### ISSUE TITLE
Can't sign transactions on form function

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#1005]
![image](https://user-images.githubusercontent.com/6990215/193832408-ebcaba80-9bc5-424e-b0d8-594466cfc43e.jpeg)

**Comment by tomlinton** [comment]
I couldn't reproduce this, bid on three things consecutively without a refresh and didn't run into an issue. Was it a hardware wallet?

**Comment by armaniferrante** [comment]
Closing as not reproduceable.
