### ISSUE TITLE
App crashes if `coingecko` requests fail

### ISSUE THREAD

**Issue by hkirat** [coral-xyz/backpack#1009]
I think coingecko is down in India right now and I'm seeing this consistently. 
If I try to send a transaction (lets say using the `provider-test` example), the app crashes. 
The issue is that coingecko returns a 502 with HTML response and we don't catch any of that [here](https://github.com/coral-xyz/backpack/blob/master/packages/recoil/src/atoms/prices.tsx#L166)

<img width="1725" alt="Screenshot 2022-10-04 at 11 25 50 PM" src="https://user-images.githubusercontent.com/8079861/193895238-97f6c745-d0f3-43ad-bc92-f8080bd15c2a.png">
<img width="1699" alt="Screenshot 2022-10-04 at 11 25 59 PM" src="https://user-images.githubusercontent.com/8079861/193895463-3d569fb1-c91d-4959-ba86-5ed72314e9c9.png">

This can probably be handled more gracefully

**Comment by jim4067** [comment]
To work on this, would I need to wrap the fetch call in a `try-catch` block eg.

```js
// Coingecko API query for all ERC20 contract addresses
const pricesForErc20Addresses = selector({
  key: "pricesForErc20Addresses",
  get: async ({ get }: any) => {
    const contractAddresses = get(erc20ContractAddresses);
    if (contractAddresses.length === 0) {
      // No contract addresses, nothing to query
      return new Map();
    }
    const params = {
      ...baseCoingeckoParams,
      contract_addresses: contractAddresses,
    };
    const queryString = new URLSearchParams(params).toString();
    try {
      const resp = await fetch(
        `https://api.coingecko.com/api/v3/simple/token_price/ethereum?${queryString}`
      );
      const json = await resp.json();
      return new Map(
        // Transform the response from id -> price data to addresss -> price data
        Object.keys(json).map((address) => [
          ethers.utils.getAddress(address),
          json[address],
        ])
      );
    } catch (err) {
      return new Map();
    }
  },
});
```

and repeat the process for all the coingecko calls here? Or is there another approach I am missing?

**Comment by hkirat** [comment]
Looks legit, can you confirm how the UI looks when this request fails?

**Comment by jim4067** [comment]
Any ideas on how I could simulate this, because when I disable my network in the dev-tools the coingecko API is not being called

**Comment by hkirat** [comment]
You can replace the `https://api.coingecko.com/api/v3/simple/token_price/ethereum?${queryString}` call with a fake call to a local server that returns a 500

**Comment by jim4067** [comment]
Here is what the UI looks like when I disable my network.

Also, @hkirat how do I force turbo to rebuild and not use the cached build?




![image](https://user-images.githubusercontent.com/30603522/203850798-5e0dd795-6fba-4a72-a2be-bd3c19d8391b.png)

**Comment by jim4067** [comment]
Everything looks okay.

![image](https://user-images.githubusercontent.com/30603522/203852615-8aa3c85f-3bd9-4d21-8424-7210b83251ff.png)
