### ISSUE TITLE
Improvement in README.md - 0. Pull the code

### ISSUE THREAD

**Issue by biccs** [coral-xyz/backpack#1010]
In order to make the documentation more accesible for new developers we shall allow them to just copy and paste some things, within the first step in the installation I encountered something that could be done better: ⬇️ 
```
git clone git@github.com:coral-xyz/backpack.git
git submodule init
git submodule update
```
I propose to add the line `cd  backpack/`  between the  second and last instructions, as in: ⬇️ 
```
git clone git@github.com:coral-xyz/backpack.git
cd backpack/
git submodule init
git submodule update
```
with this change we allow developers to just copy and paste the instruction in their terminal and they are good to go.
Because if some inexperienced dev stumbles into this and just copy and pastes it, `git submodule init `and `git submodule update` wont run because you need to be within the recently cloned repo.
Thanks for taking the time to read this issue.

**Comment by tomlinton** [comment]
https://github.com/coral-xyz/backpack/pull/958
