### ISSUE TITLE
Nan usd balance change on fresh wallet 

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#1015]
![image](https://user-images.githubusercontent.com/6990215/193960076-eded1823-20b7-43c5-8abf-35836f7f1b43.png)

**Comment by snario** [comment]
1. Installed fresh from [this zip](https://github.com/coral-xyz/backpack/releases/download/latest-2268/build-beta-2268.zip)
2. Restored existing wallet seed phrase
3. UI, under Solana, shows `+$NaN`

Console shows this:
```
Uncaught (in promise) TypeError: Failed to fetch
    at t (background.js:2:1742088)
    at new Promise (<anonymous>)
    at background.js:2:1742006
    at Array.map (<anonymous>)
    at background.js:2:1741929
    at Ic (background.js:2:1742411)
    at async background.js:2:2285772
t @ background.js:2
(anonymous) @ background.js:2
(anonymous) @ background.js:2
Ic @ background.js:2
await in Ic (async)
(anonymous) @ background.js:2
(anonymous) @ background.js:2
Ic @ background.js:2
await in Ic (async)
(anonymous) @ background.js:2
```
```
error fetching: http://walken.uk/metadata.json Error: timeout
    at background.js:2:1742051
```

**Comment by tomlinton** [comment]
I believe this was for small balances and should have been fixed by https://github.com/coral-xyz/backpack/commit/39f9d36fa3a6cec6c94352fc47a25183974efe16

Please reopen if not

**Comment by tomlinton** [comment]
Still seeing this with some large balances. It might be a separate issue but reopening this to track.
