### ISSUE TITLE
fix alpha logo positioning at different screen sizes

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#1017]
Should be able to offset it from center instead of offsetting it with a margin-right.

<img width="825" alt="Screen Shot 2022-10-05 at 9 35 23 PM" src="https://user-images.githubusercontent.com/489202/194017447-107bebcd-1dc3-4fb2-9425-95dea9153dbf.png">

**Comment by dhruvsol** [comment]
@tomlinton  Someone working on this?

**Comment by tomlinton** [comment]
No, happy to assign you if you are keen

**Comment by dhruvsol** [comment]
> No, happy to assign you if you are keen

yea sure, I will start working

**Comment by armaniferrante** [comment]
Any updated @dhruvsol?

**Comment by dhruvsol** [comment]
@armaniferrante  running a bit late almost done will make a pr soon

**Comment by dhruvsol** [comment]
So it's done I have algin it. with reference to center  but is there way to test it on bigger screen it is looking perfect on extension

**Comment by dhruvsol** [comment]
@tomlinton  How did u run it on localhost to check for bigger screen

**Comment by tomlinton** [comment]
@dhruvsol the instructions for running it locally can be found here https://github.com/coral-xyz/backpack

**Comment by dhruvsol** [comment]
@tomlinton  @armaniferrante  pr done please check when you can 

https://github.com/coral-xyz/backpack/pull/1094

**Comment by tomlinton** [comment]
Closes #1094 thank you!
