### ISSUE TITLE
Create a more minimal selector instead of `solanaTokenBalance` 

### ISSUE THREAD

**Issue by hkirat** [coral-xyz/backpack#1019]
When sending a transaction, I noticed that we only need the `native balance` of the tokens (https://github.com/coral-xyz/backpack/blob/master/packages/recoil/src/hooks/useTransactionData.tsx#L242) to simulate the transaction and not their USD value. 
The hook that we use [here](https://github.com/coral-xyz/backpack/blob/master/packages/recoil/src/hooks/useTransactionData.tsx#L183) calculates the USD values of the users tokens before returning (which the useTransactionData hook doesn't really need). 

So when a user tries to send a transaction, we have
1. an extra call to `coingecko` which slows down the time it takes for the hook to resolve (and the user to see the `approve button` enabled)
2. Can lead to crashes if `coingecko` goes down (which would be fixed after #1009)

Does it make sense to have a more minimal hook (solanaNativeTokenBalance) that doesn't need the USD values? `solanaTokenBalance` can probably re-use `solanaNativeTokenBalance`. 

Same logic can be applied to `ethereumTokenBalance`

**Comment by tomlinton** [comment]
Yea this makes sense. Related https://github.com/coral-xyz/backpack/issues/755
