### ISSUE TITLE
Multiple(Five) Backpack windows opening on OpenSea refresh. 

### ISSUE THREAD

**Issue by nickFNY** [coral-xyz/backpack#1021]
While attempting to list an NFT on OpenSea, which requires two transactions, First transaction went through, the second failed. The user refreshed OpenSea and backpack opened up 5 different wallet windows. Screen Shot included. 

![example105](https://user-images.githubusercontent.com/63250024/194119940-ac845ce3-6f34-4d37-940c-e4317d2186ff.png)

**Comment by tomlinton** [comment]
This will be resolved in the next release.
