### ISSUE TITLE
Add link component

### ISSUE THREAD

**Issue by avneesh0612** [coral-xyz/backpack#1026]
Currently there is no way to add a link afaik because we can't add an anchor tag and I can't see any Link component from `react-xnft`

**Comment by hkirat** [comment]
This is currently not possible because don't have `allow-popups` enabled on the xnft iframe. 
Can't think of any security concerns not to allow popups on xnfts. 
Can be a design concern if a certain xnft opens up a bunch of popups making the overall experience bad.

**Comment by avneesh0612** [comment]
hmm I see. Many times we would want to show people the transaction links so maybe a way to open the explorer directly into backpack?

**Comment by armaniferrante** [comment]
You can open up new windows/tabs via `window.xnft.openWindow`

**Comment by armaniferrante** [comment]
Closing as we have react-native now.

**Comment by avneesh0612** [comment]
sweet, gotta try it out 👀

**Comment by armaniferrante** [comment]
Checkout https://github.com/coral-xyz/xnft-quickstart!
