### ISSUE TITLE
user unable to import ETH ledger addresses

### ISSUE THREAD

**Issue by nickFNY** [coral-xyz/backpack#1031]
User not able to add ledger eth, stuck loading on import accounts

discord: [https://discord.com/channels/971847939456639047/1025538150719819797/1027496032084447262](url)

**Comment by tomlinton** [comment]
Not much context in the Discord discussion but likely solution to this is https://github.com/coral-xyz/backpack/issues/980 so will close as a duplicate.

**Comment by tomlinton** [comment]
Looked further into this and found it to be a separate issue.
