### ISSUE TITLE
When approving a transaction, the wallet pops up as a new window instead of from the extension bar. AND the approve button is hidden 

### ISSUE THREAD

**Issue by nickFNY** [coral-xyz/backpack#1037]
When approving a transaction, the wallet pops up as a new window instead of from the extension bar. AND the approve button is hidden so the new window must be extended to view the approve button. OS: windows 

https://user-images.githubusercontent.com/63250024/194605200-2c3fd1fc-3c9a-4fd4-aedf-dcfea27a3289.mp4

discord: [https://discord.com/channels/971847939456639047/1025538150719819797/1027940226099839066](url)

**Comment by nickFNY** [comment]
Another example connecting wallet to jup


https://user-images.githubusercontent.com/63250024/194610521-db3ffa6b-5600-4e28-a1fd-b15788c31c97.mp4

**Comment by 0xInq** [comment]
related to #976

**Comment by tomlinton** [comment]
Popping as a new window is expected behaviour, but unsure about why the wallet overflows. I think this is likely the same as https://github.com/coral-xyz/backpack/issues/981

**Comment by armaniferrante** [comment]
dup of https://github.com/coral-xyz/backpack/issues/981
