### ISSUE TITLE
Infinite loop when opening Ethereum wallet on CryptoPunks site

### ISSUE THREAD

**Issue by steveluscher** [coral-xyz/backpack#1038]
#### Repro

1. Install Backpack
2. Visit https://cryptopunks.app/cryptopunks/forsale (I used Brave)

Observe that infinite wallet dialogs open.

https://user-images.githubusercontent.com/13243/194636896-d2044309-f3a3-4d68-ba3f-80891e1047fd.mov

I didn't dig into whether this owes itself to Backpack, or to their implementation.

**Comment by armaniferrante** [comment]
@tomlinton was this addressed by https://github.com/coral-xyz/backpack/pull/911 ?

**Comment by armaniferrante** [comment]
Related https://github.com/coral-xyz/backpack/issues/1021

**Comment by tomlinton** [comment]
Yea this should be solved. Are you on the latest build?

**Comment by steveluscher** [comment]
This was with whatever's in the Chrome Web Store. v0.1.0.

**Comment by tomlinton** [comment]
Thanks, this was fixed in https://github.com/coral-xyz/backpack/pull/971. Chrome submission is pending for a build with that fix in it.
