### ISSUE TITLE
invalid DOM nesting warning in development

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#1045]
<img width="899" alt="Screen Shot 2022-10-08 at 12 12 56 PM" src="https://user-images.githubusercontent.com/489202/194691656-f42974b1-5959-42fe-b384-bd06121bee0d.png">

**Comment by gala25** [comment]
I'd like to have a stab at it 🙂

**Comment by armaniferrante** [comment]
Closed by https://github.com/coral-xyz/backpack/pull/1066
