### ISSUE TITLE
Error: keyring store is not unlocked - showing blank screen after importing wallet on edge build

### ISSUE THREAD

**Issue by nickFNY** [coral-xyz/backpack#1058]
USER: download the 2347 edge build from github. Disabled the old extension and enabled the new version. When I try to import my existing wallet, i get through the recovery phrase, set my new password, and then it just shows a blank screen

There is an error showing in the extension
Uncaught (in promise) Error: keyring store is not unlocked

discord: [https://discord.com/channels/971847939456639047/1025538150719819797/1028952763528392774](url)

**Comment by tomlinton** [comment]
Thanks @nickFNY, closing in favour of https://github.com/coral-xyz/backpack/issues/1062 following discussion in Discord.
