### ISSUE TITLE
Unable to unlock using password

### ISSUE THREAD

**Issue by hkirat** [coral-xyz/backpack#1068]
Not sure if everyone is seeing this but I'm unable to unlock my wallet in the recent build (using the password)

EDIT: the following explaination is wrong please ignore - 
> Didn't look too deep into it but it seems like `withPassword` fails [here](https://github.com/coral-xyz/backpack/blob/master/packages/background/src/backend/keyring/index.ts#L368) because `isUnlocked` is true (even though I see the password screen) because `this. lastUsedTs` is not 0 [here](https://github.com/coral-xyz/backpack/blob/master/packages/background/src/backend/keyring/index.ts#L313)

cc @tomlinton could be related to https://github.com/coral-xyz/backpack/pull/1042 or https://github.com/coral-xyz/backpack/pull/1016 but I might be wrong

**Comment by armaniferrante** [comment]
Related to https://github.com/coral-xyz/backpack/pull/1063 ?

**Comment by hkirat** [comment]
Don't think so the password I'm using is `123random`. Used to work until a few days ago.

**Comment by hkirat** [comment]
Error seems to originate here when I unlock my wallet for the first time - 

<img width="935" alt="Screenshot 2022-10-11 at 11 40 35 PM" src="https://user-images.githubusercontent.com/8079861/195167786-b78411ff-d8c9-4e01-9fd5-a977bd864cc5.png">

<img width="381" alt="Screenshot 2022-10-11 at 11 40 43 PM" src="https://user-images.githubusercontent.com/8079861/195167645-0b98f482-be8b-4308-8741-c8514fba6d79.png">

I have both eth and sol enabled in my wallet

**Comment by tomlinton** [comment]
This will be related to #1042, is it consistent?

**Comment by hkirat** [comment]
Yup just confirmed it in two different browsers. Consistently can't unlock my wallet after I add eth to the list of chains

**Comment by tomlinton** [comment]
Does the reproduction look like:

- Onboard
- Click through to preferences and hit `Enable` next to `Ethereum`
- Lock wallet
- Attempt unlock

**Comment by hkirat** [comment]
That is correct @tomlinton
