### ISSUE TITLE
First digit of Auto Lock Timer cannot be deleted with 'delete' key. must be highlighted then new digit typed

### ISSUE THREAD

**Issue by nickFNY** [coral-xyz/backpack#1074]
First digit of Auto Lock Timer cannot be deleted with 'delete' key. must be highlighted then new digit typed

Ex. 15 is default. Delete key will remove the 5 but get stuck in front of the 1. To change to '20' must highlight the numbers and type 20 on the keypad.

**Comment by gala25** [comment]
I can take this one.
