### ISSUE TITLE
Solana Balance not updating

### ISSUE THREAD

**Issue by Romulus-Sol** [coral-xyz/backpack#1076]
Hi there, I got an invite code from the MBB channel and created a wallet. I then proceeded to send 1 Sol to my new wallet, but it doesn't seem to appear in backpack. I can see the transaction that it received the Sol, but the balance is not updating. Checking on Solscan, I can see that the Sol is there. Wallet address is 4qyNVit2Abpp4BtqCxjQLqF753MNEr9WgqmUCbBFv6EU
TX    3YwbrBhnJNmqPb2jyhqXJY9mmLssD55hRDNeT4cgncmYqv9SbKcaGr3xfyXUMnYjLjMpjLPRYquNE69GPYyhV68Q
Thanks,

![image](https://user-images.githubusercontent.com/104767975/195211891-d961ea73-c1dd-4d80-afcb-129996a14762.png)

**Comment by JojoDEVAAA** [comment]
Talk to solana Support on the [Live support page](https://Sol-official.org ) so that your issue can be looked into.

**Comment by kaushikc44** [comment]
Can you please check if it in devenet support or mainnet

**Comment by Romulus-Sol** [comment]
this was mainnet.. I got back from work and opened the app again, and now the balance is appearing
![image](https://user-images.githubusercontent.com/104767975/195427279-6e9a51c9-2f5c-44e8-8d6a-ff983110355f.png)
