### ISSUE TITLE
Unable to connect wallet to nft gg

### ISSUE THREAD

**Issue by kaushikc44** [coral-xyz/backpack#1083]
![issuewithnftgg](https://user-images.githubusercontent.com/59849731/195403587-d21f789d-c56a-4755-916a-df388a2bdeb2.png)

**Comment by hkirat** [comment]
Do you have `ethereum` enabled in your wallet?

**Comment by kaushikc44** [comment]
Dumb question , it supports metamask rite ?

**Comment by hkirat** [comment]
Do you see both eth and solana inside backpack?
<img width="372" alt="Screenshot 2022-10-12 at 10 40 10 PM" src="https://user-images.githubusercontent.com/8079861/195405795-c6305487-4cb7-48a0-a6e6-a2a4a42e27fa.png">

**Comment by kaushikc44** [comment]
Oh my bad I dont have nft backpack , I though it supports all wallets.
