### ISSUE TITLE
window.xnft.sendAndConfirm should block the UI and show a loading indicator until transaction is confirmed

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#1085]
Something similar to token sending

![image](https://user-images.githubusercontent.com/6990215/195423374-07198f2e-e15e-44f3-8cad-57faf9ae8223.png)
![image](https://user-images.githubusercontent.com/6990215/195423390-700fcaa8-96ef-4665-b846-d8183b775cf8.png)

**Comment by Benhawkins18** [comment]
Having an option to set the message and or content would make it even sweeter but not required.
