### ISSUE TITLE
Wallet unable to load any balances on burp suite browser 

### ISSUE THREAD

**Issue by nickFNY** [coral-xyz/backpack#1089]
https://discord.com/channels/971847939456639047/1025538150719819797/1029873687484190880Discord: [](url)

![burperror2](https://user-images.githubusercontent.com/63250024/195457189-a176e738-89f1-449b-9dce-572281d40e35.png)
![errorburp1](https://user-images.githubusercontent.com/63250024/195457192-991a639b-0895-4f93-b4bd-8d8f78f655ee.png)

**Comment by tomlinton** [comment]
This is not burp suite?

Related https://github.com/coral-xyz/backpack/issues/877

**Comment by tomlinton** [comment]
This is most likely Burp proxies altering the request somehow so not something we'll fix.
