### ISSUE TITLE
When entering incorrect password and then entering the correct password extension does not log in

### ISSUE THREAD

**Issue by gala25** [coral-xyz/backpack#1092]
Steps to reproduce: 

1. Open the backpack dev extension.
2. Input an incorrect password.
3. Delete and input the correct password
4. Press Enter or click Unlock

Expected result: 
It should log in to Backpack

Actual result:
It stays on the log in page with the password highlighted in red

Additional problem: 
When this issue happens, if you close and reopen Backpack it crashes with an error - `Error: no keyring for blockchain`

**Comment by tomlinton** [comment]
The unlock code assumes any exception is an [incorrect password ](https://github.com/coral-xyz/backpack/blob/f1d6c4b3796c528e0a2c1dcdac5c515ab75508e7/packages/app-extension/src/components/Locked/index.tsx#L33) so what is likely happening is that `Error: no keyring for blockchain` is being represented as an incorrect password. The next time you open backpack that same exception is not caught so it crashes (i.e. the first time you entered the password it was correct and the wallet was successfully unlocked).

The error `Error: no keyring for blockchain` is being tracked in https://github.com/coral-xyz/backpack/issues/1095

**Comment by tomlinton** [comment]
Actually looks like you were right! Ignore the above, thanks for the report :)
