### ISSUE TITLE
no keyring for blockchain error

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#1095]
![Screen Shot 2022-10-13 at 11 21 49 AM](https://user-images.githubusercontent.com/6990215/195638161-59099cc3-8a1c-499f-a3c9-920bb8db7bd8.png)

**Comment by armaniferrante** [comment]
No

**Comment by hkirat** [comment]
Was able to reproduce the `approval popup` showing up even though eth is disabled - 
<img width="597" alt="Screenshot 2022-10-13 at 9 24 03 PM" src="https://user-images.githubusercontent.com/8079861/195645575-0bdeb0da-fbd8-4798-ba2e-6b161e1a8f43.png">
<img width="1276" alt="Screenshot 2022-10-13 at 9 18 58 PM" src="https://user-images.githubusercontent.com/8079861/195645559-255eb7d9-56e4-4f96-80b1-9155688d0b09.png">

Steps to reproduce - 
1. Install latest build
2. Setup a new wallet
3. Start the simple client
4. Try connecting to eth

**Comment by tomlinton** [comment]
@hkirat that is a separate issue https://github.com/coral-xyz/backpack/issues/1056

**Comment by armaniferrante** [comment]
Dup of https://github.com/coral-xyz/backpack/issues/1092#issuecomment-1278248388
