### ISSUE TITLE
When downloading an xNFT, a black window appears directly over the approve transaction window. Have to move black screen to see it. 

### ISSUE THREAD

**Issue by nickFNY** [coral-xyz/backpack#1097]
When downloading an xNFT, a black window appears directly over the approve transaction window. Have to move black screen to see it. 

<img width="718" alt="Screen Shot 2022-10-13 at 11 51 55 AM" src="https://user-images.githubusercontent.com/63250024/195657880-c6abbbc7-1f56-46f3-9605-de9cadfcc48c.png">
<img width="459" alt="Screen Shot 2022-10-13 at 11 51 47 AM" src="https://user-images.githubusercontent.com/63250024/195657886-9302cf2a-bc76-4e1b-83cd-afdedbff908a.png">

**Comment by armaniferrante** [comment]
Does the user have two different instances of the backpack extension installed?

**Comment by nickFNY** [comment]
Yes. edge and chrome store. (it's me)

**Comment by armaniferrante** [comment]
Then the two popups is currently expected. The black one seems to have a dead service worker. Dup of https://github.com/coral-xyz/backpack/issues/990.
