### ISSUE TITLE
Ability to set text-align in TextField input

### ISSUE THREAD

**Issue by 0xCactus** [coral-xyz/backpack#1100]
Would be nice to have a prop on TextField for setting text align left (default), right or center

<img width="364" alt="Screen Shot 2022-10-13 at 5 02 51 PM" src="https://user-images.githubusercontent.com/85321734/195710012-d545c28c-c013-4bc4-8674-5048e7957007.png">

**Comment by armaniferrante** [comment]
related: https://github.com/coral-xyz/backpack/issues/686

**Comment by armaniferrante** [comment]
Moving to react-native. Closing.
