### ISSUE TITLE
Alignment off with new applications icon

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#1107]
<img width="182" alt="Screen Shot 2022-10-13 at 6 56 24 PM" src="https://user-images.githubusercontent.com/321395/195732753-5377ad27-8170-4918-a4a9-cba1067b8fa7.png">

We recently reduced the size of the icons in the bottom nav from 24 to 20 px, but whenever we reuse the icons, they need to be a 20px shape within a 24px frame to line up vertically with the other icons on your Profile/Settings page or anywhere else we're using them alongside 24px icons.

Attached icons that should help with this

![balances](https://user-images.githubusercontent.com/321395/195732506-ef79849d-0173-4e07-a9e7-206d5d63a97c.svg)
![nfts](https://user-images.githubusercontent.com/321395/195732511-148dc9f8-ddda-42e6-9701-8b08d296521d.svg)
![applications](https://user-images.githubusercontent.com/321395/195732514-049bf587-7b97-4ecb-b4ff-15691d732196.svg)

**Comment by armaniferrante** [comment]
Closed by 2c6b70bb59f1805b63d55e89d46e1019e388a1bb
