### ISSUE TITLE
some long mnemonic words are getting clipped by their container elements

### ISSUE THREAD

**Issue by wentokay** [coral-xyz/backpack#1108]
![Screen Shot 2022-10-13 at 20 20 59](https://user-images.githubusercontent.com/101902546/195740382-0990d6a6-f925-4da0-aafe-7844eb6ca49e.png)

the "r" at the end of remember is hidden in the above example

**Comment by armaniferrante** [comment]
Note this only was clipped in settings. Not in the onboarding flow. Closed by 87f386cf3dbde23ce9b7416b7b93efba574893b1.
