### ISSUE TITLE
Consolidate Blockchains Enable/Disable function into Solana and Ethereum menu with checkboxes

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#1109]
Idea is to remove one layer of nesting make it easier to enable and disable blockchains shown. Leftmost is current behavior, middle and right are the proposed change

<img width="1166" alt="Screen Shot 2022-10-13 at 8 30 23 PM" src="https://user-images.githubusercontent.com/321395/195741252-5aa29fb3-ca49-47c1-a2ef-4f868e420c77.png">

**Comment by armaniferrante** [comment]
two changes:

1) remove this blockchains section
2) add the enable blockchain toggles into each respective blockchain preference at the top as a separate section
