### ISSUE TITLE
allow .sol and .eth domains in send to fields

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#1111]
Needs it for both token and NFT sends

**Comment by Gajesh2007** [comment]
like people can send their USDC/SOL/ETH to a SNS or ENS address?

**Comment by tomlinton** [comment]
Yea, the field validation prevents it right now. Should work without any further changes for Ethereum.  Not sure about Solana.

**Comment by tomlinton** [comment]
Closed by #1156
