### ISSUE TITLE
Need to expand window to approve xNFT instillation tx (OS Windows 10, Brave)

### ISSUE THREAD

**Issue by nickFNY** [coral-xyz/backpack#1128]
Need to expand window to see 'approve' button on xNFT instillation tx (OS Windows 10, Brave)

discord: [https://discord.com/channels/971847939456639047/1025538150719819797/1030546314003501056](url)

![bp2](https://user-images.githubusercontent.com/63250024/195940444-6d28b4d4-530d-494d-a952-8145bdb67247.png)
![bp1](https://user-images.githubusercontent.com/63250024/195940446-025472ab-d3ca-4690-bccb-a9811395c482.png)

**Comment by armaniferrante** [comment]
Dup of https://github.com/coral-xyz/backpack/issues/569
