### ISSUE TITLE
Copy update for "Trusted Apps"

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#1129]
Can we change "Trusted Apps" to "Trusted Sites" to avoid confusion with the Applications tab? The new description also calls out this is determined by the user thanks to @johnrees 

New design [here](https://www.figma.com/file/HNF2HJZYq6dUzCWxSmH2Oe/Backpack-_-Questlog?node-id=10249%3A37086)

There are at least two places to change: empty state and the menu option title in Profile > Preferences

**Comment by ritvij14** [comment]
I would like to give it a try.

**Comment by ritvij14** [comment]
@trucy how can I view the design that's needed.

**Comment by armaniferrante** [comment]
@ritvij14 

<img width="555" alt="Screen Shot 2022-10-16 at 9 31 26 AM" src="https://user-images.githubusercontent.com/6990215/196038218-23a88bd7-0eea-48d9-bf3f-210eec051cd0.png">

**Comment by ritvij14** [comment]
@armaniferrante got it 👍🏻 I will get started
