### ISSUE TITLE
investigate metamask breakage

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#1134]
I suspect this has to do with both extensions fighting for window.ethereum. See https://github.com/MetaMask/metamask-extension/issues/16088.

**Comment by tomlinton** [comment]
This should have gone away with https://github.com/coral-xyz/backpack/pull/911. Hard to verify what version they are using but the issue/comments were prior to 0.2.0 which I believe included https://github.com/coral-xyz/backpack/pull/911.

**Comment by armaniferrante** [comment]
I think this is likely fixed in the latest version. The person who pointed out the above metamask issue can no longer reproduce.
