### ISSUE TITLE
checkbox check mark  invisible in dark mode

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#1150]
Check mark is white, it needs a better colour. This is checked:

<img width="383" alt="Screen Shot 2022-10-17 at 12 47 45 PM" src="https://user-images.githubusercontent.com/489202/196108802-586bd3f8-b07d-47a1-a499-188a3ea39124.png">

**Comment by AFZL210** [comment]
@hkirat , can you please assign it to me? I would love to work on this.

**Comment by hkirat** [comment]
@AFZL210 go for it.
Please try using a color from the color pallet in the `themes` package rather than adding a new one

**Comment by AFZL210** [comment]
@hkirat Okay, I'll use the suggested color. Thanks!

**Comment by AFZL210** [comment]
@hkirat  I have set up the repository locally, can you please give me an invite code so I can reproduce the issue?

**Comment by wentokay** [comment]
we've now emailed you a code, thanks

**Comment by AFZL210** [comment]
I haven't received it yet, can I share my registered email here? @wentokay

**Comment by wentokay** [comment]
You can use this @AFZL210 `7163b072-5bcb-4e50-8dc2-2eefa0286579`

**Comment by AFZL210** [comment]
can you please tell me how can I reproduce this issue, I'm new to backpack
