### ISSUE TITLE
add Backpack to wagmi

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#1183]
https://github.com/wagmi-dev/wagmi

**Comment by Gajesh2007** [comment]
wagmi has injected connector support. projects can use it for backpack integration right?

**Comment by tomlinton** [comment]
Yea, but we should add name etc https://github.com/wagmi-dev/wagmi/blob/ed130747c0f28c1d9980a1328883e4000a60455e/packages/core/src/utils/getInjectedName.ts

**Comment by ph101pp** [comment]
https://github.com/wagmi-dev/references/pull/168
