### ISSUE TITLE
Clicking on NFT crashes app

### ISSUE THREAD

**Issue by hkirat** [coral-xyz/backpack#1186]
https://discord.com/channels/985994296337498182/1011846320677462137/1031860466949034024

**Comment by hkirat** [comment]
<img width="1167" alt="Screenshot 2022-10-18 at 3 14 11 PM" src="https://user-images.githubusercontent.com/8079861/196396296-392350b9-071a-4871-b4ea-e36f24989e63.png">

**Comment by armaniferrante** [comment]
I'm unable to reproduce.

**Comment by hkirat** [comment]
Same
We need a way to better extract stack traces from `popup.js` somehow.

**Comment by tomlinton** [comment]
Might be something specific about that NFT.

https://github.com/coral-xyz/backpack/blob/0427af20148dd3fdb9c3c0f072bae85fea26a45b/packages/common-public/src/utils.ts#L58-L63 might be possible if the passed URL is undefined.

**Comment by hkirat** [comment]
Great eye 👁️ . Will add a catch and see if that fixes it for the user
