### ISSUE TITLE
deceptive site warnings

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#1227]
Right now junk NFTs can be sent to a wallet and a big red warning sign will be displayed. This is a bad user experience. We should display a more informative message.

**Comment by hkirat** [comment]
Is this the same as https://github.com/coral-xyz/backpack/issues/1227 ? Or are we talking about some other warning here?

**Comment by hkirat** [comment]
Taking the approach of relaying these from a server of our own to avoid the warnings
