### ISSUE TITLE
Unable to connect my wallet on xnft.gg

### ISSUE THREAD

**Issue by hkirat** [coral-xyz/backpack#1234]
<img width="1408" alt="Screenshot 2022-10-22 at 10 12 58 PM" src="https://user-images.githubusercontent.com/8079861/197352247-6d6d0f88-c6d1-438c-ab29-a790fb6b8fa2.png">

**Comment by hkirat** [comment]
Had to close and re-open chrome

**Comment by hkirat** [comment]
Way to reproduce - https://discord.com/channels/985994296337498182/1011846320677462137/1033853025913155595

**Comment by hkirat** [comment]
Happened again here - https://discord.com/channels/985994296337498182/1011846320677462137/1035603903024210010

**Comment by tomlinton** [comment]
If you have an approval prompt open and you don't either approve/deny this will happen. Is that what is happening here?

**Comment by hkirat** [comment]
Maybe, I'm unsure if I had a lingering approval prompt open. 
Maybe I didn't approve or deny on one of them (since I have two wallets)

**Comment by tomlinton** [comment]
It sounds like it is working as intended (restricting the number of approval popups to window) but it also seems to be causing some confusion. Will have to think about a solution.

**Comment by hkirat** [comment]
Maybe if a user deliberately clicks on `Connect` we should trigger a new popup?

**Comment by hkirat** [comment]
Yeah that should do it

**Comment by hkirat** [comment]
We'd need a way to figure out when a user clicked on the `connect` button vs was `auto connected` else this'll get very confusing to the end user when popups close and re-open automatically on `auto connects`.

**Comment by tomlinton** [comment]
That was built to prevent sites spamming popups, closing the old one and opening a new one has basically the same problem as spamming popups everywhere

**Comment by hkirat** [comment]
Makes sense. I think it makes sense to close this for now then. 
I'll keep an eye out for when this happens again to see if I'm missing an open popup. Will re-open if that's not the case (looking at the locking logic I most probably had a lingering popup).
Thanks for the clarification @tomlinton

**Comment by tomlinton** [comment]
It might make sense to just focus the open popup (if possible)

**Comment by hkirat** [comment]
Looking at chrome docs it may not be possible. It's possible to open it in `panel` mode it seems but that `flag` is not on by default so it'll go out of focus for most users.
Ref https://stackoverflow.com/questions/13574825/chrome-extension-create-window-alwaysontop
