### ISSUE TITLE
Support refs in ReactXnft

### ISSUE THREAD

**Issue by hkirat** [coral-xyz/backpack#1255]
Would let users do things like use https://github.com/streamich/react-use/blob/master/docs/useScroll.md and control audio and video elements. Bunch of other use cases I can think of. Shouldn't be a security concern now that rendering happens inside an iframe. Worried about mobile though and how it might affect things there

**Comment by lndgalante** [comment]
Yes +1 to this, any hook that needs a ref i.e

[https://www.npmjs.com/package/react-detect-click-outside](https://www.npmjs.com/package/react-detect-click-outside)

**Comment by armaniferrante** [comment]
Moving to react native. Closing.
