### ISSUE TITLE
connecting wallet with disabled blockchain gives blank screen

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#1256]
Steps to reproduce:

* enable ethereum only in backpack
* go to xnft.gg
* connect wallet

And a blank screen will appear.

**Comment by tomlinton** [comment]
Related https://github.com/coral-xyz/backpack/issues/1056, suggested solution is to allow them to enable from that screen, but in the short term we might just display an error with the suggested fix, i.e. `Enable Solana in the settings menu.`.

**Comment by tomlinton** [comment]
https://github.com/coral-xyz/backpack/pull/1376
