### ISSUE TITLE
Simulator bug: Simulator keeps auto-reopening 

### ISSUE THREAD

**Issue by greenish** [coral-xyz/backpack#1273]
Backpack & Simulator are getting into a bad state when:

- Simulator is open (click outside of Backpack to close the popup)
- window.xnft.openWindow("...")  ie click "open" on any xnft on xnft.gg.

Now the simulator will open whenever backpack is opened or you navigate to the apps tab.

The only way to get out of this state is to completely remove backpack from chrome.

**Comment by 0xInq** [comment]
+1 seeing the same thing happening
