### ISSUE TITLE
Customize avatar for xNFTs profile - Why can't we set our own avatar by passing image url or NFT address to useAvatarUrl component

### ISSUE THREAD

**Issue by BalanaguYashwanth** [coral-xyz/backpack#1283]
<img width="817" alt="image" src="https://user-images.githubusercontent.com/36238382/198034029-09a8d4da-40a1-4e51-b3ba-d3c3e102bf14.png">

**Comment by armaniferrante** [comment]
Indeed. This is on the stack.

**Comment by armaniferrante** [comment]
Done.
