### ISSUE TITLE
stuck on sign the message screen when connecting ethereum ledger

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#1300]
<img width="1168" alt="Screen Shot 2022-10-27 at 8 41 03 AM" src="https://user-images.githubusercontent.com/6990215/198286867-17e5a955-ffca-479c-b656-156a9938903d.png">

**Comment by armaniferrante** [comment]
<img width="1684" alt="Screen Shot 2022-10-27 at 8 43 42 AM" src="https://user-images.githubusercontent.com/6990215/198287424-cbb3a632-b966-48fb-b8bb-574f8f838309.png">

**Comment by tomlinton** [comment]
I can reproduce this with usernames/invite codes disabled, was that the setup?

I've just got to not prompt for a signature in that case as there is nothing to sign (usually the invite code is signed).

**Comment by armaniferrante** [comment]
Correct. Although on solana i was able to sign.

**Comment by tomlinton** [comment]
Great, makes sense because Solana is signing a pretend transaction whereas Ethereum is trying to sign an empty string.
