### ISSUE TITLE
Obscure Fungible token appears as NFT under 'No collection'

### ISSUE THREAD

**Issue by nickFNY** [coral-xyz/backpack#1304]
User has a fungible token, FOMO, which appears as an NFT under the 'No Collection' category. Shared examples of how appears in Backpack vs Phantom

discord: [https://discord.com/channels/971847939456639047/1025538150719819797/1035299757767270430](url)

<img width="273" alt="Screenshot_7" src="https://user-images.githubusercontent.com/63250024/198400462-59b4dc5b-57ac-4afb-8298-f65d9777dae8.png">
![IMG_0587](https://user-images.githubusercontent.com/63250024/198400465-b1aad069-3f2e-4f18-991c-95ffd6ddf1ff.jpeg)

**Comment by nickFNY** [comment]
Re-uploading second image since didn't appear to work 
![IMG_0587 (1)](https://user-images.githubusercontent.com/63250024/198400620-53881e11-4682-4a7f-99d3-29741b957c41.jpeg)

**Comment by armaniferrante** [comment]
We need to actually check for the master edition account. Right now we're probably showing anything with metadata.

**Comment by armaniferrante** [comment]
Related https://github.com/coral-xyz/backpack/pull/1388.

**Comment by armaniferrante** [comment]
Also related https://github.com/coral-xyz/backpack/issues/1383.

**Comment by armaniferrante** [comment]
Closing in favor of the above.
