### ISSUE TITLE
Link to xnft.gg for empty state of the applications tab

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#1322]
We should have an empty state like in the nft collectbles tab where we link to xnft.gg and tell users they can get xnfts there. See how this is done with the NFTs tab.

**Comment by armaniferrante** [comment]
As part of this let's introduce a dev mode switch.

**Comment by tomlinton** [comment]
You start this @armaniferrante? Did a bit before realising you assigned yourself.
