### ISSUE TITLE
window.ethereum not reassignable

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#1324]
We don't control the order in which chrome extensions load. E.g. this order

MetaMask
Backpack

is fine, because Backpack won't clobber `window.ethereum` if it already exists.

If Backpack comes first, it assigns `window.ethereum` and due to the frozen provider changes (I believe) it is not reassignable by MetaMask if it loads second.

The solution here is probably to use a `Proxy` and handle getting/setting so that it works in all cases. An alternative would be to make `window.ethereum` writable, which probably defeats the reason for the frozen provider change.

**Comment by hkirat** [comment]
`The solution here is probably to use a Proxy and handle getting/setting so that it works in all cases` - Could you elaborate on this one @tomlinton

**Comment by tomlinton** [comment]
Working on it here https://github.com/coral-xyz/backpack/compare/tomlinton/window-ethereum-proxy

**Comment by hkirat** [comment]
Ah gotcha awesome! Assigned the issue to avoid duplication
