### ISSUE TITLE
[EDIT] Wallet did not auto-lock with xNFT open overnight. User logged back in wallet was open to xNFT, exited xNFT and wallet was functional. 

### ISSUE THREAD

**Issue by nickFNY** [coral-xyz/backpack#1326]
User had 15 minute timer on with Tiexo app open. Relogged into computer next day and xNFT was still open. They exited the xNFT and wallet was still functional. 

discord: [https://discord.com/channels/971847939456639047/1025538150719819797/1035359009995243590](url)

**Comment by nickFNY** [comment]
Update: User did not 'log out' but left the computer open overnight. So might be expected behavior.

**Comment by armaniferrante** [comment]
Dup.
