### ISSUE TITLE
confusing error in xnft renderer

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#1338]
Using a standard html element, e.g. div.

<img width="529" alt="Screen Shot 2022-10-30 at 10 26 50 PM" src="https://user-images.githubusercontent.com/489202/198871605-ab97bec9-9dc9-4136-a9a9-5e4ddb4bc855.png">

**Comment by hkirat** [comment]
@tomlinton should we show a better error message (Please use `ReactXnft` exported components) here?

**Comment by tomlinton** [comment]
Yea that'd be great, took me a while to figure out what this meant. It'd be good if the error could also contain the erroneous component (e.g. `div is not a valid ReactXnft component, please use ReactXnft exported components`)
