### ISSUE TITLE
Extension errors out when loading metadata for nfts

### ISSUE THREAD

**Issue by hkirat** [coral-xyz/backpack#1349]
Seeing this, now for metadata files. Should we be proxying these too?

<img width="164" alt="Screenshot 2022-10-31 at 3 54 18 AM" src="https://user-images.githubusercontent.com/8079861/198907215-0db0171d-db07-4f47-89d4-cddfacfa433f.png">

**Comment by armaniferrante** [comment]
dup of https://github.com/coral-xyz/backpack/issues/1043 ?

**Comment by hkirat** [comment]
yup
