### ISSUE TITLE
reset recovery phrase copy changes

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#1358]
It makes sense to change these screens in the reset recovery phrase flow to be have more generic wording as the user does not necessarily have a recovery phrase (i.e. they onboarded with a hot wallet).

I'd suggest we replace `recovery phrase` with `wallet`.

<img width="375" alt="Screen Shot 2022-10-31 at 10 53 25 PM" src="https://user-images.githubusercontent.com/489202/199037849-d31aadce-5b46-4a7b-bae1-3db297efa099.png">

**Comment by trucy** [comment]
These are all the screens that need to be updated yeah? Noticed we could probably also add an icon to match the others. 

- [Figma here](https://www.figma.com/file/HNF2HJZYq6dUzCWxSmH2Oe/Backpack-_-Questlog?node-id=13683%3A30769)
-  + SVG and screenshots for those who don't have Figma access
 
<img width="926" alt="Screen Shot 2022-10-31 at 10 52 47 AM" src="https://user-images.githubusercontent.com/321395/199051790-fbd28de0-f8ec-4a1e-a97c-7c8f2254f647.png">
![question-mark-circle](https://user-images.githubusercontent.com/321395/199051855-65e91512-9a81-4673-a4f4-e41eede2e2c5.svg)

**Comment by jim4067** [comment]
Let me check this out.

**Comment by tomlinton** [comment]
That looks right @trucy except the `proposed`/`current` labels are on the wrong set of screens.

`Reset Backpack` is another option here. `Reset Account` kind of makes it sound like it's going to do something with your actual account rather than just the local state.

**Comment by trucy** [comment]
@tomlinton whoops yeah those are switched :P Updated [Figma](https://www.figma.com/file/HNF2HJZYq6dUzCWxSmH2Oe/Backpack-_-Questlog?node-id=13683%3A30923) with your suggestion as well, and some minor copy changes
