### ISSUE TITLE
window.openXnft(pubkey) interferes with open plugins in Backpack

### ISSUE THREAD

**Issue by greenish** [coral-xyz/backpack#1360]
When window.openXnft(pubkey) is called while a plugin is open in Backpack the two query params `plugin` and `pluginProps` interfere and create unexpected states. 

This can result in Backpack entering a state that can only resolved by removing and re-adding the plugin to the browser.

**Comment by armaniferrante** [comment]
Appears resolved. Closing (please re-open if this is false).

**Comment by greenish** [comment]
yes resolved with: #1699
