### ISSUE TITLE
Popular NFT 'Critters Cult' showing up in 'No Collection' 

### ISSUE THREAD

**Issue by nickFNY** [coral-xyz/backpack#1362]
Popular NFT 'Critters Cult' showing up in 'No Collection' 

discord: [https://discord.com/channels/971847939456639047/1025538150719819797/1036675567820484668](url)

<img width="269" alt="Screenshot_7 (1)" src="https://user-images.githubusercontent.com/63250024/199060740-7372d5d4-eeb0-45b7-a11e-82e3e44dec07.png">

**Comment by armaniferrante** [comment]
Closing in favor of #382.
