### ISSUE TITLE
User can not connect / send transactions in backpack xNFT in the chrome extension b/c ctx.sender.tab is undefined

### ISSUE THREAD

**Issue by tj-dispatch** [coral-xyz/backpack#1371]
Steps to repro:

1) Install the dispatch app: https://www.xnft.gg/app/7U6WUC33Pwh59kZ6HFng61Tx4ESbD4fkCmcnjVxdZv81
2) Open the dispatch app
3) Try to connect, then try to send a transaction
4) See the errors in the console in chrome for the app

The error comes from this part of the code (well, any part that checks ctx.sender.tab.title):
https://github.com/coral-xyz/backpack/blob/master/packages/background/src/frontend/server-injected.ts#L240

There is an error from the @mui/material package you are using that is probably causing it (see screenshots here: https://discord.com/channels/985994296337498182/1011846320677462137/1036719443931300010)

I am not sure why the tab would be undefined -- perhaps this is a configuration issue on my end where I was supposed to define something and didn't?

**Comment by armaniferrante** [comment]
Labeling as P1 as this is blocking the release of the dispatch xNFT.
