### ISSUE TITLE
tab url gets overriden with incorrect tab

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#1385]
Backpack can get into an unfixable state where you can't select a certain tab. See the video here.

https://user-images.githubusercontent.com/6990215/198447057-80b2d04c-ab55-42f9-a7c8-0f884d9edca6.mov

**Comment by armaniferrante** [comment]
If you get into this state and look at the navigation storage, you can see that the storage for one tab has a totally incorrect URL, so we are somehow causing it to be overwritten.

<img width="911" alt="Screen Shot 2022-11-01 at 8 10 06 PM" src="https://user-images.githubusercontent.com/6990215/199364899-cc8f88ad-ef57-4b32-b3f5-e8f0d9b98c9e.png">

Note: this screenshot doesn't match the video above, but the idea/issue is still the same. The video is unable to click on the third NFT tab, and the screenshot here is unable to click on the first Balances tab.

**Comment by hkirat** [comment]
Strong inkling it is some sort of race condition when `UI_RPC_METHOD_NAVIGATION_CURRENT_URL_UPDATE` gets called but the active tab changes. Unable to reproduce though

**Comment by hkirat** [comment]
Able to reproduce if I increase this timeout - https://github.com/coral-xyz/backpack/blob/master/packages/app-extension/src/components/Unlocked/DisplayPlugin.tsx#L61 and quickly navigate to another tab before the `UI_RPC_METHOD_NAVIGATION_CURRENT_URL_UPDATE` call fires
