### ISSUE TITLE
wallet goes black if connected to a xnft.gg without a SOL wallet

### ISSUE THREAD

**Issue by gonzalo-ftx** [coral-xyz/backpack#1386]
Ideally, the wallet would prompt the user to create a network's wallet upon recognizing that it is attempting to be connected through that network. This is especially noticeable for users who onboard via ETH and then try to connect to xnft.gg

https://user-images.githubusercontent.com/104650166/199400108-25d86f57-1872-4be3-a293-8b960c1fbb49.mov

**Comment by tomlinton** [comment]
This was fixed here https://github.com/coral-xyz/backpack/commit/3dc4d16acf5762beed82c3dfd3b1774fb8062ea3 and will be in the next release.
