### ISSUE TITLE
burnt nft transaction error

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#1390]
<img width="375" alt="Screen Shot 2022-11-02 at 10 55 33 AM" src="https://user-images.githubusercontent.com/489202/199472206-5274e120-e4a5-4337-ba0d-716454f1c213.png">

**Comment by tomlinton** [comment]
https://solscan.io/account/H4YJ7ESVkiiP9tGeQJy9jKVSHk98tSAUD3LqTowH9tEY is the account, `StarAtlas Anniversary` NFT https://solscan.io/token/7kj48tKix2732ZP3Bhf1tnmd7ZaFe9wsajw7xHHjRrCr is the NFT. Note the account has a balance of 9, but Backpack only shows 1. Might be related.

**Comment by armaniferrante** [comment]
Error https://github.com/solana-labs/solana-program-library/blob/master/token/program/src/error.rs#L52-L54
