### ISSUE TITLE
autolock timer not working

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#1393]
Some reports in Discord that the autolock timer doesn't lock after the specified period:

> I cant seem to get my wallet (Mac, Brave Browser) to respect the autolock timer that i set. It keeps locking either a minute or two after i open it, and also after most app interactions.

**Comment by jim4067** [comment]
Maybe this is a bug on Mac. 

I am also on brave but using Linux(Pop OS) and auto-lock works.  I set it to lock after one minute and it worked.

**Comment by tomlinton** [comment]
> Maybe this is a bug on Mac OS.
> 
> I am also on brave but using Linux(Pop OS) and auto-lock works. I set it to lock after one minute and it worked.

The issue is not that it doesn't lock, it is that using the wallet (e.g. UI interactions) should reset the timer so it doesn't lock. In your case you'll find it'll lock after a minute regardless of what you are doing with the wallet.

**Comment by jim4067** [comment]
Spent the better part of my day testing this out. Found out that the mouse events were not being registered(might be wrong though)

A few questions?
If I am guessing correctly, [`lastUsedTs`](https://github.com/coral-xyz/backpack/blob/7a45b27d9c7c24240ea03f6da72654eeca368f9c/packages/background/src/backend/keyring/index.ts#L36) is the variable that records the last time backpack was used right? 
The setter method to update this variable would be [`updateLastUsed`](https://github.com/coral-xyz/backpack/blob/7a45b27d9c7c24240ea03f6da72654eeca368f9c/packages/background/src/backend/keyring/index.ts#L430)?

**Comment by tomlinton** [comment]
That's right, here is one approach that didn't quite solve this https://github.com/coral-xyz/backpack/pull/1478

**Comment by jim4067** [comment]
Thanks. Surprised that the PR captured what I was thinking too. 

Hadn't thought about that edge case of registering events when using xNFTs or playing flappy bird. 
I also think that we could update the auto-lock timer using the various `UI_RPC_METHOD`s and `notification-navigation-url-did-change`. My only concern would be that this would result in a lot of code repetition and knowing which methods to call and avoid calling.

On implementing a permanent option for auto-lock, these issues would also be partly resolved #1394 and #1533

**Comment by jim4067** [comment]
@tomlinton I personally would have preferred to have the new RPC to reset the autolock timer and set it to never lock when an

**Comment by tomlinton** [comment]
That sounds like the approach I described here? https://github.com/coral-xyz/backpack/pull/1478#discussion_r1021011451

**Comment by jim4067** [comment]
It is. I was wondering whether I could push ahead with the approach you described.

**Comment by tomlinton** [comment]
Yea sure, I agree it is preferable

**Comment by wentokay** [comment]
fixed in #1858
