### ISSUE TITLE
more autolock settings

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#1394]
the user should have an option to

lock immediately on extension close (and thus have to type in the password at all times)
never lock (and thus never have to type in the password)

Related https://github.com/coral-xyz/backpack/issues/1393

**Comment by anoushk1234** [comment]
<img width="361" alt="Screenshot 2022-11-08 at 10 29 01 AM" src="https://user-images.githubusercontent.com/32778608/200478935-2c6d6bad-7972-428d-a3aa-d1495d1c73dd.png">
Should i add it in this menu above dark mode?

**Comment by tomlinton** [comment]
<img width="377" alt="Screen Shot 2022-11-09 at 8 11 10 AM" src="https://user-images.githubusercontent.com/489202/200774623-83ccf2a3-b10a-43d8-acbc-c392e159c706.png">

It'd be nice to have it on this screen, might need some design guidance though. cc @trucy @aarongillett

**Comment by anoushk1234** [comment]
yea was going to implement it there but was unsure of the design

**Comment by trucy** [comment]
closing since we're going to update this view

**Comment by trucy** [comment]
oops closed the wrong issue haha

**Comment by wentokay** [comment]
quick heads up of something to be aware of, I'm not sure if this will be avoidable without some trickery that will probably come in a future piece of work

'popping out' backpack triggers a close event internally, so if a user has autolock on close enabled, if they choose to open backpack in the popup window either from the menu or via keyboard shortcut it will launch into the lock screen

**Comment by wentokay** [comment]
hmm although this could probably be avoided by delaying the lock on close by 1 second, so if the user does the popout action, backpack reopens and cancels the lock event that is scheduled. If nothing happens within that second, i.e. the extension is actually closed, then proceed with the autolock.

**Comment by wentokay** [comment]
for reference, this issue (including the figma design) is being worked on here #1858

**Comment by wentokay** [comment]
added in #1858
