### ISSUE TITLE
Add types to ReactXnft components

### ISSUE THREAD

**Issue by hkirat** [coral-xyz/backpack#1397]
Would be super useful to developers to get props like `tw`, `style` as types. Right now there are no docs either so gets very hard to understand what props to use.

**Comment by armaniferrante** [comment]
related https://github.com/coral-xyz/backpack/issues/886

**Comment by anoushk1234** [comment]
Highly needed!

**Comment by anoushk1234** [comment]
have added this for the styles #1409

**Comment by anoushk1234** [comment]
this can be closed now

**Comment by anoushk1234** [comment]
#1426 Full component type support

**Comment by anoushk1234** [comment]
can close this @hkirat

**Comment by hkirat** [comment]
Closed via #1426
