### ISSUE TITLE
Using spread syntax when updating a useState within TextField onChange causes the other properties to revert to what they were before

### ISSUE THREAD

**Issue by jokumusic** [coral-xyz/backpack#1423]
e.g.:
const [testState, setTestState] = useState({a:"0",b:"1"});

<TextField value={testState.a} onChange={e=>setTestState({...testState, a: e.target.value})} />
<TextField value={testState.b} onChange={e=>setTestState({...testState, b: e.target.value})} />

Changing the value on one causes the other to revert to its previous value.

**Comment by hkirat** [comment]
Hi @jokumusic , i'm unable to re-produce this locally 
<img width="374" alt="Screenshot 2022-11-05 at 9 41 57 AM" src="https://user-images.githubusercontent.com/8079861/200100248-d1542373-cc18-48f8-be26-1110889ce93f.png">


```js
import ReactXnft, {AnchorDom, TextField, View} from "react-xnft";
import {useState} from "react";

ReactXnft.render(
  <AnchorDom>
    <App />
  </AnchorDom>
);

function App() {
    const [testState, setTestState] = useState({a:"0",b:"1"});

    return <View>
        <TextField value={testState.a} onChange={e=>setTestState({...testState, a: e.target.value})} />
        <TextField value={testState.b} onChange={e=>setTestState({...testState, b: e.target.value})} />
    </View>
}
```

What's the version of `ReactXnft` you are using?

**Comment by jokumusic** [comment]
Disregard. Updating my packages seems to have resolved the issue.
