### ISSUE TITLE
removing wallet with new name causes black screen

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#1427]
https://user-images.githubusercontent.com/6990215/200116756-c37e2ff8-0236-46e6-9ace-a0872ad13490.mp4

**Comment by Gajesh2007** [comment]
![Screenshot 2022-11-05 at 10 27 27 PM](https://user-images.githubusercontent.com/26431906/200132022-3d427beb-8523-42ff-b3d9-ed0ec260a45a.png)

**Comment by Gajesh2007** [comment]
works on builds before 7 days.

 ![Screenshot 2022-11-05 at 10 43 49 PM](https://user-images.githubusercontent.com/26431906/200132696-c36262db-6818-406b-b937-81f10cbc83f3.png)

**Comment by hkirat** [comment]
Seems like this happens when you delete the currently active walet.
