### ISSUE TITLE
Expose width and height via ReactXnft

### ISSUE THREAD

**Issue by hkirat** [coral-xyz/backpack#1449]
https://discord.com/channels/985994296337498182/1011846320677462137/1040020684832768040

**Comment by anoushk1234** [comment]
> https://discord.com/channels/985994296337498182/1011846320677462137/1040020684832768040

So would we add be adding breakpoints like base, medium, large, xl for diff screen sizes?

**Comment by jokumusic** [comment]
Added PR for this: https://github.com/coral-xyz/backpack/pull/1453

**Comment by hkirat** [comment]
Closed via https://github.com/coral-xyz/backpack/pull/1453
