### ISSUE TITLE
When using stack navigators, the developers need to specify `height: 100%` else the body doesn't show

### ISSUE THREAD

**Issue by hkirat** [coral-xyz/backpack#1465]
https://discord.com/channels/985994296337498182/1004775994193875064/1040756660265824306

**Comment by hkirat** [comment]
Looking at the code, there's probably no soln to this on our side, we just need to communicate this better in the docs

**Comment by jim4067** [comment]
We also encountered a similar issue. Maybe adding an **NB** or a **Note** would be appropriate.

Where are the docs housed? I can't seem to find them.
