### ISSUE TITLE
Direct link users to blockchain settings on Apps tab when it's disabled

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#1499]
<img width="371" alt="Screenshot 2022-11-14 at 2 36 27 PM" src="https://user-images.githubusercontent.com/321395/201816064-a34e6b8f-981b-4175-ae54-b1bd0ee0b7e0.png">

Can we link directly to the Solana Blockchain settings from a button on this empty state/info message?

**Comment by tomlinton** [comment]
Duplicate https://github.com/coral-xyz/backpack/issues/1377
