### ISSUE TITLE
SPL tokens not showing balances correctly

### ISSUE THREAD

**Issue by nickFNY** [coral-xyz/backpack#1515]
Tokens besides SOL are not showing correct balances. If send token to wallet or swap to a token, balances are not reflected on the wallet even after waiting. The explorer shows correct balances however. 
<img width="353" alt="Screen Shot 2022-11-16 at 11 14 09 AM" src="https://user-images.githubusercontent.com/63250024/202248235-c3981e71-fcc0-4bf8-b0db-e307ed11db74.png">
<img width="973" alt="Screen Shot 2022-11-16 at 11 14 28 AM" src="https://user-images.githubusercontent.com/63250024/202248243-a164e4aa-f8ea-4f33-ba4e-28475ab4cef1.png">

**Comment by tomlinton** [comment]
@hkirat It never becomes correct? This is expected to a point, but it should resolve when the next token polling update hits.

**Comment by hkirat** [comment]
Been a while and I don't see it yet (sent USDC to my wallet)
<img width="385" alt="Screenshot 2022-11-17 at 12 05 47 AM" src="https://user-images.githubusercontent.com/8079861/202264766-e931ff38-9621-4882-ac6f-120d2a8d1bc5.png">


This is the transaction that sent the USDC - https://explorer.solana.com/tx/4zKTNVPDDBK2LNSH42WXYpZ7LhEjpCotdCDryMoph9s4DbjLbrPUnBQHk4Gs2VW8pGHEjvs6ewNM3sqj4wLMMCZ2?cluster=devnet
Been ~30 mins. What is the token polling interval?

**Comment by tomlinton** [comment]
10s, so not that. I can't reproduce on master but interestingly I see yours is devnet. I was testing mainnet so maybe that is the difference.

**Comment by nickFNY** [comment]
My balances ended up appearing correct after about 90 mins, on mainnet

**Comment by tomlinton** [comment]
Reasonably sure this was RPC related (I was using a custom RPC server and not the same as others so it makes sense I couldn't reproduce). We've switched RPC providers so it should be resolved.
