### ISSUE TITLE
`render fn not found` when going in and out of degods plugin

### ISSUE THREAD

**Issue by wentokay** [coral-xyz/backpack#154]
to repoduce:

with a wallet not holding degods
click on degods table widget
click back button

https://user-images.githubusercontent.com/101902546/173593376-27921c50-128a-4e1f-8888-6426ba82850f.mov

**Comment by grimAgent** [comment]
Ok, bit more info on the problem, looks like that `_render` function [is expecting to get the instance's `_renderFns`](https://github.com/coral-xyz/backpack/blob/aa170c4b1b869d62a34e74441983e09dfedec0d4/packages/react-xnft-renderer/src/plugin.ts#L989). But that Map is [populated on the `onRender` callback](https://github.com/coral-xyz/backpack/blob/aa170c4b1b869d62a34e74441983e09dfedec0d4/packages/react-xnft-renderer/src/plugin.ts#L798), which seems to be called AFTER `commitUpdate`

This is all happening on the `react-xnft-renderer` package on file `plugin.ts`

I'm not familiar with the whole architecture and what the order of events SHOULD be, but maybe this just saves some debugging time to someone...

**Comment by grimAgent** [comment]
@armaniferrante or @wentokay you might want to change the title of the ticket, since it's not specific to the Degods plugin and just happens with adding a `style` to any element
