### ISSUE TITLE
error in examples/xnft/deadgod

### ISSUE THREAD

**Issue by crypt0miester** [coral-xyz/backpack#1546]
Icon's file is icon in [App.tsx](https://github.com/coral-xyz/backpack/blob/3022ac037cf886b92763c09c4357145da48496be/examples/xnft/deadgods/src/App.tsx#L4)

but in the [utils](https://github.com/coral-xyz/backpack/tree/master/examples/xnft/deadgods/src/utils) folders it is "Icon.tsx"

you might want to rename the file to "icon.tsx"

**Comment by jim4067** [comment]
this should be a fairly quick fix

**Comment by crypt0miester** [comment]
> this should be a fairly quick fix

yup, did not want to make PR for a quick fix.
