### ISSUE TITLE
[Improvement] Private key import

### ISSUE THREAD

**Issue by dr497** [coral-xyz/backpack#1550]
At the moment it is not very clear how one can import an existing wallet to Backpack. It seems that one can only import a base58 encoded private key (correct me if I am wrong). I suspect this might be a bit confusing for most people especially since there is not much explanation/help on the import screen and that the average user is more comfortable using his seed phrase than a private key.

It would be amazing to add the possibility to import existing wallets through:

- Seed phrase
- Private key as a bit-array
- Private key base58 encoded

**Comment by armaniferrante** [comment]
We can easily add those private key imports. Seed phrase would also be great but a lot more work.

**Comment by tomlinton** [comment]
It supports both bit array and base58 encoded, so I think what we are discussing here is the ability to import a singular account using a mnemonic that is not the mnemonic that the user onboarded with (or alternatively supporting multiple mnemonics).

Related https://github.com/coral-xyz/backpack/issues/1464

**Comment by armaniferrante** [comment]
Seed phrases can now be done by creating new accounts. Settings -> top username button -> add account. Still need to do the private key imports.

**Comment by armaniferrante** [comment]
Verified we support private key imports for both bs58 and array formats. So looks like this is done.
