### ISSUE TITLE
react-xnft hooks don't work with react-native

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#1552]
Probably caused by two different versions of react.

**Comment by crypt0miester** [comment]
the versions were locked into to be the same on #1544

**Comment by crypt0miester** [comment]
I also noticed that a react-native `View` does not work with the react-xnft `Tab`

**Comment by hkirat** [comment]
@crypt0miester you can only use one of `react-native` or `react-xnft` for now. Their renderers are both not compatable and wont work together

**Comment by crypt0miester** [comment]
> @crypt0miester you can only use one of `react-native` or `react-xnft` for now. Their renderers are both not compatable and wont work together

sure. thanks.
