### ISSUE TITLE
Re-use `@coral-xyz/zeus` in `workers/auth`

### ISSUE THREAD

**Issue by hkirat** [coral-xyz/backpack#1554]
https://github.com/coral-xyz/backpack/tree/master/backend/native/zeus now exports the `auth` zeus types. Can be re-used in `workers/auth` to avoid code duplication

**Comment by jim4067** [comment]
Hello @hkirat 

would love to look at this

**Comment by wentokay** [comment]
these zeus definitions are based on the auth worker role's scope, do we want to have them in a separate package?

**Comment by hkirat** [comment]
@wentokay yeah I moved the `auth worker` scoped zeus defns to https://github.com/coral-xyz/backpack/blob/master/backend/native/zeus/package.json#L10 because I had to use them in a few other packages.
So it already exists as a module, we can just re-use it

**Comment by hkirat** [comment]
@jim4067 `@coral-xyz/zeus` and you'll have to introduce it to the package.json of the module as well

**Comment by jim4067** [comment]
Also, since @hkirat already moved the definitions, I think it should be safe to delete the `zues` definitions in the worker/auth directory.

**Comment by jim4067** [comment]
Also, since @hkirat already moved the definitions, I think it should be safe to delete the `zues` definitions in the worker/auth directory.
