### ISSUE TITLE
Wallet Locks before set duration time. 

### ISSUE THREAD

**Issue by nickFNY** [coral-xyz/backpack#1587]
User set auto-lock to 2 weeks or 10080 seconds, although the wallet auto-locks after 2 minutes. Confirmed time is saved as 10080 second if close and reopen setting but still locks after 2 minutes. 

discord: https://discord.com/channels/971847939456639047/1027311104973623447/1045751827733426247

**Comment by armaniferrante** [comment]
dup of https://github.com/coral-xyz/backpack/issues/1393
