### ISSUE TITLE
User unable to reopen wallet/recover account after creating with ledger

### ISSUE THREAD

**Issue by nickFNY** [coral-xyz/backpack#1588]
User created account with ledger, after closing and reopening the wallet they are prompted to create new/restore account. then trying to restore account via hardware receives error below. Tried multiples times with same result. 

discord: https://discord.com/channels/985994296337498182/985994296790487112/1045429806734520370

![image123](https://user-images.githubusercontent.com/63250024/204041585-c3ef8169-fae9-485b-8a63-34cbc6e10194.png)

**Comment by nickFNY** [comment]
User suspect account never completed setting up. Says on the last step of setting my ledger up it takes legit 30 minutes of loading and never works

**Comment by armaniferrante** [comment]
Don't think this is an issue anymore. Closing.
