### ISSUE TITLE
Responsive empty states

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#1609]
Current:

![Screenshot 2022-11-22 at 8 46 39 AM](https://user-images.githubusercontent.com/321395/204358217-747e36d9-dc03-4cdc-a9c1-b451b6ea2de4.png)

Option 1:
- use current design for extension, switch to the following on larger viewports:
https://www.figma.com/file/MmzQZ15WygrJ8sf4mj7VYJ/Backpack-Design-System?node-id=205%3A8047&t=xWluFj2fJv9sEKf3-1

<img width="957" alt="Screenshot 2022-11-28 at 12 56 22 PM" src="https://user-images.githubusercontent.com/321395/204358580-95f8b08e-6dee-404e-b4ec-5952459d5338.png">

Option 2:
- remove the background behind the empty state and set the button width to equal the width of the content + 24px L/R padding inside of the button

**Comment by callensm** [comment]
going to do option 2, think it'll look cleaner in the end regardless of the viewport size
