### ISSUE TITLE
remove username from jwt

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#1615]
```
{
  sub: 'd9a23634-1cb9-4993-931c-729746e29035',
  username: 'god',
  iss: 'auth.xnfts.dev',
  aud: 'backpack',
  iat: 1669670538
}
```

**Comment by tomlinton** [comment]
`sub` is the uuid here, do we want to just remove `username` and rename `sub`?

**Comment by armaniferrante** [comment]
I guess `sub` is the standard name for this in jwts? If that's the case I guess not.

**Comment by tomlinton** [comment]
Ahh yea short for `subject`, so we will just remove `username`.
