### ISSUE TITLE
Applications page will not load xNFTs

### ISSUE THREAD

**Issue by nickFNY** [coral-xyz/backpack#1642]
Users application page will not load xNFTs. Pic below. Brave browser. user tried resetting browser and restoring seed phrase to troubleshoot without success. Also waited a couple hours with page open without help. on mainnet 

discord: https://discord.com/channels/985994296337498182/1035923763570675832/1047645890048970772

<img width="373" alt="Screenshot_2022-11-30_at_4 48 38_PM" src="https://user-images.githubusercontent.com/63250024/204942506-b41d4edb-1b8d-486b-8145-a96ed62f61ae.png">

**Comment by armaniferrante** [comment]
Doesn't appear to be a problem anymore.
