### ISSUE TITLE
use UUID from user account creation response

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#1651]
When onboarding is completed, we need to get the UUID and use it in Backpack. Right now, UUIDs are only provided when `BACKPACK_FEATURE_USERNAME` is off [here](https://github.com/coral-xyz/backpack/blob/master/packages/app-extension/src/components/Onboarding/pages/Finish.tsx#L77-L85). When it is on, we need to get the UUID created from the worker and use it.

**Comment by tomlinton** [comment]
Same applies to recovery

**Comment by armaniferrante** [comment]
Closed by https://github.com/coral-xyz/backpack/pull/1669. Need to actually deploy the backend-api to test it out.
