### ISSUE TITLE
stripe integration should use a backpack logo

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#1685]
Right now it's just using this default blue logo.

<img width="398" alt="Screen Shot 2022-12-03 at 8 55 05 AM" src="https://user-images.githubusercontent.com/6990215/205444347-71f9a63a-7e76-4f2c-a330-017fa222edd0.png">

**Comment by armaniferrante** [comment]
Does the merchant name need to be the company name (Coral)? Or can it be the product (Backpack)?

**Comment by hkirat** [comment]
updated the logo, unsure if we can change the name but have asked the stripe folks

**Comment by hkirat** [comment]
Fixed the logo and name to say backpack
<img width="592" alt="Screenshot 2022-12-15 at 2 27 49 PM" src="https://user-images.githubusercontent.com/8079861/207816432-7114a4bb-2cc8-42de-bdc4-a55959218266.png">
