### ISSUE TITLE
Unable to use installed applications 

### ISSUE THREAD

**Issue by GabrielePicco** [coral-xyz/backpack#1696]
# Unable to use installed applications 

I'm unable to use any installed application application. 

Setup:
- RPC devnet
- OS: macOS Ventura 13.0, Chrome 108.0.5359.94. 
- backpack: 0.4.0 installed from the Chrome store
- RPC set on devnet,
- One of the app I tried to install: one of the app I tried to install: https://devnet.xnft.gg/app/9AmGmRkSQYSYAupbdKmr2et8nQkSg5bo8NAG1nmXgY6g , but I get the same error with all the apps

- I can correctly install the applications and I can see tre transaction on the explorer
- After installation, I can't visualise the installed application

<img width="379" alt="Screenshot_2022-12-04_at_19 35 43" src="https://user-images.githubusercontent.com/12031208/205512219-6ea2802c-1042-4f81-baca-d3072abb299d.png">
- If I click on "Open" from the app page, the popup get stuck with a black screen

<img width="379" alt="Screenshot_2022-12-04_at_19 35 43" src="https://user-images.githubusercontent.com/12031208/205512284-c692ece3-0665-45ee-b11f-80775241c35a.png">

- The stack trace of the popup console is:  popup.js:2 TypeError: Cannot read properties of undefined (reading 'toString')

<img width="648" alt="Screenshot_2022-12-04_at_19 38 44" src="https://user-images.githubusercontent.com/12031208/205512377-f5eea9de-d8f0-4186-8023-03301e8261bc.png">

Hope it helps detect the bug.

**Comment by armaniferrante** [comment]
Can you try the edge build from the latest release https://github.com/coral-xyz/backpack/releases/tag/0.2.0-latest-1083

**Comment by GabrielePicco** [comment]
@armaniferrante I just tried, still not working, but I get a slightly different behaviour:
- Popup is blocked on a white screen
- Popup stack track:
 
<img width="644" alt="Screenshot 2022-12-04 at 20 33 14" src="https://user-images.githubusercontent.com/12031208/205514142-77ce439a-baa6-4679-82f5-169e46c1ce37.png">

**Comment by hkirat** [comment]
@GabrielePicco at what stage do you see the white screen? Are you able to create a new wallet?

**Comment by GabrielePicco** [comment]
@hkirat thanks for the fast support. Yes I'm able to create a new wallet. It's when I open the app:

<img width="1726" alt="Screenshot 2022-12-04 at 21 04 06" src="https://user-images.githubusercontent.com/12031208/205515477-1ccbb418-3dba-4421-8b79-cf98c035ce68.png">

**Comment by hkirat** [comment]
are you clicking on `preview`? Or are you installing the xnft?

**Comment by hkirat** [comment]
This is what I see when I open the same xnft 
<img width="1236" alt="Screenshot 2022-12-05 at 2 38 53 AM" src="https://user-images.githubusercontent.com/8079861/205515729-c0cdce94-8966-47ec-a380-ec5033669591.png">

**Comment by GabrielePicco** [comment]
I installed the xnft and then clicking on open.
The other strange thing, not sure is related, is that the applications are not loading:
<img width="377" alt="Screenshot 2022-12-04 at 21 10 49" src="https://user-images.githubusercontent.com/12031208/205515809-d7873a09-02b2-4d60-9c44-1def1c6b528d.png">

**Comment by hkirat** [comment]
What's the Solana RPC URL that u are using? What do you see when you access this endpoint - https://solana-rpc.xnfts.dev/ ?

**Comment by GabrielePicco** [comment]
Devnet (not custom). I see this messsage `Only POST requests are allowed`. Am I somehow blocked?

**Comment by GabrielePicco** [comment]
Closing as solved in the latest edge build. Thanks for the help!
