### ISSUE TITLE
better ledger feedback when signing a transaction

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#1698]
"when using hardware wallet and approving TX, can you please adjust the button to show a loader/spinner, i didnt realize it sent the request to my device, the wallet UI gave me no indication it was waiting."

-- original request [here](https://twitter.com/0xBanana/status/1599476918713479168)

**Comment by armaniferrante** [comment]
Note that this was during a connected app transaction.

**Comment by tomlinton** [comment]
Related (but different as they are transactions from inside Backpack not from a connected app) https://github.com/coral-xyz/backpack/issues/806, https://github.com/coral-xyz/backpack/issues/805, https://github.com/coral-xyz/backpack/issues/897

**Comment by trucy** [comment]
Can we do something [like this](https://www.figma.com/file/HNF2HJZYq6dUzCWxSmH2Oe/Backpack-_-Questlog?node-id=14741%3A64079&t=v0lsQ1a8QzGeYWhw-1)?

**Comment by aarongillett** [comment]
Closing as addressed with [Issue 3469](https://github.com/coral-xyz/backpack/issues/3469)
