### ISSUE TITLE
enforce unique public key constraint

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#1725]
There should be a public key constraint that makes the blockchain/public key composite unique.

There's probably existing non uniques so they'll need to be dealt with.

Blocks https://github.com/coral-xyz/backpack/issues/1716

**Comment by armaniferrante** [comment]
Blocking the release on this as it will be painful to go back and enforce this in the future. The current release only has two dups, both of which are being dealt with.

**Comment by tomlinton** [comment]
This has been added and enforced at the database level. Further work in #1746
