### ISSUE TITLE
inform user when trying to association a pubkey with more than one username

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#1746]
One cannot associate a pubkey with more than one user. We will need educational error states during onboarding, account adding, and wallet adding to educate the user.

**Comment by tomlinton** [comment]
Breaking this out into issues for each case: https://github.com/coral-xyz/backpack/issues/1823 https://github.com/coral-xyz/backpack/issues/1821 https://github.com/coral-xyz/backpack/issues/1819 https://github.com/coral-xyz/backpack/issues/1822
