### ISSUE TITLE
Display transaction simulation when signing transactions

### ISSUE THREAD

**Issue by aarongillett** [coral-xyz/backpack#1753]
We currently don’t have transaction simulations.
At a minimum to avoid rugs, Backpack should display tx instructions when approving.

Example transaction buying an NFT.
![Screenshot 2022-12-06 at 21 42 16](https://user-images.githubusercontent.com/4157473/206316527-1bbd8caa-1e48-4999-b8a2-28ca2d1fa93f.png)

**Comment by aarongillett** [comment]
In addition to transaction simulation, I think it’d be useful and necessary to display a “Show advanced details” button that displays detailed instructions like _Create token account_, _program ID_ etc. This could also be a v1 before transaction simulation.

**Comment by armaniferrante** [comment]
We have this. Closing. Going to create a new issue for developer mode transaction details as @aarongillett suggested.
