### ISSUE TITLE
transaction approve/deny drawer did not pop out while using window.xnft in Iframe

### ISSUE THREAD

**Issue by jack77121** [coral-xyz/backpack#1764]
[condition and environment]
backpack version:
@ commit e815282c9fd89e8149333562a4ff43e50d02ce1a
(w/ developer mode on)

dapp:
locally, at `http://localhost:3000`

launch with iframe:
`npx xnft dev --iframe http://localhost:3000`

using xnft with predefined interface:
```
interface xNFTInterface extends Provider {
  signMessage(message: Uint8Array): Promise<Uint8Array>
  signAllTransactions<T>(transactions: T[]): Promise<T[]>
  signTransaction<T>(transaction: T): Promise<T>
}

declare global {
  interface Window {
    xnft: xNFTInterface
  }
}
```
============================================================
few weeks ago, everything works fine, after pulling and build the latest backpack,
the transaction signing approve/deny drawer did not shows up.

**Comment by hkirat** [comment]
Can you share the code that you're using to sign the transaction?

**Comment by jack77121** [comment]
```
import { useEffect } from 'react'

import { Provider } from '@project-serum/anchor'

import useWallet from '@/application/wallet/useWallet'

interface xNFTInterface extends Provider {
  signMessage(message: Uint8Array): Promise<Uint8Array>
  signAllTransactions<T>(transactions: T[]): Promise<T[]>
  signTransaction<T>(transaction: T): Promise<T>
}

declare global {
  interface Window {
    xnft: xNFTInterface
  }
}

export default function useXNFTWallet() {
  useEffect(() => {
    if (window && window.xnft && window.xnft.publicKey) {
      /* eslint-disable */
      console.log('useXNFTWallet:', window.xnft)
      useWallet.setState({
        signMessage: window.xnft.signMessage,
        signAllTransactions: window.xnft.signAllTransactions,
        owner: window.xnft.publicKey,
        connected: true
      })
    }
  }, [])
}
```
I load them into zustand state when dapp launched, I also using solana wallet adapters, 
and wrapped them into a function tools, when signing, I use:
`signAllTransactions(transactions)`

**Comment by hkirat** [comment]
Do you see an error log by any chance @jack77121

**Comment by jack77121** [comment]
from console:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/5617621/206953963-ad8a467a-0288-49a8-ab45-e193f7859054.png">

**Comment by jack77121** [comment]
Circle back to this project and realize that `window.xnft` has upgraded that has `window.xnft.solana` & `window.xnft.ethereum` for a loooong time.
