### ISSUE TITLE
crashes on logging out usernames

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#1796]
Potentially two separate issues.

First reproduction:

- Recover an account with a single public key on one blockchain (Solana)
- Recover another account with a single public key on a different blockchain (Ethereum)
- Log out the Ethereum wallet

<img width="379" alt="Screenshot 2022-12-12 at 9 12 03 AM" src="https://user-images.githubusercontent.com/489202/206926528-24be6762-7df0-4d62-a1b2-f6623016a9ed.png">

Second reproduction:

- Recover an account with a single public key on one blockchain (Solana)
- Recover an account with a single public key on a different blockchain (Ethereum)
- Recover another account (Ethereum)
- Switch to the Solana account and log it out

<img width="374" alt="Screenshot 2022-12-12 at 9 12 24 AM" src="https://user-images.githubusercontent.com/489202/206926588-c029aca6-ec0b-4e9c-8733-2e9fa3c6601b.png">

The first one looks like its due to the token table for a blockchain rendering when there is no public keys left, and the second one looks like its due to logging out the last active wallet for a blockchain.

**Comment by armaniferrante** [comment]
Maybe related. Something wonky is up with the key-type detection. For example, notice the "show secret phrase" button here. If I load a ledger first, and switch accounts, this doesn't show.

<img width="392" alt="Screen Shot 2022-12-11 at 3 56 41 PM" src="https://user-images.githubusercontent.com/6990215/206928351-836b90e3-2c12-42d5-9ed5-b8c393274e31.png">

**Comment by tomlinton** [comment]
Tracked in #1800
