### ISSUE TITLE
example client broken

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#1835]
Steps to reproduce:

* run `yarn start` in `examples/client/simple`
* click `send lamport to 1 random address`

And the transaction popup doesn't appear.

**Comment by armaniferrante** [comment]
<img width="1551" alt="Screen Shot 2022-12-13 at 1 17 05 PM" src="https://user-images.githubusercontent.com/6990215/207413230-82091667-cbb7-4653-b7f3-fb58ba22977c.png">

**Comment by tomlinton** [comment]
From memory we had the same issue with the RPC proxy prior to the swr-data one being implemented. Here was the fix:

https://github.com/coral-xyz/backpack/pull/1630

Not sure if it is correct in this case.

**Comment by armaniferrante** [comment]
Seems to work now.
