### ISSUE TITLE
app can't connect to locked wallet

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#1853]
- Use the example client
- Select wallet / Backpack while Backpack is locked

<img width="600" alt="Screenshot 2022-12-15 at 9 52 05 AM" src="https://user-images.githubusercontent.com/489202/207711536-ecbe3d48-4f34-4018-ac78-18abe6d7e9bc.png">

Related #1840

**Comment by tomlinton** [comment]
https://discord.com/channels/985994296337498182/1014889986350383144/1051974090304520262

**Comment by armaniferrante** [comment]
On it.

**Comment by armaniferrante** [comment]
Closed by 81d4163ceda66979ac4761c2832571ccb9504f13. Please confirm on your end.
