### ISSUE TITLE
splTokenMint undefined after solana token polling update

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#1854]
https://github.com/coral-xyz/backpack/blob/2b28b27081b77504b31a419f47f8201eefeaf33a/packages/recoil/src/atoms/solana/token.tsx#L201 becomes undefined.

Initial investigation makes me think this is because of the recoil state update in the Solana token polling.

<img width="1050" alt="Screenshot 2022-12-15 at 9 58 24 AM" src="https://user-images.githubusercontent.com/489202/207712824-3a88a759-42f0-4c2e-b19b-76b623ce59e8.png">

Reproduction:

- Use example client
- Use send 1 lamport button
- Wait on the approve screen for the Solana token update to poll

**Comment by armaniferrante** [comment]
Closed by https://github.com/coral-xyz/backpack/pull/1836
