### ISSUE TITLE
JWT doesn't get reset on user switch

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#1857]
Steps to see the issue:

- where user A) is not whitelisted for the WAOlist xNFT, open user A), view collectibles tab, no WAOlist
- where user B) is indeed whitelisted for the WAOlist xNFT, open user B), see collectibles tab, click on WAOlist

The WAOlist will display the incorrect message "open in backpack".

**Comment by tomlinton** [comment]
Should be fixed by https://github.com/coral-xyz/backpack/pull/1944
