### ISSUE TITLE
scrolling style broken

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#1862]
First half of the video is what it should look like. Then the second half is where things get funky and regress to the default scroll. Caused by https://github.com/coral-xyz/backpack/pull/1860. My guess is that it's due to the `<Scrollbar>` component being removed https://github.com/coral-xyz/backpack/commit/98243ecb8ee3558ee7561f07ed7b183b92dbed68#diff-51345119a3dc82fc06d143c66ba37e2a8db8f4c90014ce0c706ed93e69e730a9L176.

https://user-images.githubusercontent.com/6990215/207993922-e58205de-68a0-40c1-a8d3-efaf2651f015.mov

**Comment by armaniferrante** [comment]
Potential hack: Instead of removing that scrollbar component completely, it might be better to put it back and just replace it selectively when you use the virtualized list.

**Comment by tomlinton** [comment]
Related https://github.com/coral-xyz/backpack/issues/818

**Comment by tomlinton** [comment]
Related to the issue (loss of styling), not necessarily the same root cause but worth mentioning as  someone might be able to resolve both with the same fix.

**Comment by armaniferrante** [comment]
Closed by #1864.
