### ISSUE TITLE
Updates to notifications empty state + global empty state fixes

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#1867]
**Current**
<img width="375" alt="Screenshot 2022-12-15 at 10 53 46 AM" src="https://user-images.githubusercontent.com/321395/208134168-725413c4-4d43-4571-a0bc-135936c55dcd.png">

This copy seems too specific if notifications can come from multiple sources

Suggested: make it more generic
Related: can we make (or make sure) all our empty states have sentence case capitalization and punctuation after the descriptions?

**Proposed**
<img width="281" alt="Screenshot 2022-12-16 at 9 48 46 AM" src="https://user-images.githubusercontent.com/321395/208136384-9be94cba-0b89-4678-a49d-5c8b0b6dc2b1.png">

[Figma](https://www.figma.com/file/HNF2HJZYq6dUzCWxSmH2Oe/Backpack-_-Questlog?node-id=15606%3A78028&t=6NbJd9d4rL0Y4YO6-1)

**Comment by jim4067** [comment]
Let me take this

**Comment by jim4067** [comment]
I think @hkirat already worked on this https://github.com/coral-xyz/backpack/commit/e6016cdd1afbd975ce10b4c38252d1ca61d8c48a

**Comment by hkirat** [comment]
Yup good to close
