### ISSUE TITLE
Collectibles page breaks

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#1870]
Steps to reproduce:

* open backpack
* change to nft tab
* change to balances tab
* change back to nft tab

<img width="376" alt="Screen Shot 2022-12-16 at 12 27 03 PM" src="https://user-images.githubusercontent.com/6990215/208154586-2f7fbc07-550f-41a4-a79c-52915e59ed31.png">

**Comment by armaniferrante** [comment]
Probably caused by https://github.com/coral-xyz/backpack/pull/1860

**Comment by armaniferrante** [comment]
closed by https://github.com/coral-xyz/backpack/pull/1877

**Comment by tomlinton** [comment]
Still present on build #1428

**Comment by greenish** [comment]
I used to be able to reproduce this by just changing tabs before #1877 but not able to anymore.. Are there any other steps to cause this?

**Comment by tomlinton** [comment]
It seems to happen when I do anything. Maybe try with multiple blockchains holding NFTs.

https://user-images.githubusercontent.com/489202/208398226-e92c17c9-86fe-44d1-b038-75a0f31961e6.mov

**Comment by armaniferrante** [comment]
Closed by https://github.com/coral-xyz/backpack/pull/1933.
