### ISSUE TITLE
Add empty state for changing pfp

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#1886]
[Figma](https://www.figma.com/file/HNF2HJZYq6dUzCWxSmH2Oe/Backpack-_-Questlog?node-id=15645%3A78298&t=QjhX52nryLrXXMHX-1)

**Comment by armaniferrante** [comment]
![Network](https://user-images.githubusercontent.com/6990215/208216360-b3a42d14-9c5e-4aac-a2e5-afa20902c454.png)

**Comment by armaniferrante** [comment]
Closed by 33b1fd69ebf29096b04e2e682b1c59e0739c36cd.
