### ISSUE TITLE
pfp select screen periodically jumps to top

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#1888]
Open the PFP selection screen. Scroll down (you need enough NFTs in the wallet to make it scrollable). It'll jump back to the top after some time. This likely happens when the token polling update hits and the recoil state is updated.

**Comment by armaniferrante** [comment]
I suspect this will be addressed by the work @greenish is doing to improve NFT load perf.

**Comment by armaniferrante** [comment]
Closed by https://github.com/coral-xyz/backpack/pull/1933.
