### ISSUE TITLE
pfp loading from two different urls 

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#1890]
E.g. in contact search list it loads:

https://d1a7965zcx2lcc.cloudfront.net/cdn-cgi/image/fit=contain,width=400,height=400,quality=85/https:/avatars.xnfts.dev/v1/armani

But in the account settings it loads from:

https://d1a7965zcx2lcc.cloudfront.net/cdn-cgi/image/fit=contain,width=400,height=400,quality=85/https:/swr.xnfts.dev/avatars/armani

**Comment by armaniferrante** [comment]
For me, the contacts list also shows an old out of date image.
