### ISSUE TITLE
useAvatarUrl hook is not user specific

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#1906]
Once you update an avatar the newAvatar atom is set in recoil, and that sets it for all accounts because if it exists it is used instead of querying based on username.

https://github.com/coral-xyz/backpack/blob/d12f6c73a91cd0a314d7bec549be3d98b1148e63/packages/recoil/src/hooks/avatar.tsx#L11

<img width="376" alt="Screenshot 2022-12-18 at 4 37 14 PM" src="https://user-images.githubusercontent.com/489202/208280164-a82ad184-6129-49fc-9710-18e596c3f915.png">

**Comment by armaniferrante** [comment]
@greenish any ideas on this one?

**Comment by armaniferrante** [comment]
Closed by https://github.com/coral-xyz/backpack/pull/1927.
