### ISSUE TITLE
Extension context invalidated error throwing after service worker refresh

### ISSUE THREAD

**Issue by hkirat** [coral-xyz/backpack#1914]
Steps to reproduce - 
1. Refresh service worker
2. Try connecting wallet to `magiceden.io`
3. The following error is thrown

<img width="1564" alt="Screenshot 2022-12-19 at 4 27 30 PM" src="https://user-images.githubusercontent.com/8079861/208410881-4128e1f4-3e3b-4b9a-915f-16e7245e3e0f.png">

The error might be silent in the prod wallet, but maybe people dont refresh the `sw` in the prod wallet?

**Comment by armaniferrante** [comment]
Looks like this is somewhat expected. When you reload the extension, the injected content script in magiceden (or any other website) loses its connection to the extension, causing the error, and so the website needs to be refreshed. One idea [here](https://stackoverflow.com/questions/53939205/how-to-avoid-extension-context-invalidated-errors-when-messaging-after-an-exte) is to add a listener that re-injects the content script whenever the extension is installed.

**Comment by hkirat** [comment]
So it doesn't go away even when the website is refreshed. It is consistently reproducible after refreshing. 
The only way to get rid of it is removing the extension and adding it back
