### ISSUE TITLE
nfts in collections are not displayed

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#1949]
No console errors, no outgoing requests happening. Confirmed that when there is only a single NFT (i.e. clicking links you straight through to the actual NFT rather than the display of multiple NFTs) it works fine.

https://user-images.githubusercontent.com/489202/209033237-522412d7-30d4-4264-939a-42dd398b7214.mov

**Comment by armaniferrante** [comment]
Caused by 3aa214eebce3638ceffd1accfee1962d9a00b0b8.

**Comment by tomlinton** [comment]
Closed by #1957
