### ISSUE TITLE
Add formatting to large numbers to increase legibility (like BONK)

### ISSUE THREAD

**Issue by aarongillett** [coral-xyz/backpack#1969]
Large numbers should be formatted with commas e.g. `000,000,000.00`

Locations that need formatting:
- Balances: table views
- Balances/Token (e.g. Solana/BONK)
- Swap
- Send

Locations that may need formatting (balance not high enough to test)
- Main balances USD amount

<img width="372" alt="image" src="https://user-images.githubusercontent.com/4157473/210010462-449ff274-d2d0-4a39-8e3f-03621b826e13.png">
<img width="374" alt="image" src="https://user-images.githubusercontent.com/4157473/210010495-8a4b6ce1-11cb-4a2f-85ae-f77fc9f235c9.png">
<img width="373" alt="image" src="https://user-images.githubusercontent.com/4157473/210013536-434eace3-fc35-454c-b6e4-6b81d5a4acec.png">
<img width="373" alt="image" src="https://user-images.githubusercontent.com/4157473/210013597-679a9b6c-5a23-458e-b11d-925d580e94e3.png">

**Comment by tomlinton** [comment]
Got this done in most places, but not in input fields. Not sure if that is something we wanted, but I prefer only having numbers in input fields.
