### ISSUE TITLE
Incorrect font-size for negative % change value in table view.

### ISSUE THREAD

**Issue by aarongillett** [coral-xyz/backpack#1972]
font-size should be 14px to match the green positive % font-size.

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/4157473/210074897-ac5a8cd1-9fc6-482f-aaf0-9bc2e92cea70.png">

**Comment by Damkols** [comment]
Hello, can I be assigned to this issue?

**Comment by aarongillett** [comment]
Go for it @Damkols!
