### ISSUE TITLE
Create wallet confirmation drawer doesn't show

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#1992]
Steps to reproduce:

- open balances page
- click wallet selector button
- go to settings
- click add wallet 
- click create new wallet 

A confirmation drawer showing success should display

**Comment by tomlinton** [comment]
This does not happen when opened from the settings menu. I assume it's because the active wallet gets updated and the wallet drawer is rendered in the balances table head which is rerendered on an active wallet change.
