### ISSUE TITLE
token balances changing order on polling updates

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#2023]
Tokens with 0 USD value are reordering on each polling update. I assume this is because the order is by USD value, we need to have a secondary ordering on alphabetical.

<img width="370" alt="Screenshot 2023-01-08 at 3 39 19 PM" src="https://user-images.githubusercontent.com/489202/211224720-368ef36e-d5e9-4024-ac17-6c003cc5dc27.png">

**Comment by tomlinton** [comment]
Also probably makes sense to add a $ in front of the 0. Or remove the number altogether because the value is unknown.

**Comment by armaniferrante** [comment]
I'm a little surprised this is happening because we now don't update the UI or recoil atom every time the poll occurs, because we do an equality check on the data. https://github.com/coral-xyz/backpack/blob/master/packages/background/src/backend/solana-connection.ts#L235-L237

**Comment by tomlinton** [comment]
Out of date branch 👍
