### ISSUE TITLE
Add "About Backpack" page, with the Discord link

### ISSUE THREAD

**Issue by monk-doesnt** [coral-xyz/backpack#2050]
![Screenshot 2023-01-10 at 12 53 04 PM](https://user-images.githubusercontent.com/104650166/211637143-4c2bc027-6571-430b-a655-629dcd4c3647.png)

**Comment by yerinle** [comment]
There is already a "Need help? Hop into Discord"
<img width="371" alt="image" src="https://user-images.githubusercontent.com/499891/211878599-1ea0284c-9555-44ee-bc53-be51e1ac8c26.png">

**Comment by trucy** [comment]
Updated design [here](https://www.figma.com/file/HNF2HJZYq6dUzCWxSmH2Oe/Backpack-_-Questlog?node-id=16432%3A100374&t=5QoAxnYI5hEfkwgs-1)

Screenshot for those w/o Figma access

<img width="340" alt="Screenshot 2023-01-11 at 7 10 45 PM" src="https://user-images.githubusercontent.com/321395/211952124-5e8c29fd-350a-47a4-9cc4-5acb94a2d390.png">

Once this is done, we also need to remove the version list item from Preferences (the one that has a hover state but isn’t clickable)

**Comment by jim4067** [comment]
@trucy is this done and is anyone working on it from the dev team?

**Comment by jim4067** [comment]
@armaniferrante, Should I make similar changes to the `app-mobile` package?

![image](https://user-images.githubusercontent.com/30603522/212774945-cdbc1c97-b047-4585-898f-04d17a0d21a3.png)

**Comment by armaniferrante** [comment]
Let's hold off on mobile for now.
