### ISSUE TITLE
Requesting a contact shows myself as being the contact that is being requested, it should show the other user's name instead. 

### ISSUE THREAD

**Issue by monk-doesnt** [coral-xyz/backpack#2064]
![Screenshot 2023-01-11 at 5 06 07 PM](https://user-images.githubusercontent.com/104650166/211937280-c116d23f-a02e-4090-9657-1c9c59023056.png)

**Comment by monk-doesnt** [comment]
Send to prompt at the bottom of the window is also flipped. ![Screenshot 2023-01-11 at 5 23 25 PM](https://user-images.githubusercontent.com/104650166/211939398-d1571143-7a2e-46d4-a6e7-eac452317f97.png)

**Comment by hkirat** [comment]
This is fixed
