### ISSUE TITLE
UI polish on messages

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#2067]
Two things

* time layout is messed up on the right

<img width="487" alt="Screen Shot 2023-01-11 at 7 21 14 PM" src="https://user-images.githubusercontent.com/6990215/211953297-c19d0310-1282-4d6f-a769-8921f144e706.png">

![image](https://user-images.githubusercontent.com/6990215/211954340-140f37a4-6466-4fe0-86f5-c67e676dccda.png)

![image](https://user-images.githubusercontent.com/6990215/211954364-f5ad7ede-a2d6-4145-9353-a50e951dd79e.png)

**Comment by jim4067** [comment]
Hello @armaniferrante, anyway I could locally reproduce this?

Could you send me a long message @b75e1f8 so I can try playing with the margin and padding values?

**Comment by armaniferrante** [comment]
Appears fixed.
