### ISSUE TITLE
Current Backpack license isn't open source

### ISSUE THREAD

**Issue by mikemaccana** [coral-xyz/backpack#2079]
Heya! Just a heads up I work on a different Solana wallet, but I like Backpack and love/respect you all. Looking forward to seeing some exciting xNFT projects in future.

Was chatting with Mert last week about priority fees and he mentioned to look at the Backpack source code. I've seen a few people mention Backpack is open source, but the license at https://github.com/coral-xyz/backpack/blob/master/LICENSE isn't an open source license,

That license includes:

> You are granted a non-exclusive, non-transferable, non-sublicensable license to distribute, publish, copy, modify, merge, combine with another program or create derivative works of the Program (such resulting program, collectively, the “Resulting Program”) solely for Non-Commercial Use

Which conflicts with part 6 of the [Open Source definition - the rules that define what Open Source is](https://opensource.org/osd). 

Likewise Backpack wouldn't quality for Free Software either - [to be free software, the license needs to meet the free software definition](https://www.gnu.org/philosophy/free-sw.html), Backpack's license doesn't meet the 'Use' freedom

Compare this with well known open source projects:

 - [Sollet is Apache 2 licensed](https://github.com/project-serum/spl-token-wallet/blob/master/LICENSE), Apache 2 meets the open source definition. 
 - [node is MIT licensed](https://github.com/nodejs/node/blob/main/LICENSE), MIT is open source because it meets the open source definition
 - [The Linux kernel is GPL 2 licensed](https://en.wikipedia.org/wiki/Linux_kernel), GPL 2 meets the open source definition
 - [Rust is Apache 2 / MIT licensed](https://github.com/rust-lang/rust/blob/master/LICENSE-MIT), Apache 2 and MIT meets the open source definition. 

While people can view Backpack's source code in github, the source code doesn't currently have an open source license.

The main concern is that people might be working on Solana commercially (whether their code is open source or not) and believe they can read and use Backpack source code when the current license says they cannot. 

I fully believe this to be an innocent mistake and Coral can easily fix it depending on how and what they want to do:

 - Pick an [existing open source license](https://opensource.org/licenses/alphabetical). We're about to use MIT for own open source contributions which is popular for people that want to allow anyone to use their code. If you want to ensure that there aren't non-open-source forks on backpack, Coral could pick GPL2 or something more restrictive.
  
 - Keep the existing license but avoid describing Backpack as open source.

 - Create a new license that meets the open source definition (this is a hassle as well known open source licenses have been reviewed by lawyers).

Totally up to Coral to determine what Coral thinks is best. It's your code. My team doesn't have an interest in backpack source, in my case I found other documentation on priority fees, and we don't have much demand to implement things like xNFTs. I've just been working on open source for a few decades and thought you may appreciate the heads up.

Hope that was useful and good luck!

**Comment by armaniferrante** [comment]
Backpack is source available. This is not a mistake. We will consider relicensing once we can prove that we can operate as a going concern as a sustainable business. This is not guaranteed, in any respect. Our first goal is to stay alive and continuing to work on the project. Second goal is trust minimization, i.e., don't trust the code just read it. And then only after that I think it would be reasonable to revisit this conversation. But the team doesn't work for free and so we must prioritize accordingly.

**Comment by mikemaccana** [comment]
Understood re: open source licensing not being guaranteed. We don't open source everything either. My concern in raising this is that I've seen at least one tweet describing Backpack as open source https://twitter.com/viksit/status/1613051995581190144, and based on your account liking the tweet, thought you may not be aware that the current license doesn't qualify. As long as everyone's clear that the current license is source available, rather than open source, we'll avoid potential headaches.

**Comment by mikemaccana** [comment]
BTW regarding reading the code - a non-commercial license prevents people that work in Solana, or in information security, or any other professional involving crypto, from reading the code. People don't know what's in the Backpack source before they read it, and don't know whether they'll work on something that potentially competes with Coral in the future, which would  violate the current license.

**Comment by mikemaccana** [comment]
Thanks for fixing this.

https://x.com/xnft_backpack/status/1739228016797192655
