### ISSUE TITLE
lock screen pfp does not show skeleton loader when extension opened from toolbar

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#2102]
Comparing opening extension in tab vs via toolbar, note the grey skeleton component is never displayed in toolbar:

https://user-images.githubusercontent.com/489202/212580998-18d65ccb-c814-49fd-aa22-1185a59ac5db.mov

**Comment by armaniferrante** [comment]
Related https://github.com/coral-xyz/backpack/issues/1591

**Comment by tomlinton** [comment]
Possibly a more general loading problem and not specific to the PFP

**Comment by tomlinton** [comment]
Closed by #2160
