### ISSUE TITLE
clicking reply should auto focus the messaging input field

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#2105]

**Comment by AFZL210** [comment]
Yes, it does focus on the input box only for the first message sent by the user and not for follow-up messages by the same user.

https://user-images.githubusercontent.com/79896602/224538811-0b7ef7a9-7529-41cc-a43a-f7f331ab1ccc.mp4



Expected :
There are four places that handle the **Reply button** but only one of them targets the input box and focuses on it.


https://user-images.githubusercontent.com/79896602/224539255-d2eba6ee-2589-471a-a9bb-497acdbf128a.mp4
