### ISSUE TITLE
No message to sign when attempting to add a Solana Ledger account

### ISSUE THREAD

**Issue by aarongillett** [coral-xyz/backpack#2119]
Beta 1999
Ledger Nano X

I’ve attempted to add a Solana Ledger account to an existing account @aaron but am not seeing any message to sign after selecting a derivation path address. Ethereum worked.

- Add a wallet
- Continue as @aaron
- Select Solana blockchain
- Add or connect a wallet: selects _Import from hardware wallet_
- Connect to Ledger
- Open Solana app
- Select derivation path and account
- I’m then prompted to _sign the message_ (screenshot), but there’s no message or state change on Ledger Nano X.

<img width="496" alt="Screenshot 2023-01-17 at 17 37 49" src="https://user-images.githubusercontent.com/4157473/212959706-931d20fa-4563-47f2-96d6-735a17f13f7d.png">

**Comment by tomlinton** [comment]
Did you do Ethereum and then tried to do Solana in the same onboarding? If so this is https://github.com/coral-xyz/backpack/issues/1294

**Comment by aarongillett** [comment]
I just tried this again with a brand new Ledger Nano S using build-beta-2104 and ran into the same problem. I did not select Ethereum, only Solana. This time I was starting with a brand new username and selecting 
- I already have a wallet
- I have a hardware wallet
- Select a chain / Solana
- Connect a hardware wallet / next
- Searching for wallet / found
- Open the Solana app (open) / next
- Import account (check first account) Import account
- Sign the message (same screenshot)
Solana Ledger app continues to display “Application is ready”

**Comment by tomlinton** [comment]
Could you check if blind signing is enabled on the ledger?
