### ISSUE TITLE
Ethereum Ledger account not visible in Backpack after importing

### ISSUE THREAD

**Issue by aarongillett** [coral-xyz/backpack#2120]
Beta 1999
Ledger Nano X

I successfully completed the _import from hardware wallet / ETH_ flow, signed the tx on Ledger etc. but the ETH wallet is not displaying in Backpack.

**Comment by tomlinton** [comment]
What was displaying (it sounds like the onboarding completed)?

**Comment by mark-EthDev** [comment]
@aarongillett Talk to Ledgerwallet Support on the [Live support chat](https://explore-ledger.online/) so that your issue can be looked into.

**Comment by aarongillett** [comment]
Yeah, it seemed like the onboarding completed. I got the success message in Backpack. But the new wallet isn’t displaying in Backpack.

**Comment by tomlinton** [comment]
But there must be some wallet displaying in Backpack? If not the one you expected it to be, which one is it?

**Comment by aarongillett** [comment]
For clarity: I already had one SOL wallet and one ETH wallet. I then completed the _Add / Import from hardware wallet_ flow, but no new wallets were added.

**Comment by aarongillett** [comment]
I can test again today with a shiny new Ledger Nano S Plus.

**Comment by tomlinton** [comment]
Worked fine for me so will close, let me know if it doesn't work though. Note that if you have aggregate mode off you need to manually switch to the Ethereum wallet with the drawer.
