### ISSUE TITLE
Message and group chat polish

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#2121]
[Figma](https://www.figma.com/file/HNF2HJZYq6dUzCWxSmH2Oe/Backpack-_-Questlog?node-id=17399%3A139288&t=nMHFpjs7rpjKvYMG-1)

Messages (global)
- add pop window option to top right menu
- reduce bottom padding on each message from 25 to 20
- reduce pfp size from 40 to 32
- increase/add padding below username to 8px (before the top of a gif or message)
- reduce opacity of timestamps from 1 to 0.5
- increase font size of emojis (to be visually the balanced relative to text) from 14 to 18px. maybe this doesn't make sense to do if the emoji is in the middle of a string where the surrounding text is a different size
- ~~can we add a slight overlay with gradient fill to fade the content towards the top?
background: linear-gradient(180deg, rgba(255, 255, 255, 0.5) 0%, rgba(255, 255, 255, 0) 50.1%);~~
- add background gradients to fade towards top (under the text this time though)
- light mode: background: linear-gradient(360deg, #FFFFFF 0%, #F8F8F9 100%), #FFFFFF;
- dark mode: background: linear-gradient(180deg, rgba(255, 255, 255, 0.04) 0%, rgba(0, 0, 0, 0) 100%), #18181B;

Replies
- reduce contrast of “replying to” text color
- reduce font weight of text you're replying to from semi-bold (700) to regular (400)
- reduce line height of text you're replying to from 1.5 to 1.4
- change “Your message” placeholder to “Reply”
- ~~update close icon~~ will make a new ticket for changing icons
- ~~add L/R and top padding to reply input~~ done

~~Group chat~~
- ~~change verified icon~~ will make a new ticket for changing icons
- ~~change backpack top nav background to white~~ done
- ~~change verified icon color from blue to #212938~~ done

**Comment by trucy** [comment]
@peterpme i would file a new ticket for this with steps to reproduce if it's still an issue in the latest build (ie what screen are you clicking tristan's username from)

**Comment by hkirat** [comment]
cc @callensm

**Comment by callensm** [comment]
@trucy are all of the uncrossed out items in the original post still pending completion?

**Comment by trucy** [comment]
@callensm I just went through everything and crossed out the items you can ignore so it should be up to date now

**Comment by callensm** [comment]
@trucy can you update the figma link for this ticket please
