### ISSUE TITLE
Add back wallet selector to top of change pfp empty state

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#2159]
If a user has no NFTs in their active wallet they see this when trying to edit their pfp

<img width="376" alt="Screenshot 2023-01-19 at 2 17 08 PM" src="https://user-images.githubusercontent.com/321395/213552226-e0a306aa-f6f3-4c2a-82d1-25173164e5be.png">

We need to add back the wallet selector to the top so the user can switch between

Otherwise, if someone starts in a wallet with NFTs, switches to one without, they'll get stuck here

<img width="419" alt="Screenshot 2023-01-19 at 2 26 09 PM" src="https://user-images.githubusercontent.com/321395/213552569-f2dc4cc2-53ad-49ea-b00d-bb2f73e67ce6.png">

**Comment by armaniferrante** [comment]
I'll take this.

**Comment by armaniferrante** [comment]
Closed by 8438ae7087912aeab84f571001a34075e2a4ed94
