### ISSUE TITLE
cant recover private key based server side wallet if keyring does not exist

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#2164]
Follow up for https://github.com/coral-xyz/backpack/pull/2146

- Setup Backpack with a mnemonic based account and enable Solana and Ethereum
- Add private key import to Ethereum
- Delete the mnemonic based wallet from Ethereum
- Reset Backpack and go through the recovery flow
- The Ethereum private key import will exist as a dehydrated wallet that needs to be recovered, but it is not possible to recover it because keyrings can't be instantiated with only a private key

Options:

- Prevent wallet removal so it is not possible to end up with only a private key based wallet for a blockchain
- Refactor keyring to allow setup with only a private key

**Comment by aarongillett** [comment]
Testing wallet recovery today and I was unable to recover an Ethereum wallet (didn’t try Solana). Same issue?

0x168C6023317eB4d12d0212f734dE693FF113d2C2

<img width="480" alt="image" src="https://user-images.githubusercontent.com/4157473/216670789-66cdfeaa-c93a-47c5-b339-64eebcb6fcf0.png">
