### ISSUE TITLE
Add set NFT as PFP toggle to NFT view

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#2169]
Allow users to set an NFT as their PFP from the NFT view (currently only something you can do from settings)

<img width="934" alt="Screenshot 2023-01-20 at 11 44 47 AM" src="https://user-images.githubusercontent.com/321395/213770938-9c82c262-5e32-4987-9a5d-e19353a4f0f9.png">

[Figma](https://www.figma.com/file/HNF2HJZYq6dUzCWxSmH2Oe/Backpack-_-Questlog?node-id=16867%3A115311&t=77rDpQcEDWSFqxwQ-1)

We can reuse the toasts from messaging, although all the toast backgrounds should be white

**Comment by armaniferrante** [comment]
Proposal: this might be better served in the more info menu?

**Comment by trucy** [comment]
Related: https://github.com/coral-xyz/backpack/issues/2306 should change this dropdown too
