### ISSUE TITLE
Unable to import from hardware wallet (Solana + Ethereum)

### ISSUE THREAD

**Issue by aarongillett** [coral-xyz/backpack#2174]
Fresh Ledger Nano S Plus
Beta Build 2104
No Ledger accounts have been imported
Both Solana and Ethereum chains are enabled in Backpack

### Solana: the loader hangs on the Import account screen after doing the following:

- Ledger is connected, unlocked, no app is open.
- In Backpack: Add wallet (Selects `+`)
- Your new wallet will be associated with @aaron (selects `continue as @aaron`)
- Blockchains (selects `Solana`)
- Add or connect a wallet (selects `Import from hardware wallet`)
- Connect a hardware wallet (selects `next`)
- Selects Ledger Nano S Plus
- Open the Solana app (opens app, selects `Next`)
- Import account + derivation path selector + loader (screenshot)

<img width="502" alt="image" src="https://user-images.githubusercontent.com/4157473/213788134-4a5ba395-2147-4f80-8484-a8ddf3bc997b.png">

### Ethereum

- Same process as above, except on the Import account screen, the Ethereum Ledger app closes and returns to the main app selector screen.

**Comment by aarongillett** [comment]
Seemed to be the multiple windows issue.
Is this something that is being fixed @tomlinton ? Or should we add some helper text when connecting? Something like “Make sure this is the only Backpack window open”

**Comment by davilaaDEV** [comment]
have you solved your isssue?

**Comment by aarongillett** [comment]
Seemed to be the multiple wallet issue. Is this something that will be fixed @tomlinton ? If not, let me know and I can edit copy.

**Comment by aarongillett** [comment]
Note: blind transaction signing needed to be enabled on Ledger. Unsure if this is also something that is being addressed, but we shouldn’t require users to do this.

**Comment by aarongillett** [comment]
Was able to add an Ethereum wallet with blind transactions disabled. Have not tried with Solana, but am assuming it was a recent build that fixed this.
