### ISSUE TITLE
messaging: click to see full size image attachment

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#2177]
right now you can only see images inline in messages

**Comment by trucy** [comment]
mvp designs for this are [here](https://www.figma.com/file/HNF2HJZYq6dUzCWxSmH2Oe/Backpack-_-Questlog?node-id=16970%3A117457&t=et6S7XCLa8zTjux6-1)

**Comment by harishlalwani** [comment]
@armaniferrante @trucy - Shall I take this issue?

**Comment by armaniferrante** [comment]
@harishlalwani let us know if you started on this already. If not going to bring in @callensm for this.

**Comment by harishlalwani** [comment]
@armaniferrante - no i haven't started on this yet.
