### ISSUE TITLE
Aury token not being recognized by the wallet 

### ISSUE THREAD

**Issue by KougaDaodalus** [coral-xyz/backpack#2178]
![image](https://user-images.githubusercontent.com/123257304/213875406-efc70157-f978-48b1-a58a-2b12e19e9879.png)
![image](https://user-images.githubusercontent.com/123257304/213875415-ced00907-ad5f-405e-a480-8e584ed1a4fe.png)

The token is not being recognized and can't stake them

**Comment by armaniferrante** [comment]
This should be fixed on the latest (not on chrome store yet).
