### ISSUE TITLE
All the tokens of one wallet shows on other wallets as well while trying to swap.

### ISSUE THREAD

**Issue by lokgubhaju** [coral-xyz/backpack#2195]
When i select my Ledger wallet and trying to swap within a backpack wallet then i can see tokens in my Ledger in Backpack wallet and on Ethereum wallet as well.

https://user-images.githubusercontent.com/20090994/213949159-93e3a623-4878-4e10-93cc-969e3ad9faed.mov

**Comment by armaniferrante** [comment]
Please disable aggregate wallet mode. That feature is still a work in progress. Closing.

**Comment by armaniferrante** [comment]
Related: https://github.com/coral-xyz/backpack/issues/1985
