### ISSUE TITLE
Change "user" to "account"

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#2233]
Change "user" to "account" on this screen:

<img width="376" alt="Screenshot 2023-01-25 at 9 51 47 AM" src="https://user-images.githubusercontent.com/321395/214610387-80741388-b9c7-4c18-a934-9f3dcedc435d.png">

We're using already "account" consistently everywhere else, so we should continue

<img width="449" alt="Screenshot 2023-01-25 at 9 53 07 AM" src="https://user-images.githubusercontent.com/321395/214610761-f769a69e-7951-47f8-a553-fc0c38f036f7.png">
<img width="251" alt="Screenshot 2023-01-25 at 9 53 00 AM" src="https://user-images.githubusercontent.com/321395/214610767-464a129c-5967-4953-a361-6eeb22cb23ac.png">
<img width="379" alt="Screenshot 2023-01-25 at 9 54 13 AM" src="https://user-images.githubusercontent.com/321395/214611052-83007a33-08ea-4c24-8079-b967ea11e2bf.png">
<img width="370" alt="Screenshot 2023-01-25 at 9 54 04 AM" src="https://user-images.githubusercontent.com/321395/214611056-e57952be-6207-47c4-aaac-1e3b4943b53e.png">

**Comment by michel-98** [comment]
I would like to take this

**Comment by tomlinton** [comment]
Thanks!
