### ISSUE TITLE
Update full screen messages background and padding

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#2237]
[Figma](https://www.figma.com/file/HNF2HJZYq6dUzCWxSmH2Oe/Backpack-_-Questlog?node-id=17056%3A123169&t=qnw5AlblRhHSHZ8F-1)

Screenshot for those who don't have access:

![Screenshot 2023-01-25 at 11 35 50 AM](https://user-images.githubusercontent.com/321395/214639417-c46c7a92-491e-4506-9326-ee42a98f5ca4.png)

**Comment by harishlalwani** [comment]
@trucy - i would like to take this issue. Is there any invite code for contributing?

**Comment by hkirat** [comment]
Hi @harishlalwani , you can use 6f5c39ca-0c4e-4677-af4d-a0354303b6a3

**Comment by trucy** [comment]
Related: https://github.com/coral-xyz/backpack/issues/2261 (for the new input)
