### ISSUE TITLE
distinct mnemonic icon in wallet list

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#2249]
First is from mnemonic, second two are imports. There should be a distinct icon.

<img width="373" alt="Screenshot 2023-01-26 at 11 27 04 AM" src="https://user-images.githubusercontent.com/489202/214705997-faae520b-5bdb-4e95-b37b-fd38672563e4.png">

**Comment by Mayuresh0072** [comment]
@tomlinton @steveluscher Hello, I want to work on this issue and contribute.. Please assign me this issue. Thanks

**Comment by tomlinton** [comment]
Closed by https://github.com/coral-xyz/backpack/pull/2580
