### ISSUE TITLE
Deploy Programmable NFTs into backpack

### ISSUE THREAD

**Issue by freddyal0x01** [coral-xyz/backpack#2255]
Deets & info so it doesn't get lost on Twitter. 

2 things need to be done: 

1. Check if the NFT being transferred is a pNFT. You can see how we do this for cardinal nfts here: https://github.com/coral-xyz/backpack/blob/da84ca62dfcfe6bfa3cfb7bdb491351fdad140c0/packages/app-mobile/src/components/BottomDrawerSolanaConfirmation.tsx#L63-L66

2. If it is a metaplex pNFT, invoke a metaplex specific transfer function. Again, see how we do this for cardinal here: https://github.com/coral-xyz/backpack/blob/da84ca62dfcfe6bfa3cfb7bdb491351fdad140c0/packages/common/src/solana/index.ts#L357

**Comment by jim4067** [comment]
I'd like to work on this

**Comment by armaniferrante** [comment]
This is done!
