### ISSUE TITLE
Add jump to latest messages button

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#2275]
[Figma](https://www.figma.com/file/NuXRbSjtCQ7IRXlWBqkxpz/Backpack-Design-(Public)?node-id=339%3A4768&t=ojgF3gMaa8ZUyLqf-1)

If a user has scrolled backwards / upwards in the chat at least 100% of the vh (since the extension can be popped), show a button that allows them to click and auto scrolls to the newest messages.

**Comment by kennisjoseph** [comment]
On it!
