### ISSUE TITLE
Remove extra @ behind gm

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#2295]
Remove the @ from this screen in onboarding (when creating a new account, after you enter a new username and hit continue)

<img width="418" alt="Screenshot 2023-01-27 at 3 21 28 PM" src="https://user-images.githubusercontent.com/321395/215203406-c4880ee4-5830-4f77-a8fe-a3a18a41fbeb.png">

**Comment by miikkuu** [comment]
@trucy 
Would like to solve. Please assign me!

**Comment by trucy** [comment]
You got it
