### ISSUE TITLE
all chat info menu needs ui polish

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#2304]
<img width="387" alt="Screen Shot 2023-01-28 at 5 17 16 PM" src="https://user-images.githubusercontent.com/6990215/215295499-12fd6d57-145f-4b2e-b3d7-515dd4fe9b04.png">

**Comment by armaniferrante** [comment]
see figma (if it exists) tagging @trucy

**Comment by armaniferrante** [comment]
Also note that the skeletons + loading for this screen also needs a lot of work.

**Comment by trucy** [comment]
[Designs here](https://www.figma.com/file/HNF2HJZYq6dUzCWxSmH2Oe/Backpack-_-Questlog?node-id=17371%3A141684&t=ubXj7yFO57Aahz2t-1)
