### ISSUE TITLE
chat more info menu needs ui polish

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#2306]
See menu here.

<img width="387" alt="Screen Shot 2023-01-28 at 5 34 03 PM" src="https://user-images.githubusercontent.com/6990215/215295911-6666479c-8838-4fd6-a11f-7a931eace96e.png">

**Comment by armaniferrante** [comment]
Tagging @trucy for figmas.

**Comment by trucy** [comment]
https://www.figma.com/file/HNF2HJZYq6dUzCWxSmH2Oe/Backpack-_-Questlog?node-id=17287%3A130921&t=0cwtptFZAvGBmDYW-1

**Comment by callensm** [comment]
what's the intended change here? getting a bit confused with the figma comments on this one.

**Comment by trucy** [comment]
@callensm got it. tldr

- we should use the same component across the site, which might require adjusting the one on the NFT page and anywhere else you can find
- if we aren't supporting tab to focus states on elements, just use the browser default styles
- min 128px width then expand to fit content, never truncating (unless you recommend not doing this)
- i will make another ticket related to the "open in external" icon
