### ISSUE TITLE
multiple consecutive messages should bunch them 

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#2312]
Right now if you send a bunch of consecutive messages, they show up as separate lines/messages. Instead they should be bunched together, still as separate messages, but with a single name and icon like tg.

<img width="295" alt="Screen Shot 2023-01-29 at 10 12 10 AM" src="https://user-images.githubusercontent.com/6990215/215339342-12731709-a698-4901-bca2-d11c434691c0.png">
<img width="275" alt="Screen Shot 2023-01-29 at 10 12 55 AM" src="https://user-images.githubusercontent.com/6990215/215339371-f38e09f1-b270-4ac4-8e4b-39bae4b49849.png">

**Comment by irffanasiff** [comment]
and this one too

**Comment by armaniferrante** [comment]
Closed by #2330.
