### ISSUE TITLE
messaging: images show up squished

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#2313]
<img width="390" alt="Screen Shot 2023-01-29 at 10 14 23 AM" src="https://user-images.githubusercontent.com/6990215/215339471-209b31b9-bc7d-4de0-8abb-ed05a5bab4ee.png">

**Comment by armaniferrante** [comment]
Related: notice how the time is clipped on the right, as well.

**Comment by irffanasiff** [comment]
this one too

**Comment by armaniferrante** [comment]
#2320 fixed the squished image, but note that the time is still clippedd off on the edge
<img width="395" alt="Screen Shot 2023-01-29 at 12 36 07 PM" src="https://user-images.githubusercontent.com/6990215/215348310-fc915295-7bd8-4e8d-bc21-8cd961da7f9b.png">

**Comment by irffanasiff** [comment]
fixed please close this

**Comment by hkirat** [comment]
@irffanasiff the timestamp is still overflowing from the right 
You should be able to see it when you see this message in the backpack chat.
<img width="361" alt="Screenshot 2023-01-31 at 11 50 06 AM" src="https://user-images.githubusercontent.com/8079861/215682149-261aa00b-8921-498b-82be-b03688825966.png">

**Comment by hkirat** [comment]
Closing in favor of https://github.com/coral-xyz/backpack/issues/2334
