### ISSUE TITLE
reply form UI needs polish

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#2314]
See figma

<img width="393" alt="Screen Shot 2023-01-29 at 10 59 59 AM" src="https://user-images.githubusercontent.com/6990215/215342917-f46d623c-479b-4005-92bc-b5797a98ab52.png">

**Comment by irffanasiff** [comment]
doing this

**Comment by irffanasiff** [comment]
@armaniferrante can you add a screenshot if there is a design for it

**Comment by trucy** [comment]
@irffanasiff https://www.figma.com/file/NuXRbSjtCQ7IRXlWBqkxpz/Backpack-Design-(Public)?node-id=402%3A4716&t=FYKhXW9AZlmZbywd-1 thank you!

**Comment by trucy** [comment]
Related: replies styling is part of this ticket https://github.com/coral-xyz/backpack/issues/2121

**Comment by irffanasiff** [comment]
close this pr #2392 fixes it
