### ISSUE TITLE
tagging autocomplete needs ui polish

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#2316]
![Home (3)](https://user-images.githubusercontent.com/6990215/215345196-a1b26a7f-4a5f-4c45-8608-a6631e80e366.png)

**Comment by irffanasiff** [comment]
im on it

**Comment by trucy** [comment]
Design specs for this are [here](https://www.figma.com/file/NuXRbSjtCQ7IRXlWBqkxpz/Backpack-Design-(Public)?node-id=431%3A4735&t=EtRY1329dY5SVUrb-1)

cc @irffanasiff

**Comment by hkirat** [comment]
@irffanasiff if you could prioritise this one it would be great, might be the highest impact amongst the ones you're working on

**Comment by irffanasiff** [comment]
done

**Comment by hkirat** [comment]
Hey @irffanasiff could you point me to the PR where this is done?

**Comment by hkirat** [comment]
This is done
