### ISSUE TITLE
Clicking on a tagged @name should push onto the nav stack a new peer to peer message chat room

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#2322]
Clicking `@armani1` here.

<img width="369" alt="Screen Shot 2023-01-29 at 12 42 06 PM" src="https://user-images.githubusercontent.com/6990215/215348602-a0a33caf-4e95-4119-86b0-576f30184f61.png">

**Comment by irffanasiff** [comment]
assign this to me if no one is working on it
