### ISSUE TITLE
Update design for drag and drop attachments

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#2346]
No. 8 on [this list](https://github.com/coral-xyz/backpack/issues/2107), making a new ticket so it's easier to track

[Figma](https://www.figma.com/file/HNF2HJZYq6dUzCWxSmH2Oe/Backpack-_-Questlog?node-id=17334%3A135794&t=TAjMml3t2cMzuW3t-1)

**Comment by armaniferrante** [comment]
Seems mostly done. Note that dragging and dropping over the chat works, but dragging and dropping over the message input does not.

https://user-images.githubusercontent.com/6990215/215635638-4ba6ab3f-8cb0-4bdb-8cca-66d3a8dd28ae.mov

**Comment by trucy** [comment]
Oh yeah, this is just polish for the full screen feedback before a user does mouse up while holding file over the chat area. I can edit the title so it's more clear
