### ISSUE TITLE
graphical glitch in app signing toggle

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#2381]
Hovering over it cuts it in half, maybe related to https://github.com/coral-xyz/backpack/issues/2380

<img width="399" alt="Screenshot 2023-02-01 at 11 17 15 PM" src="https://user-images.githubusercontent.com/489202/216015562-b55a26ac-1d8c-4d0c-81d9-5c262b5c5b08.png">

**Comment by callensm** [comment]
i fixed this in a previous PR for all `<SwitchToggle />` components
