### ISSUE TITLE
Add a loader when I click on `create new wallet`

### ISSUE THREAD

**Issue by hkirat** [coral-xyz/backpack#2416]
When I click on `create new wallet` , nothing happens for a few seconds. We should show a loader, disable the button when the wallet is being created

![Screenshot 2023-02-02 at 1 16 01 PM](https://user-images.githubusercontent.com/8079861/216262705-67d2eb5d-c0b6-4607-a078-2c09755a6205.png)

**Comment by tomlinton** [comment]
https://github.com/coral-xyz/backpack/issues/2402 🙂
