### ISSUE TITLE
notification bubble doesn't clear 

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#2418]
https://user-images.githubusercontent.com/6990215/216364977-67fc28c2-7fb6-4274-aafd-1ebfbfd5cb6f.mov

**Comment by armaniferrante** [comment]
Related issue: I have notifications that are showing up as empty. I expect to see some friend requests.

**Comment by hkirat** [comment]
I think your notifications might be pointing to legacy xnft ids, I had the same problem. Will clear the notifications table
