### ISSUE TITLE
contact images are broken

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#2419]
I think there might be two separate issues here:

* images are breaking when they shouldn't (not 100% certain of this)
* when an image is broken, we should fallback to another icon

<img width="402" alt="Screen Shot 2023-02-02 at 9 21 43 AM" src="https://user-images.githubusercontent.com/6990215/216365647-20e6d1f7-64bf-4af8-a0d8-d14902d6235d.png">

**Comment by hkirat** [comment]
Probably related https://github.com/coral-xyz/backpack/pull/2393
