### ISSUE TITLE
Remove Cold Wallet description text

### ISSUE THREAD

**Issue by aarongillett** [coral-xyz/backpack#2460]
“Disable app signing in wallet info” is confusing as it sounds like an instruction, telling me to _disable app signing_. We already have the info tooltip “Backpack cold wallets can’t sign for apps” so I think that’s sufficient and we can just remove the “Disable app signing in wallet info” text.

<img width="374" alt="image" src="https://user-images.githubusercontent.com/4157473/216667407-16a0cb8f-3d6e-4199-8002-4f33285fa00c.png">

**Comment by armaniferrante** [comment]
Closed by 5695f79176dd6899e9cace682c7bf02dbab75900
