### ISSUE TITLE
reply button unclickable sometimes

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#2485]
See the beginning of the video. I'm unable to click reply for `@ericc`, but once I send a message something changes with the layout and I'm later able to reply.
https://user-images.githubusercontent.com/6990215/216852903-283c3b1d-208c-4d5d-8801-28d5c1766c42.mov

**Comment by hkirat** [comment]
Closed via https://github.com/coral-xyz/backpack/pull/2493
