### ISSUE TITLE
Clicking both addresses should copy the address to clipboard 

### ISSUE THREAD

**Issue by aarongillett** [coral-xyz/backpack#2486]
### Clicking both addresses should copy the address to clipboard (with copied! tooltip pattern)

<img width="371" alt="Screenshot 2023-02-05 at 17 42 05" src="https://user-images.githubusercontent.com/4157473/216852835-2d4f6e7c-4663-408e-b5b8-dc93cf7b9dee.png">

**Comment by Abhijit20112003** [comment]
Hey!, I want to contribute to this issue please assigned me

**Comment by armaniferrante** [comment]
This is done.
