### ISSUE TITLE
Want to show $EPCT on Solana Wallet

### ISSUE THREAD

**Issue by KishiTheMechanic** [coral-xyz/backpack#2510]
Hi. How are you? Thank you for your development always.
I'm kishi.sol from Epics DAO.

We're using backpack Solana wallet but it doesn't show our Token $EPCT which is listed on Orca and Jupiter.
Soon it will be verified by Jupiter.

$EPCT information👇

Ticker: EPCT
Token address: CvB1ztJvpYQPvdPBePtRzjL4aQidjydtUz61NWgcgQtP
Token Decimal: 6
Coin image: https://bafybeibal7k2hz6frznyjbl4qcnzcwlsuzxmquatrsaly6ttmuppgmdvwe.ipfs.w3s.link/EpicsCoin.png
Logo image: https://bafybeiamum7b44m2j7nb3prplfqdafzrea7t4ztn3tgkbf2w6c3znxewo4.ipfs.w3s.link/Epics-logo-background.png
Website: https://epics.dev/en
Epics Platform: https://alpha.epics.dev/en
Whitepaper: https://storage.googleapis.com/epics-bucket/WhitePaper/EpicsWhitePaperV2-1-0EN.pdf
Pitch: https://speakerdeck.com/epicsdao/epics-buidl-to-earn
CoinGecko: https://www.coingecko.com/en/coins/epics-token
Birdeye: https://birdeye.so/token/CvB1ztJvpYQPvdPBePtRzjL4aQidjydtUz61NWgcgQtP
Twitter: https://twitter.com/EpicsDAO2
Token address tweet: https://twitter.com/EpicsDAO2/status/1622536326170935296

**Comment by armaniferrante** [comment]
@KishiTheMechanic can you send a very small amount to the dev wallet here `EcxjN4mea6Ah9WSqZhLtSJJCZcxY73Vaz6UVHFZZ5Ttz` so that we can test. I suspect this has already been fixed on the latest version.

**Comment by KishiTheMechanic** [comment]
Thank you for your response!
I sent 1 $EPCT to the wallet.

That's amazing!! I'm looking forward to the latest version also!

Thank you always🙌

**Comment by armaniferrante** [comment]
Currently shows up as 

<img width="443" alt="Screen Shot 2023-02-06 at 4 11 22 PM" src="https://user-images.githubusercontent.com/6990215/217099146-a992c739-653e-4253-959c-00357ca09fc1.png">

**Comment by armaniferrante** [comment]
coingecko entry added here 324a06a70bbdfea33a42d9849d68b3ac62c8a2ac

**Comment by KishiTheMechanic** [comment]
Ohhhhhhhh amazing!!!

Thank you so much🙌
