### ISSUE TITLE
Send button is missing from messaging input

### ISSUE THREAD

**Issue by aarongillett** [coral-xyz/backpack#2527]
Send button should be visible when:
- text is input
- emoji in input
- image is added

<img width="517" alt="image" src="https://user-images.githubusercontent.com/4157473/217324127-f9762a13-3ca8-48e6-8d84-a94984aacd4f.png">

**Comment by tomlinton** [comment]
There was a discussion about this and I think the removal was intentional. Will bump the thread in Slack and we can reopen if necessary.
