### ISSUE TITLE
render loop when settings menu open

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#2581]
<img width="1604" alt="Screenshot 2023-02-09 at 7 54 15 PM" src="https://user-images.githubusercontent.com/489202/217739524-4a1217de-d92e-4a96-91a8-a2551e0d3f93.png">

**Comment by tomlinton** [comment]
Goes away if you remove the component from the title here https://github.com/coral-xyz/backpack/blob/9000d67fd2b063f021eeedbd4e07e2a7dc1572ea/packages/app-extension/src/components/Unlocked/Settings/index.tsx#L53

**Comment by armaniferrante** [comment]
closed by da03ddad7d95b048e3818e57a57cab6150ddc621
