### ISSUE TITLE
cant open chat if no solana wallets

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#2609]
I.e. Solana disabled, onboarding a solana wallet fixed it.

<img width="375" alt="Screenshot 2023-02-10 at 8 12 11 PM" src="https://user-images.githubusercontent.com/489202/218026224-5fb8e6fd-df5c-4907-b690-935aa3e0ad99.png">

**Comment by hkirat** [comment]
Closed via https://github.com/coral-xyz/backpack/pull/2627
