### ISSUE TITLE
Proxy all `send` requests through the backend

### ISSUE THREAD

**Issue by hkirat** [coral-xyz/backpack#2644]
We should proxy the requests to Semd from our backend servers so as to have an atomic operation of adding a chat message when the txn succeeds/fails

**Comment by armaniferrante** [comment]
Is this for transaction sends? Not sure I fully understand.

**Comment by hkirat** [comment]
Correct

**Comment by armaniferrante** [comment]
We currently don't send chat messages after sending tokens, so this is no longer relevant. Can re-open if we decide to go back to that feature.
