### ISSUE TITLE
messages loading state has a stray `00` below skeleton components

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#2647]

**Comment by tomlinton** [comment]
<img width="376" alt="Screenshot 2023-02-13 at 11 56 14 AM" src="https://user-images.githubusercontent.com/489202/218342392-010f0e98-3d5e-42c1-a5e0-555141714408.png">

**Comment by armaniferrante** [comment]
Is this still the case?

**Comment by tomlinton** [comment]
Nope, looks like its fixed.
