### ISSUE TITLE
View profile addresses from contact card

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#2684]
I should be able to see all the addresses associated with a given user from the contact card.

<img width="487" alt="Screen Shot 2023-02-14 at 5 53 56 AM" src="https://user-images.githubusercontent.com/6990215/218730874-18c449a5-b5c3-4218-b5af-486325239aff.png">

**Comment by tomlinton** [comment]
This is now a single address that should be displayed.

**Comment by armaniferrante** [comment]
Would be good to get a quick design for this @aarongillett
