### ISSUE TITLE
swap screen crash

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#2685]
* open swaps
* click on input field

crash

<img width="487" alt="Screen Shot 2023-02-14 at 7 35 59 AM" src="https://user-images.githubusercontent.com/6990215/218754151-0ddb645b-7123-4539-afdf-0b4a9e0ebea9.png">

**Comment by tomlinton** [comment]
Is this still an issue @armaniferrante? Never reproduced it, the code has changed so might be worth checking if it still occurs.

**Comment by armaniferrante** [comment]
Can't repro anymore.
