### ISSUE TITLE
Issue while syncing two wallets

### ISSUE THREAD

**Issue by hkirat** [coral-xyz/backpack#2688]
Steps to reproduce - 
1. Import a wallet in 2 browsers
2. Add a new wallet to one of the browsers
3. The other browser shows you an import error when it should automatically import (All wallets in the example are mnemonic based)
![Screenshot 2023-02-15 at 12 54 03 AM](https://user-images.githubusercontent.com/8079861/218837321-6507b725-6147-44af-a3ed-a331e50ec3e8.png)

**Comment by tomlinton** [comment]
Are you using the latest? This should have been handled by https://github.com/coral-xyz/backpack/commit/1903434faba8757cacad309e7b33f86704e75afd which was merged yesterday.

**Comment by tomlinton** [comment]
Will assume it's fixed, please reopen if not!
