### ISSUE TITLE
allow more than 5 options for importing wallets

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#2699]
This is mostly just a design question, should this be paginated or scrollable? 

<img width="386" alt="Screenshot 2023-02-15 at 2 17 48 PM" src="https://user-images.githubusercontent.com/489202/218900105-de33f49d-cd55-4d81-a758-1ddb66c0f865.png">

**Comment by armaniferrante** [comment]
Let's just make it scrollable.
