### ISSUE TITLE
usdc is sometimes undefined in account history token swap transactions

### ISSUE THREAD

**Issue by wentokay** [coral-xyz/backpack#2730]
<img width="343" alt="Screenshot 2023-02-15 at 19 14 30" src="https://user-images.githubusercontent.com/101902546/219259109-4bebe98e-ba15-4af5-9efa-16cb38605c5f.png">

USDC mint address `EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v`

**Comment by wentokay** [comment]
<img width="352" alt="Screenshot 2023-02-15 at 19 17 09" src="https://user-images.githubusercontent.com/101902546/219259363-b71336bb-c39c-4141-a962-c2a086ef3390.png">

I think it's all swaps _to_ USDC, swaps _from_ USDC look as expected

**Comment by tomlinton** [comment]
I get it with other tokens, also the values are wrong. I did not swap 2299848000.00000.

<img width="379" alt="Screenshot 2023-02-16 at 10 43 57 PM" src="https://user-images.githubusercontent.com/489202/219328684-ed318d36-b901-476c-8a9b-160acb06abe7.png">

**Comment by tomlinton** [comment]
https://github.com/coral-xyz/backpack/commit/9c59f385f6f6198ff3e3ec3b2d9fd74a39657fec
