### ISSUE TITLE
switch tokens button in swapper leaves output mint input empty

### ISSUE THREAD

**Issue by wentokay** [coral-xyz/backpack#2731]
https://user-images.githubusercontent.com/101902546/219260897-f3d8906d-743f-4c78-ba43-56aacfcab453.mov

**Comment by tomlinton** [comment]
It does this because there is no USDC -> SOL path. There is a USDC -> wSOL path but the input mint here is SOL not wSOL. It needs a special case.

In general if you do USDT -> USDT and switch the tokens it won't depopulate.

**Comment by wentokay** [comment]
understood! thanks for the explanation
