### ISSUE TITLE
transaction history display broken

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#2736]
<img width="377" alt="Screenshot 2023-02-16 at 10 22 44 PM" src="https://user-images.githubusercontent.com/489202/219322986-fc447574-ae87-4d84-83b1-bb07e787e43f.png">

**Comment by callensm** [comment]
i'm confused, are these USDC -> USDC swaps?

can you dm me the wallet so i can debug

**Comment by armaniferrante** [comment]
Is this fixed?

**Comment by tomlinton** [comment]
Yep
