### ISSUE TITLE
"gm @" when upgrading from chrome build to master

### ISSUE THREAD

**Issue by wentokay** [coral-xyz/backpack#2742]
- create account in backpack [chrome store build](https://github.com/coral-xyz/backpack/files/10757895/build.zip)
- replace chrome store build directory with master build directory
- reload extension in chrome://extensions
- username is missing in "gm @" message on log in screen

<img width="487" alt="Screenshot 2023-02-16 at 07 52 02" src="https://user-images.githubusercontent.com/101902546/219421078-522f6163-b0ae-4c71-982e-b8506daa8766.png">

I haven't tested if this also affects the user avatar yet

**Comment by wentokay** [comment]
after locking backpack the gm message is correct

**Comment by armaniferrante** [comment]
as dicsused, we're just going to ignore this
