### ISSUE TITLE
consistent search for placeholders

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#2757]
I think the first one should be `Search for people or send to address`. It's not clear you can input an address here, and not just search for a person by their address.

<img width="376" alt="Screenshot 2023-02-17 at 8 23 41 AM" src="https://user-images.githubusercontent.com/489202/219466659-0150072e-7454-483a-9b54-34c0f89d0475.png">
<img width="376" alt="Screenshot 2023-02-17 at 8 23 52 AM" src="https://user-images.githubusercontent.com/489202/219466675-6ea971c1-9faa-4da4-abc6-218e21546ca8.png">

**Comment by trucy** [comment]
How ab "Search for people or an address" ?

**Comment by tomlinton** [comment]
That captures:

- Search for people
- Search for address

What we need to capture is:

- Search for people by name
- Search for people by address
- Send to an address

I think maybe "Enter a username or an address" might get everything. There is a lot going on in one input 🙂

**Comment by tomlinton** [comment]
Went with that for now!

**Comment by trucy** [comment]
I actually forgot with this UI you can still send to an address 😂 I think your suggestion makes more sense but I will create a new ticket for a design enhancement that will make this function more clear
