### ISSUE TITLE
expanding message send thing should push messages up 

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#2783]
Bottom message cuts off:

<img width="378" alt="Screenshot 2023-02-17 at 2 39 01 PM" src="https://user-images.githubusercontent.com/489202/219527613-d6393822-006d-41f9-8d41-2f9e0fce2e82.png">

**Comment by tomlinton** [comment]
Looks like dark mode just does opacity here, so maybe that'll work for light mode.

**Comment by armaniferrante** [comment]
Let's push the message up. This is really annoying after you've pointed it out!
