### ISSUE TITLE
prevent wrap on negative/positive symbol in token symbol

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#2811]
Negative/positive symbol should never be on a line on its own.

<img width="382" alt="Screenshot 2023-02-19 at 9 53 14 AM" src="https://user-images.githubusercontent.com/489202/219899027-e5d71d93-e8f0-43bc-b90d-5f0ccecdba54.png">

**Comment by jim4067** [comment]
let me try this

**Comment by beingkarnage** [comment]
Hi, I'm new to open source, would like to work on this issue

**Comment by armaniferrante** [comment]
Putting on @callensm as we may want to just rewrite the entire thing.

**Comment by tomlinton** [comment]
Closed #3145
