### ISSUE TITLE
unnecessary truncation on names in contact search

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#2832]
Contact name is `testing_tom5`, it fits easily here without truncation.

<img width="377" alt="Screenshot 2023-02-20 at 9 15 11 AM" src="https://user-images.githubusercontent.com/489202/219973197-901a5a64-ea3b-46b4-a260-1c90b70c2e5b.png">

**Comment by hkirat** [comment]
Fixed in master
