### ISSUE TITLE
clicking on user tag in DM should open users profile not attempt to open chat

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#2836]
<img width="378" alt="Screenshot 2023-02-20 at 9 56 39 AM" src="https://user-images.githubusercontent.com/489202/219974717-50f745e2-07b9-4bf1-b328-362063b3e24a.png">

Clicking the tag @backpack_dev in the chat message attempts to open our current chat, which is already open. If we are in a DM it should open their profile instead (or just have the link removed altogether).

**Comment by trucy** [comment]
Related: https://github.com/coral-xyz/backpack/issues/2062
Note: in the near future we want something like https://github.com/coral-xyz/backpack/issues/2678

**Comment by trucy** [comment]
Once we have this, it could be the behavior for hovering on tagged users too https://github.com/coral-xyz/backpack/issues/2678
