### ISSUE TITLE
Onboarding is broken

### ISSUE THREAD

**Issue by hkirat** [coral-xyz/backpack#2872]
I see this after setting the password

I can still get into the wallet after this, so it isn't blocking me from getting in.

![Screenshot 2023-02-21 at 9 46 42 PM](https://user-images.githubusercontent.com/8079861/220428417-30706584-f588-424f-8a12-8468ae198b18.jpg)
![Screenshot 2023-02-21 at 9 46 36 PM](https://user-images.githubusercontent.com/8079861/220428422-eb76304b-cf5e-4bd6-8d6e-833cdf6c9ed6.png)

**Comment by tomlinton** [comment]
https://github.com/coral-xyz/backpack/pull/2879
