### ISSUE TITLE
review button doesn't work 

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#2878]
<img width="434" alt="Screen Shot 2023-02-21 at 1 44 58 PM" src="https://user-images.githubusercontent.com/6990215/220443293-a617a062-d99e-472b-a3ee-0de920c49ed6.png">

**Comment by peterpme** [comment]
After clearing my build cache `git clean -xfd && yarn && yarn build` this seemed to go away unless it was fixed? i'm able to click "Review" now

**Comment by armaniferrante** [comment]
@peterpme's suggestion works. Thanks.
