### ISSUE TITLE
switching accounts really fast results in error

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#2881]
Because of https://github.com/coral-xyz/backpack/issues/2880 it's possible to flick accounts really fast because the menu disappears, which resulted in this error:

<img width="381" alt="Screenshot 2023-02-22 at 10 02 05 AM" src="https://user-images.githubusercontent.com/489202/220457794-6d166441-ce46-4530-975a-b56e0b04fd78.png">

It's probably not possible to do this if the menu doesn't persist but it's a condition we should prevent anyway.

**Comment by tomlinton** [comment]
This is probably because notifications are only processed some time after rerenders in the client.

**Comment by armaniferrante** [comment]
Is this happening on prod? Is it creating any noticeable problems? Or is it just a dev mode error?

**Comment by armaniferrante** [comment]
Switching to p2 unless there's a functional issue here in prod.

**Comment by tomlinton** [comment]
You can't trigger this because the switching account menu no longer remains open (that transition bug).
