### ISSUE TITLE
loading wallet attempts to load metadata for many users

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#2889]
<img width="826" alt="Screenshot 2023-02-22 at 4 22 49 PM" src="https://user-images.githubusercontent.com/489202/220513301-38638780-5a63-4e19-afbd-0d404522ee07.png">
<img width="358" alt="Screenshot 2023-02-22 at 4 22 54 PM" src="https://user-images.githubusercontent.com/489202/220513307-2ae109af-c96c-433e-b5d6-107749f72a45.png">

**Comment by hkirat** [comment]
can you take a screenshot of your indexed db `users` table?

**Comment by hkirat** [comment]
nvm can reproduce locally

**Comment by tomlinton** [comment]
Closing as I believe this was due to some legacy state on my account
