### ISSUE TITLE
export secret key broken

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#2905]
<img width="430" alt="Screenshot 2023-02-22 at 10 00 43 PM" src="https://user-images.githubusercontent.com/489202/220571997-d30cd756-b647-4142-9be2-1ca08a29b5a3.png">
<img width="587" alt="Screenshot 2023-02-22 at 10 01 00 PM" src="https://user-images.githubusercontent.com/489202/220572005-527c1ec9-7ba0-402d-83c7-813897bda163.png">

**Comment by tomlinton** [comment]
Note this was for an account that was imported via secret key, the other case of an account being mnemonic based seems to work.

**Comment by armaniferrante** [comment]
closed by 18181ac0dd4b68ce61c82da389ed995abba4079a
