### ISSUE TITLE
empty contact state

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#2908]
The title/horizontal line shouldn't show if the user has no contacts.

<img width="375" alt="Screenshot 2023-02-22 at 10 16 22 PM" src="https://user-images.githubusercontent.com/489202/220575872-8478f33d-e758-4c72-87e9-0b254695ad9f.png">

**Comment by hkirat** [comment]
@tomlinton could you share the steps to reproduce?
Tried on a fresh wallet and I see this 
![Screenshot 2023-02-23 at 12 00 08 AM](https://user-images.githubusercontent.com/8079861/220723537-ed571cdf-c2f6-4d43-bb67-9e55cc82f336.jpg)

**Comment by tomlinton** [comment]
Can't repro anymore, will close.
