### ISSUE TITLE
export secret key style crash

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#2909]
Export secret key crashes on inputting password for mnemonic based account. Distinct from #2905 

<img width="381" alt="Screenshot 2023-02-22 at 10 18 41 PM" src="https://user-images.githubusercontent.com/489202/220576383-45f11154-5c7f-4d72-ba10-f6b865b87644.png">

**Comment by hkirat** [comment]
Closed via https://github.com/coral-xyz/backpack/pull/2916
