### ISSUE TITLE
search for contacts from settings/contacts doesn't work

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#2910]
This search doesn't appear to send any network requests.

<img width="379" alt="Screenshot 2023-02-22 at 10 30 39 PM" src="https://user-images.githubusercontent.com/489202/220579419-ecd23fb2-a20c-49ed-8e14-803204cb123f.png">
<img width="374" alt="Screenshot 2023-02-22 at 10 30 33 PM" src="https://user-images.githubusercontent.com/489202/220579431-c83bf81a-5484-485d-9123-f17ca0ee095a.png">

**Comment by hkirat** [comment]
Search shouldnt send requests since all the contacts are stored locally. 
Does this user have contacts @tomlinton ?

**Comment by hkirat** [comment]
Unable to reproduce, assuming you tested with a user that had no contacts. 
Feel free to re-open if you can reproduce with a user that has contacts

**Comment by tomlinton** [comment]
Yea that's right. Then it is the text that doesn't make sense. I can't search for people to add if it's local only.

**Comment by hkirat** [comment]
Ah yeah probably should say `search for contacts`. Will change
