### ISSUE TITLE
messages: pending friend request at bottom of screen 

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#2970]
<img width="383" alt="Screen Shot 2023-02-24 at 1 44 16 AM" src="https://user-images.githubusercontent.com/6990215/221121211-54fb5cf7-2096-4404-bf93-d1dde84a7fba.png">

**Comment by tomlinton** [comment]
Looks done here https://github.com/coral-xyz/backpack/commit/35266b9ee70a358ed0375f06baa3bbeeb80101ea
