### ISSUE TITLE
extension auto-locks after ~5 minutes despite it being set to "Never"

### ISSUE THREAD

**Issue by monk-doesnt** [coral-xyz/backpack#2985]

**Comment by wentokay** [comment]
I think this might be due to the background service worker process timing out. Will look into it

**Comment by wentokay** [comment]
Haven't been able to reproduce yet. Can you give any more details @monk-doesnt? Is the extension in popout mode when this happens?

**Comment by wentokay** [comment]
Oh is this happening when the wallet is closed and you try to reopen it 5 minutes later?

If that's the case I think it's because `UI_RPC_METHOD_KEYRING_STORE_KEEP_ALIVE` can't be sent while the extension is closed.

**Comment by armaniferrante** [comment]
dup of #3027
