### ISSUE TITLE
Share nfts in messages 

### ISSUE THREAD

**Issue by hkirat** [coral-xyz/backpack#3013]
Users should be able to select and share their own nfts in the messaging app with a ✅ , explorer link

**Comment by armaniferrante** [comment]
Moving to p2. This will be good to have for a fast barrage of feature releases post mint.

**Comment by armaniferrante** [comment]
Let's get this over the fence but keep it behind a remote feature flag that we can turn on to align with announcements.

**Comment by hkirat** [comment]
yup sounds good
