### ISSUE TITLE
Extension doesnt open on a choppy internet connection

### ISSUE THREAD

**Issue by hkirat** [coral-xyz/backpack#3020]
Saw this yesterday where the extension wont open if the internet connection was bad (mine was borderline dead only)

There's probably a request to the internet that's blocking the opening of the extension

**Comment by callensm** [comment]
do you mean the extension window never appeared or the window appeared but nothing rendered?

**Comment by hkirat** [comment]
The window never opened. Let me try to reproduce.

**Comment by hkirat** [comment]
hmm unable to reproduce, this may have happened because I had the console open somewhere with a breakpoint in the sw. Closing it for now
