### ISSUE TITLE
URLs in messages show up as regular text instead of blue linked text

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#3021]
<img width="375" alt="Screenshot 2023-02-27 at 10 34 47 AM" src="https://user-images.githubusercontent.com/321395/221628989-9258bdad-4f3b-47bb-948f-c5e7c8d99bfe.png">

This should be what's in this ticket https://github.com/coral-xyz/backpack/issues/2941

**Comment by hkirat** [comment]
This was done for security reasons, will add it back post audit
