### ISSUE TITLE
Show pfp in group chat members drawer

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#3026]
Might be nice to show the same pfp as inbox view in the group members drawer

**Comment by trucy** [comment]
Oops I forgot to link the [Figma](https://www.figma.com/file/HNF2HJZYq6dUzCWxSmH2Oe/Backpack-_-Questlog?node-id=19516%3A157974&t=SnapiZ4iIxlqTgud-1)

**Comment by armaniferrante** [comment]
Put as p2 but should be quick to do if one feels so inclined.
