### ISSUE TITLE
backpack should close nft detail page when switching users

### ISSUE THREAD

**Issue by wentokay** [coral-xyz/backpack#3045]
to reproduce

- open collectibles tab via button at the bottom
- click on an NFT
- click on balances button at the bottom left
- switch to a different user
- open collectibles via button at the bottom

it will be stuck on the NFT detail page of the original user, so the NFT is not found and it's a blank screen with the NFT's name

**Comment by armaniferrante** [comment]
We have the same problem with the tokens page, this is because the routing uses URLs use addresses belonging to a given user that are no longer valid.
