### ISSUE TITLE
stuck loading when creating a wallet from a secret recovery phrase

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#3051]
![image](https://user-images.githubusercontent.com/6990215/221969699-cb35baed-23cd-4ce2-a739-0fbc26478e5f.png)

**Comment by tomlinton** [comment]
No leads on this, never experienced. Could have been a failed network request.

**Comment by tomlinton** [comment]
At least one report of this was using kiwi browser, that above screenshot looks like Chrome though.

**Comment by armaniferrante** [comment]
Closing until we have more information.
