### ISSUE TITLE
unable to click mad lads banner

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#3052]
I"m unable to reproduce but there have been ~8 reports of this.

**Comment by wentokay** [comment]
I've been unable to reproduce in chrome and brave on Mac OS as well as chrome and edge on Windows 11

Tried with different types of accounts too, it might help if we could get a username or pubkey of someone that's affected

**Comment by ph101pp** [comment]
Yea same, not able to reproduce so far

**Comment by monk-doesnt** [comment]
some users facing this issue on Windows via Chrome managed to get it to work on Brave

**Comment by armaniferrante** [comment]
Closing until we get more reports on the latest build.
