### ISSUE TITLE
Swapper Network Fee doesn't include rent fee for creating an ATA

### ISSUE THREAD

**Issue by wentokay** [coral-xyz/backpack#3089]
If I swap to an SPL token I've never owned I should see a slightly higher `Network fee` due to the cost of creating the associated token account

**Comment by armaniferrante** [comment]
Can we confirm if any other wallets do this?

**Comment by wentokay** [comment]
Phantom does it

**Comment by wentokay** [comment]
<img width="334" alt="Screenshot 2023-03-07 at 10 09 26" src="https://user-images.githubusercontent.com/101902546/223511134-74633f84-e95f-45d9-ab99-4c19ddc2e3fb.png">

**Comment by armaniferrante** [comment]
Great let's prioritize it then to be consistent with others.
