### ISSUE TITLE
Collectibles management enhancements

### ISSUE THREAD

**Issue by aarongillett** [coral-xyz/backpack#3102]
Details in Figma: https://www.figma.com/file/HNF2HJZYq6dUzCWxSmH2Oe/Backpack-_-Questlog?node-id=19553%3A162601&t=sF3C4IPZUdVLkqzk-1

**Comment by staticGuru** [comment]
@aarongillett 
Give the figma file access request

**Comment by staticGuru** [comment]
.take

**Comment by aarongillett** [comment]
Closing this as completed by @ph101pp

**Comment by aarongillett** [comment]
And thanks for reaching out and offering to contribute @staticGuru. We’ll try and get back to you sooner next time.
