### ISSUE TITLE
viewing collectibles tab crashes the app for some people

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#3109]
I'm unable to reproduce. I suspect it has to do with a particular (scam) nft.
<img width="1326" alt="Screen Shot 2023-03-02 at 11 11 58 AM" src="https://user-images.githubusercontent.com/6990215/222501959-47561979-3266-4655-ab66-269f761a3177.png">
<img width="840" alt="Screen Shot 2023-03-02 at 11 12 04 AM" src="https://user-images.githubusercontent.com/6990215/222501977-96d4b2c2-74ff-4170-aa98-e12d936f69f0.png">

**Comment by wentokay** [comment]
related #3073

**Comment by hkirat** [comment]
Did this happen on master? I think this is fixed in master
