### ISSUE TITLE
Stripe onramp broken

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#3118]
Happens to me and a couple others. After verifying with a previous account successfully, I see a brief flash of my wallet address then this screen

<img width="438" alt="Screenshot 2023-02-28 at 2 50 01 PM" src="https://user-images.githubusercontent.com/321395/222546426-13e24008-ec3e-48c7-9a38-21c99e21b2d5.png">

My log

<img width="1144" alt="Screenshot 2023-03-02 at 11 58 14 AM" src="https://user-images.githubusercontent.com/321395/222544667-fc0d048a-4eee-43f9-b2a9-08480b75a336.png">

**Comment by hkirat** [comment]
Have pinged them with the evidences. My guess it's an issue on their side and easily fixable, lets see

**Comment by hkirat** [comment]
Havent gone through the whole flow but I think this should be working now, dont see the error you saw above @trucy
