### ISSUE TITLE
Hide the empty user suggestions list in the chat sections.

### ISSUE THREAD

**Issue by staticGuru** [coral-xyz/backpack#3136]
**Describe the Bug**
In chat sections,
while the user mentioned in the chat sections using the '@' symbol showed empty suggestions.

**Expected behavior:**
It should not show, in the empty suggestions scenario.

![image](https://user-images.githubusercontent.com/79417096/222687659-13434acf-996b-4e24-9620-13f2b797bd79.png)

**Comment by staticGuru** [comment]
.take

**Comment by staticGuru** [comment]
I am working the on the issues

**Comment by staticGuru** [comment]
#3137

**Comment by staticGuru** [comment]
Issue fixed. Kindly merge the PR.
@armaniferrante

**Comment by yash-w3** [comment]
@staticGuru this was already fixed here https://github.com/coral-xyz/backpack/pull/3098

**Comment by armaniferrante** [comment]
Thanks!
