### ISSUE TITLE
Change "delete" to "remove" in removed message (shows up instead of the message being replied to)

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#3149]
~~A deleted message still remains if someone replied to it and the quoted text shows up~~

~~Before~~
<img width="434" alt="Screenshot 2023-03-03 at 12 23 59 PM" src="https://user-images.githubusercontent.com/321395/222798990-806d529d-9ca8-4ab0-9cad-ac175387e0a9.png">

~~Then, I deleted the message "going to test deleting messages here :D"~~

~~After, the original message shows "messaged removed" but "going to test deleting messages here :D" still shows up in the reply~~

<img width="374" alt="Screenshot 2023-03-03 at 12 27 03 PM" src="https://user-images.githubusercontent.com/321395/222799125-ac742a8e-d9e4-487a-8943-cbb0d43fc48e.png">

**Comment by trucy** [comment]
Oops. I didn't see it until now, but there is a lag between message removal and the UI showing it in both places. I will change this ticket to reflect a different request:

Can we change "deleted" to "removed" to match?

- Message removed
- This message was removed

**Comment by armaniferrante** [comment]
Closed by #3230.
