### ISSUE TITLE
tagged username in chat showed name + user id after sending message

### ISSUE THREAD

**Issue by monk-doesnt** [coral-xyz/backpack#3168]
<img width="237" alt="Screenshot 2023-03-04 at 1 54 55 AM" src="https://user-images.githubusercontent.com/104650166/222884361-e4f31935-2a4a-49e1-9d7e-3e47ea25744a.png">

**Comment by staticGuru** [comment]
@monk-doesnt You mentioned issues is replicable.

**Comment by staticGuru** [comment]
I will start work on it. 
Cool!!

**Comment by staticGuru** [comment]
@armaniferrante kindly assign the ticket to me.

**Comment by staticGuru** [comment]
#3169
