### ISSUE TITLE
z-index on mad labs banner blocks account switcher

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#3181]
<img width="379" alt="Screenshot 2023-03-06 at 9 29 01 AM" src="https://user-images.githubusercontent.com/489202/222984253-76f71fac-a283-4d35-b670-b6f7a8aaaa10.png">

**Comment by yash-w3** [comment]
Seems to be working for me in the current master branch

**Comment by ph101pp** [comment]
Only happened when the wallet has no nfts. Fixed here: #3182
