### ISSUE TITLE
Staff/verified badge should show up in tagged usernames popover too

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#3183]
<img width="237" alt="Screenshot 2023-03-06 at 8 50 47 AM" src="https://user-images.githubusercontent.com/321395/223145108-61a7d4f8-f818-48ad-baee-1c687945481d.png">

Would help with tagging the right person if others have similarly spelled usernames, but only one of them has a badge

**Comment by armaniferrante** [comment]
Closed by #3186
