### ISSUE TITLE
yarn install fails with node 19.x

### ISSUE THREAD

**Issue by x0samnan** [coral-xyz/backpack#3219]
When trying to run `yarn install`, it fails with the following,
```
yarn install v1.22.19
[1/5] Validating package.json...
error backpack@: The engine "node" is incompatible with this module. Expected version "18.x". Got "19.7.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
This seems to be an issue with package.json, can I open a PR updating it, so that it runs with node 19.x versions?

**Comment by wentokay** [comment]
sorry we're stuck with version 18 for now because of a strict requirement from expo and react-native in the monorepo

I'd recommend using [nvm](https://github.com/nvm-sh/nvm) or something similar if you want to easily switch between multiple node versions locally
