### ISSUE TITLE
collectibles: no margin for loading skeletons

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#3262]
The screenshot here has margin between the four geckos. The skeletons for this screen do not, however.

<img width="167" alt="Screen Shot 2023-03-09 at 3 51 31 PM" src="https://user-images.githubusercontent.com/6990215/224168364-f8396e27-28ea-412f-a0a2-ca2e59407c45.png">

**Comment by rt-web3** [comment]
I can take a look at this
