### ISSUE TITLE
balance change isn't correct

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#3267]
![image](https://user-images.githubusercontent.com/6990215/224196207-90225621-f9da-4eb9-8fd5-36c555595641.png) 
![image](https://user-images.githubusercontent.com/6990215/224196228-c35892f5-cf5d-4ab2-bb1a-3f626e661c3b.png)

**Comment by callensm** [comment]
was this reported via discord, or seen in one of our wallets?

**Comment by armaniferrante** [comment]
Reported via discord a couple of times.

**Comment by callensm** [comment]
i merged a PR a couple days ago to address this. curious if there's still an issue or it was seen on a version prior to that pr
