### ISSUE TITLE
No option to go back from waiting room

### ISSUE THREAD

**Issue by x0samnan** [coral-xyz/backpack#3292]
![bug](https://user-images.githubusercontent.com/92310785/224496147-8b911526-8632-4ecf-85f4-d287e9d98a2e.png)
Issue with Backpack DEV

- There is no option to go back after entering waiting room
- The page has to be reloaded to enter the invite code

**Comment by armaniferrante** [comment]
Let's just remove the waiting room. Will create a separate issue.
