### ISSUE TITLE
recovering account that was mnemonic based using a private key is problematic

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#3322]
This might be the same as https://github.com/coral-xyz/backpack/issues/3063

- Onboard with mnemonic
- Generate a few wallets
- Add a private key based wallet
- Reset backpack 
- Recover with the private key

You cannot add a mnemonic of your own at this point. You can create new accounts with a new mnemonic, but you can't go back and set the mnemonic to one you already have.

**Comment by tomlinton** [comment]
This will be the same with adding a ledger based account instead of the private key.

**Comment by armaniferrante** [comment]
Discussed elsewhere but reiterrating here. 

One solution is to treat private keys as we currently do ledgers. That is, allow one to generate a recovery phrase on demand inside the import flow. In addition, we should also provide the ability to import an existing key as part of that flow (this is the part we need to add here).

If we do the above, I think that more or less solves the problem and we can do #3063 as a related but separate issue later.

**Comment by tomlinton** [comment]
In the first situation described in the original issue you'll end up like this (all the accounts are on the same mnemonic):

<img width="375" alt="Screenshot 2023-03-13 at 10 42 49 PM" src="https://user-images.githubusercontent.com/489202/224664588-f2cee10a-f1ed-4380-94dd-c9ec97592c69.png">

When you hit the recover button you could recover it by selecting `Other secret phrase` here, but that does not set a mnemonic for the entire account. There almost needs to be another option `Set mnemonic for account` or similar if the account is not set up with a mnemonic.

<img width="376" alt="Screenshot 2023-03-13 at 10 42 57 PM" src="https://user-images.githubusercontent.com/489202/224664608-f1bb7b84-00f7-4502-90fa-b7be55397149.png">

**Comment by armaniferrante** [comment]
We now have the ability to import menmonics after onboarding with a ledger or private key. So this is done I think. Closing.
