### ISSUE TITLE
avatar loading is slow

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#3366]
https://user-images.githubusercontent.com/6990215/225445573-93b4a7bd-5a38-43fc-a59a-bf210816a592.mov

**Comment by armaniferrante** [comment]
Note: this is only happening on my account right now because I have a lot of friends and messages.

**Comment by wentokay** [comment]
can we remove the timestamp cachebuster from them?

each time we forcibly break the cache like that we're doing a DB request and making cloudflare images fetch, re-resize and reprocess the source image

**Comment by hkirat** [comment]
Potentially fixed by https://github.com/coral-xyz/backpack/pull/3371 . We were loading a lot of `LocalImageManagers` all trying to cache images causing the thread to be used by the canvas API.

**Comment by armaniferrante** [comment]
Appears fixed!
