### ISSUE TITLE
cant click create a new wallet after clicking once

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#3392]
This never gets reset to false

https://github.com/coral-xyz/backpack/blob/7133a581519c32ca0fab7f474765ca5632067852/packages/app-extension/src/components/Unlocked/Settings/AddConnectWallet/index.tsx#L153

Can force close the parent drawer after the wallet create so it gets reset.

**Comment by armaniferrante** [comment]
Closed by 2e42c9e7af387242e75255998562cecbcabdcc5d.
