### ISSUE TITLE
Creating an wallet creates two 

### ISSUE THREAD

**Issue by hkirat** [coral-xyz/backpack#3399]
Steps to reproduce

1. Make sure you're in an eth wallet
2. Create a new solana wallet
3. You should see two instances of the newly created wallet (wallet 2 in screenshot)

Goes away on refresh, only happens if you create a different chains wallet
![Screenshot 2023-03-17 at 12 54 16 PM](https://user-images.githubusercontent.com/8079861/225993786-85a227e9-ed7f-475b-acd4-b3fd091d329e.jpg)

**Comment by keshari1arya** [comment]
steps tried 
selected ethereum wallet
![Screenshot 2023-03-31 at 11 29 08 AM](https://user-images.githubusercontent.com/16665888/229036215-3130fba8-8fe7-41ba-92be-48e683931e12.png)
 
Went to setting and wallets 
in list of wallets page clicked on add wallet (+ icon) and continued with current user then clicked on create a new wallet 

![Screenshot 2023-03-31 at 11 29 08 AM](https://user-images.githubusercontent.com/16665888/229036592-7cb8115e-72b2-4634-8333-79c1fb77455b.png)
![Screenshot 2023-03-31 at 11 29 33 AM](https://user-images.githubusercontent.com/16665888/229036610-a4078cae-6c97-4ca2-bba7-71bfdbf7b468.png)
![Screenshot 2023-03-31 at 11 29 47 AM](https://user-images.githubusercontent.com/16665888/229036626-a1483355-217b-4d83-80a9-ac5b7f5b8225.png)
![Screenshot 2023-03-31 at 11 30 01 AM](https://user-images.githubusercontent.com/16665888/229036645-62da8daf-cd31-4ce8-b610-d4e7662ed1d8.png)
![Screenshot 2023-03-31 at 11 30 11 AM](https://user-images.githubusercontent.com/16665888/229036682-645a040c-4e76-4e0a-91b4-1e6755a08b6d.png)
i am getting only one wallet finally but surprising got the attached error below. 
i am thinking that the current issue is addressed but this is a new one 
![Screenshot 2023-03-31 at 11 30 28 AM](https://user-images.githubusercontent.com/16665888/229037243-3539b8d6-df8b-45fa-ab9d-3f731300c838.png)

**Comment by armaniferrante** [comment]
Done by #3427
