### ISSUE TITLE
Recovery of SOL accounts seems broken

### ISSUE THREAD

**Issue by hkirat** [coral-xyz/backpack#3400]
Trying to recover the `kira` user which has a bunch of SOL addresses created from the Neumonic and none seem to be recovering . Only eth wallets seem to be recovering
![Screenshot 2023-03-17 at 1 18 03 PM](https://user-images.githubusercontent.com/8079861/225999453-c287fda3-30cb-473d-a4db-d5e59b7e3243.jpg)

**Comment by hkirat** [comment]
When I go to recover, chose seed phrase, provide the same seed phrase I provided during onboarding I get the following
![Screenshot 2023-03-17 at 1 20 18 PM](https://user-images.githubusercontent.com/8079861/225999743-f328e45a-5663-4023-93ef-41385e876016.jpg)

**Comment by hkirat** [comment]
Clicking on `import wallet` I get 
![Screenshot 2023-03-17 at 1 20 14 PM](https://user-images.githubusercontent.com/8079861/225999772-475e58e1-6ee9-4e73-a2c3-a0a14fef6c53.jpg)

**Comment by tomlinton** [comment]
Your Solana primary public key doesn't seem to be here anywhere, is it one not from the mnemonic?

**Comment by hkirat** [comment]
My primary is EKkqH7ucpVN9pYTRnS6dv2hUDkNBvg9na3yQgPvgxFcc  (https://xnft-api-server.xnfts.dev/v1/users/fromUsername?username=kira) which does appear in the list
![Screenshot 2023-03-19 at 11 56 20 AM](https://user-images.githubusercontent.com/8079861/226197035-d339d52d-764c-4667-80dc-b7b991633d0c.jpg)

**Comment by hkirat** [comment]
Still seeing this btw on master

**Comment by hkirat** [comment]
Seems like this is only happening on my machine, @tomlinton is able to recover my wallet

**Comment by hkirat** [comment]
nvm all good on my machine after a re-build as well
