### ISSUE TITLE
anchor.utils.rpc undefined triggers onError in import accounts component

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#345]
Not sure how but during testing I got an `getMultipleAccounts` does not exist on undefined error here https://github.com/coral-xyz/backpack/blob/fee1567efae4039bbc2f4d2884abf19d353fb8d2/packages/app-extension/src/components/Account/ImportAccounts.tsx#L98

This can be confusing in the case of ledger being used because it calls this https://github.com/coral-xyz/backpack/blob/fee1567efae4039bbc2f4d2884abf19d353fb8d2/packages/app-extension/src/components/Account/ImportAccounts.tsx#L109 and it'll bounce back a screen saying ledger can't connect.

Can't reliably reproduce so it might be a dev only issue.

**Comment by armaniferrante** [comment]
Stale.
