### ISSUE TITLE
DMs should always have different username colors

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#3459]
Usernames are currently randomly assigned, but sometimes you can end up with the same color for sender and recipient in a DM. Should be a rule (only for DMs) that makes sure the two colors are unique for sender and receiver.

Example of them being the same

<img width="97" alt="Screenshot 2023-03-28 at 12 42 28 PM" src="https://user-images.githubusercontent.com/321395/228323990-e6713c8d-1d32-4d66-a5db-d3003bc37900.png">

**Comment by joeshajan** [comment]
Hey, @trucy So right now both the colors are the same. and this should not happen, right?

<img width="97" alt="228323990-e6713c8d-1d32-4d66-a5db-d3003bc37900" src="https://user-images.githubusercontent.com/69904519/228469601-f9e0789c-ed2b-4dfc-a488-084ced907072.png">

I would like to fix this. Can you assign this to me?

**Comment by trucy** [comment]
@joeshajan These colors are randomly assigned, but _sometimes_ they can end up being the same. There should be some rule that enforces them always being different in a 1-1 DM. Thanks!

**Comment by joeshajan** [comment]
Hey, @trucy can you please help me with this?

How can I troubleshoot my attempt to run Backpack locally, since the page I see in my Chrome extension is different from what is shown in the video? Also, how long should I expect to wait for an invite code after applying for one?


![Screenshot from 2023-04-01 10-53-44](https://user-images.githubusercontent.com/69904519/229267217-526395f1-259b-418e-a742-4189d65cebb1.png)

**Comment by Dharmavineta** [comment]
> joeshajan

same issue here. Applied for invite but the waiting room is whooping 19+k

**Comment by RashulChutani** [comment]
@trucy In order to fix the above issue, when both users have the same color, I have changed the `colorIndex` of user_2 to be 1 + `colorIndex` of user_1. Does that look fine, or should I change the colors to random values? Thanks.

**Comment by hkirat** [comment]
This invite code should work for everyone - 382aa33a-a4eb-4c77-a196-ff29cc675c27

**Comment by joeshajan** [comment]
Thanks @hkirat
