### ISSUE TITLE
Apply title case to fields in tx metadata

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#3460]
apply this to labels in tx metadata

text-transform: capitalize;

For example, the p should be P in "You paid"

<img width="367" alt="Screenshot 2023-03-28 at 1 24 02 PM" src="https://user-images.githubusercontent.com/321395/228332642-9e733dff-cf67-4b00-b410-0d07770dfc4c.png">

**Comment by psavan1655** [comment]
Hey, I would like to work on this issue. As it looks pretty straight forward. And this is my first contribution to Backpack. So i guess it's a good issue to contribute and understand backpack's process.
Thanks

**Comment by yashsolanki22** [comment]
hey guys! I would like to work on this issue. Let me know if this hasn't already been fixed. Thanks!

**Comment by trucy** [comment]
just going in order of comments here, @psavan1655 sounds good, go for it!

**Comment by MohitBansal321** [comment]
Hey I just resolve the issue @trucy

**Comment by HemanthPaila** [comment]
Hi there,

I want to contribute to this project and take on this issue as my first task. Could you please assign it to me? I am excited to work towards resolving it and will keep the team updated on my progress.

Thanks!

**Comment by psavan1655** [comment]
@trucy i have applied for invite code, but haven't got any updates yet. Let me know if i can do anything to speed up the invite code process?

**Comment by wentokay** [comment]
@psavan1655 I think someone else jumped in but maybe [there's another issue](https://github.com/coral-xyz/backpack/labels/good%20first%20issue) you can look at if you'd like to contribute (thanks for your interest in helping out!), you can use this invite code `e7aa9a30-b87a-4151-bb33-9c11cece1893`

**Comment by MohitBansal321** [comment]
> @wentokay 😄 yeah, it's ok. i'll pick another one. You can assign this issue to @MohitBansal321 Thanks for the invite code

thank you @psavan1655
