### ISSUE TITLE
Enhancements to Minted NFT view

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#3461]
Updated these designs with more clear instructions in [Figma](https://www.figma.com/file/HNF2HJZYq6dUzCWxSmH2Oe/Backpack-_-Questlog?node-id=21999%3A188657&t=lJwTsCtldjEWCgjW-1)

<img width="1218" alt="Screenshot 2023-03-28 at 2 38 17 PM" src="https://user-images.githubusercontent.com/321395/228348571-b37f7a24-0a17-4251-83c9-cee41235b09d.png">

**Comment by psavan1655** [comment]
@wentokay @trucy  Can you assign this issue to me. Pretty straight forward UI fix. with some good css will just do.
Would like to work on this issue.

**Comment by psavan1655** [comment]
@trucy  Can you help me to get to this page? To mint NFT as i am new to this

**Comment by psavan1655** [comment]
@wentokay Yeah definitely i will find my way through it , and also with optimal solution possible.

**Comment by trucy** [comment]
@psavan1655 path to this flow is:

1. Mint something (either in Backpack, or another site)

2. Click on this icon in top right
<img width="52" alt="Screenshot 2023-03-29 at 1 51 25 PM" src="https://user-images.githubusercontent.com/321395/228638953-6f4a1147-f0a8-4662-8389-66ed99afb0c9.png">

3. Click on an activity item where you minted an NFT
<img width="372" alt="Screenshot 2023-03-29 at 1 52 45 PM" src="https://user-images.githubusercontent.com/321395/228639236-fdfdfb6f-b40b-489f-9096-99118e2ce5f1.png">

**Comment by psavan1655** [comment]
@trucy 
1: Used solana/spl-token to mint locally to solana devnet.
2: Verified success also on solana explorer. 
3: It still doesn't show in backpack

**Comment by psavan1655** [comment]
When getting xnft from devnet.xnft.gg backpack just black out. Not able to achieve this scenario.
