### ISSUE TITLE
button not getting reset to "notify me"

### ISSUE THREAD

**Issue by mohitgadhavi1** [coral-xyz/backpack#3470]
![image](https://user-images.githubusercontent.com/37660846/228529013-d6d09390-0ae2-4ac8-946c-02d0ebdc8762.png)
![image](https://user-images.githubusercontent.com/37660846/228529070-5f72d17a-2023-4313-92f0-bb268f71b1f9.png)

on backpack website ,in newsletter, once submit you email and again when adding new text it is not reset back to notify me.

**Comment by GausPeerzade** [comment]
Hello there,
I would like to kindly request to be assigned the issue regarding the newsletter text not resetting back to "Notify me" after submitting an email. This would be my first issue, and I'm excited to help out with the project. Thank you!

**Comment by prashulkale** [comment]
I can fix the issue if you allow me to do the issue i will fix it

**Comment by mrb1nary** [comment]
https://user-images.githubusercontent.com/55779046/229494789-cca38dc3-2f67-45c8-a9c0-181df6aa862d.mp4



There you go, fixed it! 🎒
