### ISSUE TITLE
token name shows up as "undefined" in send flow

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#3484]
Steps to reproduce:
- Balances -> click on any token

Issue:
- Header displays "Send undefined" instead of "Send [SOL/USDC/`Token Name`]"

<img width="375" alt="Screenshot 2023-03-29 at 2 25 43 PM" src="https://user-images.githubusercontent.com/321395/228646719-9b2c3809-6052-4c3d-bac2-c627ba819109.png">

**Comment by adarshlilha** [comment]
@trucy I happened to dive into this bug and seems I found the fix (apologies for working on this without being assigned)
please find details below, I can submit a PR on team's approval :)

Steps to reproduce:
* Balances -> click on "Send" -> select a token -> header displays "Send undefined" (as in desc above)
* Balances -> select a token -> send -> header is correct (this is working)

bug - token name was not being pushed in `NavStackProvider` for `select-user` route

Snapshot:
<img width="369" alt="Screenshot 2023-03-30 at 03 06 46" src="https://user-images.githubusercontent.com/13575704/228673421-2f683384-0cfc-4016-ade7-b4282af4873e.png">

**Comment by trucy** [comment]
@adarshlilha all good, thanks for working on this! If it's ready to go feel free to submit a PR
