### ISSUE TITLE
Add xNFT icon to Applications tab and link to xnft.gg

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#3492]
Once xNFTs are installed, it's not easy to visit the library to browse and install apps.

We'd like to add the xNFT icon to the Applications tab and have it link to xnft.gg. This would always be the first icon, followed by other xNFTs someone has installed.

Text should say xNFT.gg followed by a space and [this glyph](https://rsms.me/inter/glyphs/?g=northEastArrow) 

On hover use our tooltip component that says "Browse xNFTs"

<img width="840" alt="Screenshot 2023-03-29 at 9 52 21 PM" src="https://user-images.githubusercontent.com/321395/228716063-b40efa87-24f2-45db-8603-9a4e048dea7e.png">

xNFT icon: https://www.xnft.gg/logo.svg

**Comment by bonysureliya** [comment]
Hey @trucy I am willing to work on this issue

**Comment by AnandKu07** [comment]
Hey @trucy   I want to work on this issue

**Comment by trucy** [comment]
@bonysureliya go for it!

**Comment by RakeshBC1** [comment]
Hi @trucy I am willing to work on this issue

**Comment by bonysureliya** [comment]
Hey I am done with setting up the project locally now i am trying to navigating to the applications within the extensions i have dragged the dev folder from app-extensions but its asking for creating account and it has some amount of waiting period

**Comment by bonysureliya** [comment]
Can someone help me on this

**Comment by trucy** [comment]
@adityabharadwaj198 Let's wait to show it (load them all at once). Thanks for asking!
