### ISSUE TITLE
Installing Birdeye xNFT causes xNFTs to stop loading

### ISSUE THREAD

**Issue by aj019** [coral-xyz/backpack#3500]
https://user-images.githubusercontent.com/7893859/228868977-6cb9ccb1-ca9f-4708-b6d2-92def5a5b748.mov

**Comment by aj019** [comment]
I dived deeper and found that when fetching xNFTs. The xNFT object for Birdeye doesn't have the xNFT key. Causing the app to crash. 

We can filter out such xNfts so that atleast other xNFTs are visible. 
If there is any other suggestion do let me know.

**Comment by callensm** [comment]
this is part of a larger problem of devnet xnfts being wonky with our SWR caching layer. the issue has been resolved on `master` and will be in the next published release.

**Comment by psavan1655** [comment]
Do i need to remove the extension and then load new dev folder of app-extension? to resolve the issue?
As event after getting the lastes code from master. Facing the error

**Comment by aj019** [comment]
You can go to https://devnet.xnft.gg/ connect your wallet. Uninstall the xNFT from the website. And that should solve the problem @psavan1655

**Comment by psavan1655** [comment]
Thanks @aj019 .
I am also facing one more issue. I am minting NFT. Transaction is shown in phantom Wallet. But backpack wallet doesn't show anything. Any idea?

**Comment by callensm** [comment]
> You can go to https://devnet.xnft.gg/ connect your wallet. Uninstall the xNFT from the website. And that should solve the problem @psavan1655

can i close this as resolved then?
