### ISSUE TITLE
Profile picture not updating in chat messages

### ISSUE THREAD

**Issue by aarongillett** [coral-xyz/backpack#3507]
The profile picture is correct in the header, but not in the chat bubbles:

<img width="487" alt="image" src="https://user-images.githubusercontent.com/4157473/228948057-097a4cb0-5fbf-4d66-900f-165f97fa600a.png">

**Comment by RashulChutani** [comment]
I will be happy to work on that.

**Comment by prashulkale** [comment]
i can fix it if you allow me to work on it

**Comment by callensm** [comment]
@aarongillett can't repro, could be a cache delay.

can you confirm this is still happening?

**Comment by RashulChutani** [comment]
![Same](https://user-images.githubusercontent.com/41239718/229145448-12b4cb41-fe23-4abb-a40e-77067d8c7e77.png)
Yeah, I also tried the same, by creating a new user and the Same happens with me.

**Comment by trucy** [comment]
@RashulChutani this is referring to users who have changed their pfp to an NFT. to test, you would have to do the following:

User 1: Change PFP to NFT_1
User 2: Message User 1, see if NFT_1 shows up
User 1: Change PFP to NFT_2
User 2: Go to DM with User 1, see if NFT_1 or NFT_2 shows up
