### ISSUE TITLE
"Error: no keyring for solana" error after recovering account with ethereum wallet

### ISSUE THREAD

**Issue by ph101pp** [coral-xyz/backpack#3529]
Repro (latest master): 

- Reset Backpack
- Recover account with username + ethereum secret key
- Try to recover Solana wallet with recovery phrase
- **Error: no keyring for solana**

**Comment by RashulChutani** [comment]
Hi @ph101pp, I would be happy to work on this issue, if possible. 😃

**Comment by RashulChutani** [comment]
When I click on the "Recover with Private Key" Button, I straight away get the following error: 
![image](https://user-images.githubusercontent.com/41239718/229265625-1d51c996-ae6b-4942-9b46-419cf2b136d6.png)

Do I need to set a flag from the backend to unlock the keyring store? Thanks.

**Comment by armaniferrante** [comment]
I think this is already done. Please re-open otherwise.

**Comment by armaniferrante** [comment]
Closed by 0335d9d63c32dc7a10739c2c89dc89c7347a5120.
