### ISSUE TITLE
Not an approved origin error when signing after reconnecting

### ISSUE THREAD

**Issue by mcintyre94** [coral-xyz/backpack#3555]
Repro with the wallet-adapter example app: https://solana-labs.github.io/wallet-adapter/example/

- Use any connect button to connect backpack
- Click eg sign message, verify it works correctly
- Disconnect then connect to backpack again
- Use any of the sign message/transaction buttons, you get an error:

```
VM368 react_devtools_backend.js:2655 WalletSignMessageError: https://solana-labs.github.io is not an approved origin
    at Je.He [as signMessage] (_app-cb484cb16f6d065c.js:74:470325)
    at async _app-cb484cb16f6d065c.js:74:476273 Je
```

**Comment by RashulChutani** [comment]
I will be happy to work on this issue. 😃
