### ISSUE TITLE
PFA: Getting this error on npm build (trying to clone and run app in my system)

### ISSUE THREAD

**Issue by theDheerajjha** [coral-xyz/backpack#3604]
<img width="665" alt="image" src="https://user-images.githubusercontent.com/52864945/229941089-9c937f85-2214-4616-a2b8-6742f7e2907f.png">

**Comment by richiebijoy** [comment]
The node_modules aren't installed on your system.

Run the following command to install them :- yarn install

**Comment by mrb1nary** [comment]
Try `yarn install` in the root directory then `yarn build` and finally `yarn start`

**Comment by Dhruv-Gajjar** [comment]
Hey @theDheerajjha don't use PowerShell I was having the same issue with PowerShell try using git bash instead it worked for me try doing the process from start on git bash

**Comment by theDheerajjha** [comment]
Can I use npm instead of yarn ??

**Comment by theDheerajjha** [comment]
I have tried all the things but no luck. would be thankful if anyone can connect and help me out. please send me Hello ( write4dheeraj@gmailcom)
@Dhruv-Gajjar

**Comment by armaniferrante** [comment]
Closing as we aren't prioritizing windows developer support at the moment.
