### ISSUE TITLE
Order friends on Send screen by ABC of username

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#3612]
Doing either of these things should take you to the same screen:

- Balances > Send > Choose token
- Balances > Choose token > Send

From there, friends should be ordered by ABC

<img width="376" alt="Screenshot 2023-04-05 at 11 04 47 AM" src="https://user-images.githubusercontent.com/321395/230139481-b5727ae6-4649-4c55-adfc-8570312150ff.png">

**Comment by Anubhav311** [comment]
isn't user already taken to the same screen in both the cases?

**Comment by trucy** [comment]
@Dhruv-Gajjar sweet thank you, just assigned
@Anubhav311 yes that's why i wrote "Doing either of these things should take you to the same screen"
