### ISSUE TITLE
allow notifications screen doesn't display on account recovery

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#3619]
It displays on account creation but not recovery, when it probably should.

<img width="528" alt="Screen Shot 2023-04-05 at 1 47 45 PM" src="https://user-images.githubusercontent.com/6990215/230176465-b5c081b7-6dfc-407c-8e82-700c0d125e97.png">

**Comment by richiebijoy** [comment]
Hi @armaniferrante ,

I wanted to let you know that I haven't yet had the opportunity to make any open source contributions. However, if you were to assign me this task, I would be excited to take on the challenge and make it my first contribution.

Thank you!

**Comment by palanivenkatesh** [comment]
https://github.com/coral-xyz/backpack/pull/3625

**Comment by armaniferrante** [comment]
Closed by https://github.com/coral-xyz/backpack/pull/3625.
