### ISSUE TITLE
PFA: getting error on yarn build

### ISSUE THREAD

**Issue by theDheerajjha** [coral-xyz/backpack#3623]
<img width="627" alt="image" src="https://user-images.githubusercontent.com/52864945/230222853-172dc0c3-cd7b-4e53-a249-ba6b6ddd5053.png">

**Comment by Merdi-kim** [comment]
Did you install the dependencies first?

**Comment by freddyal0x01** [comment]
I'm getting the same issue when I run `yarn build` `ERROR: command finished with error: command (/Users/freddyal/Documents/backpack/packages/app-extension) yarn run build exited (1)
command (/Users/freddyal/Documents/backpack/packages/app-extension) yarn run build exited (1)`

**Comment by akhilsingh-git** [comment]
Same issue here i tried upgrading the versions (node Js & yarn) as well Sometimes the error came to change the aysnc function in index.js?
![yarn-build-fail](https://user-images.githubusercontent.com/35478226/230280932-c0e977e1-122f-4eb7-8584-9c9ce84305a3.PNG)

**Comment by freddyal0x01** [comment]
What version of yarn and nodejs are you on? I'm on a Mac m1 fwiw

**Comment by theDheerajjha** [comment]
I am using windows and have installed latest Yarn version

**Comment by theDheerajjha** [comment]
Latest node version as well.

**Comment by Anubhav311** [comment]
did you try `yarn build --force`

**Comment by freddyal0x01** [comment]
I'm still getting yarn build exiting issues when I do did the above^.

**Comment by akhilsingh-git** [comment]
the build is working with --force, but yarn start is having issues

**Comment by yatharth1706** [comment]
try running it with yarn build --no-daemon. It will work i guess

**Comment by theDheerajjha** [comment]
Anyone here with successful installation on window please??

**Comment by yatharth1706** [comment]
> Anyone here with successful installation on window 11 please??

I was able to setup this project yesterday on windows 11. Followed all the steps which are mentioned in the contributing doc. I only faced one issue in both yarn build and yarn start. Some issue related to turbo daemon.

For that i used yarn build --no-daemon and yarn start --no-daemon.

Both commands took around 40-50 minutes in my pc.

**Comment by armaniferrante** [comment]
Going to close this to keep internal issue tracking clean since we aren't prioritizing support for a windows developer environment right now.
