### ISSUE TITLE
Messages search results do not always show the exact match first

### ISSUE THREAD

**Issue by monk-doesnt** [coral-xyz/backpack#3632]
<img width="384" alt="Screenshot 2023-04-06 at 5 07 28 PM" src="https://user-images.githubusercontent.com/104650166/230502697-be50c1f9-5782-4189-91ab-2efe75409c69.png">
<img width="385" alt="Screenshot 2023-04-06 at 5 07 20 PM" src="https://user-images.githubusercontent.com/104650166/230502699-d915dabb-2d49-4cc3-85fa-c3aee8c707dd.png">

**Comment by Merdi-kim** [comment]
I would want to investigate this further and see what that could potentially be. Can I be assigned this task ?

**Comment by wentokay** [comment]
will be fixed in #3641

**Comment by wentokay** [comment]
fix now live (via #3646)
