### ISSUE TITLE
Backpack all chat does not load on the user's first session.

### ISSUE THREAD

**Issue by monk-doesnt** [coral-xyz/backpack#3633]
Closing and opening Backpack brings up the chat.

https://user-images.githubusercontent.com/104650166/230502846-e69242f8-cb4f-46b2-8094-8c7a4e572420.mov

**Comment by Merdi-kim** [comment]
Wouldn't this be because of the internet connection? I have tried a couple time but it seems to work well for me on all trials

**Comment by monk-doesnt** [comment]
This only occurs on the very first session post-onboarding.

**Comment by Merdi-kim** [comment]
New user onboarding or new wallet onboarding?
