### ISSUE TITLE
Add support for experimental encryption feature

### ISSUE THREAD

**Issue by valentinmadrid** [coral-xyz/backpack#3644]
The Solana Wallet Standard has an experimental encryption feature. It would be amazing to have it implemented into the dev backpack build for example.
A reference implementation to perform asymmetric encryption with Solana Keypairs using Tweetnacl integrated into the Wallet Standard can be found here: https://github.com/wallet-standard/wallet-standard/blob/3823c3c25d2c3fa83fcfd43d9779ed1921fd881e/packages/example/wallets/src/solanaWallet.ts#LL235C1-L277C7

I can't seem to exhaust all the use cases where encryption would be needed and I would love to see Backpack taking the lead on this.

**Comment by valentinmadrid** [comment]
Update on this: Jordan Sexton and I agreed on a standard for the derivation of an encryption keypair inside the encryption feature. I'm going to link the reference implementation and begin to make a PR in the upcoming days.

**Comment by Nitishupkr** [comment]
can i work on this issue

**Comment by valentinmadrid** [comment]
> can i work on this issue

Let me know if you need any help. Also check out the sRFC #7 on the Solana forums expanding on this topic. 
Such a contribution would have a high value to the ecosystem.
@Nitishupkr

**Comment by Nitishupkr** [comment]
ok thank you
