### ISSUE TITLE
Regression with backpack usernames showing up for send list and send view

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#3645]
Steps to reproduce for send list:

1. Click Send from Balances tab
2. Select token
3. Enter username or address of someone you're not friends with on Backpack
4. "Other people" section returns empty array/list instead of avatars and username matches

Send view:

1. Click Send from Balances tab
2. Select token
3. Enter exact address of someone on Backpack
4. On the next screen, only the wallet address shows up, when it should be their username

**Comment by wentokay** [comment]
I'll fix this as I think my PR introduced it, it's related to the api serving variations of snake_case and camelCase data

**Comment by wentokay** [comment]
i.e. the api is currently returning

```
"public_keys": [{
	"blockchain": "solana",
	"public_key": "aaa...aaa",
	"primary": true
}]
```

but it needs to be

```
"public_keys": [{
	"blockchain": "solana",
	"publicKey": "aaaa...aaa",
	"primary": true
}]
```
