### ISSUE TITLE
Looping when trying to unlock the wallet

### ISSUE THREAD

**Issue by Harsh97x** [coral-xyz/backpack#3704]
after entering the correct credentials and pressing the unlock button. The transition happens but it shows the unlock screen once again.
![image](https://user-images.githubusercontent.com/71343199/232286848-4cb12551-e73a-431a-8cb3-32e597a930b1.png)

**Comment by Merdi-kim** [comment]
I want to reproduce this issue. Can you give more context on how I can reproduce this? Because on my side everything seems to work perfectly

**Comment by Harsh97x** [comment]
I think something is wrong with brave. the issue is fixed now. thanks for looking into it.

**Comment by wentokay** [comment]
@Harsh97x I've noticed this issue come up a few times but haven't been able to reproduce it yet.

Can you share any details about what you did that you think might've fixed it? It would be much appreciated.

**Comment by Harsh97x** [comment]
I disabled the extension and then started it again. It started working fine.

**Comment by wentokay** [comment]
good to know, thanks!
