### ISSUE TITLE
PFP not updating everywhere.

### ISSUE THREAD

**Issue by aarongillett** [coral-xyz/backpack#3722]
PFP correctly updates in account switcher header, but not in message chat or friend search lists (seems to be the smaller thumbnail version)

Correct
<img width="373" alt="image" src="https://user-images.githubusercontent.com/4157473/232883315-e7b34f59-60fa-4dd7-8185-54411d053e3b.png">

1. Incorrect (@aaron)
<img width="372" alt="image" src="https://user-images.githubusercontent.com/4157473/232883430-ad4d45de-507c-4386-a409-3e81e0e6a369.png">

2. Incorrect
<img width="487" alt="image" src="https://user-images.githubusercontent.com/4157473/232884357-a437cae9-8049-4d5f-a1ed-a00c587926ab.png">

3. Incorrect
<img width="487" alt="image" src="https://user-images.githubusercontent.com/4157473/232884741-750b4921-0c4c-49d0-b12c-a3ad2dc5a71f.png">

**Comment by adarshlilha** [comment]
@aarongillett I would like to take this up, TIA

**Comment by Tanishq-Gupta** [comment]
There's been no update from @adarshlilha for more than 2 weeks. Can i take this up? @aarongillett

**Comment by Tanishq-Gupta** [comment]
Hi @aarongillett ,
Can I take this up?

**Comment by skushagra9** [comment]
Hey , I want to work on this issue  ,please assign me

**Comment by armaniferrante** [comment]
No longer a valid issue.

**Comment by skushagra9** [comment]
Hey @armaniferrante Please tell me any issue you want to be solved, and would be helpful for the team
