### ISSUE TITLE
show error message when rate limited by backend

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#3726]
Right now we don't do anything and the components don't load

**Comment by RashulChutani** [comment]
Hi @armaniferrante, I will be more than happy to help with this. Thanks.

**Comment by Rakeshrockz** [comment]
@armaniferrante What's the rate limiting threshold: Define the threshold that triggers rate limiting, such as a maximum number of requests within a certain time frame. And which method of rate limiting is used in backpack, Also do we need to consider error message like below.
Error Message:

Error 429 - Too Many Requests

We're sorry, but you've exceeded the maximum number of requests allowed by our system. Please try again in a few minutes.

???????
