### ISSUE TITLE
Message button in chat screen doesn't seems to do anything if its just a message to be displayed this shouldn't be a button.

### ISSUE THREAD

**Issue by MohitMandalia** [coral-xyz/backpack#3729]
### Message button in chat screen doesn't seems to do anything if its just a message to be displayed this shouldn't be a button.

Could I get some design inputs here to make correction if this is not intentional.

<img width="369" alt="Screenshot 2023-04-19 at 7 32 56 PM" src="https://user-images.githubusercontent.com/36087806/233100396-52f67420-c6e6-47a4-9a39-0a5d1651a692.png">

Happy to take this up.

**Comment by aarongillett** [comment]
Agreed; this shouldn’t be a button. Thanks for spotting this. Let’s remove the button fill and just keep the icon as a non-interactive illustration, like so:

<img width="487" alt="image" src="https://user-images.githubusercontent.com/4157473/233166959-706fc736-7977-4ea3-970b-a5c04b5c7039.png">
