### ISSUE TITLE
Friend Request issue.

### ISSUE THREAD

**Issue by MohitMandalia** [coral-xyz/backpack#3732]
### Steps to reproduce
- Assume you have a friend request, Open friend request section -> Request -> tap on User -> Open Message
- In the Chat section click on `Accept friend Request` you will see a popup `You and user are connect` but in the chat screen it says `Friend Requested` and on the dot menu it will have option to `Cancel Friend Request`

<table>
<tr>

<td>
<img width="380" alt="Screenshot 2023-04-19 at 9 05 20 PM" src="https://user-images.githubusercontent.com/36087806/233127406-e61b55f2-74d6-42dc-9866-04f23cb40608.png">
</td>

<td>
<img width="377" alt="Screenshot 2023-04-19 at 9 05 29 PM" src="https://user-images.githubusercontent.com/36087806/233127560-7b2c0bed-9018-472d-9730-9071e3dcdb18.png">
</td>

<td>
<img width="379" alt="Screenshot 2023-04-19 at 9 05 45 PM" src="https://user-images.githubusercontent.com/36087806/233127604-48fc0c42-9837-4830-9a73-1d8834bf5c12.png">
</td>

</tr>
</table>

- Same goes for this screen when you click on a user, the next screen should have `Accept` and not `Request to Add Friends`

- **Update**: Just found the below issue reported [here]( https://github.com/coral-xyz/backpack/issues/3505)

<table>
<tr>

<td>
<img width="372" alt="Screenshot 2023-04-19 at 9 27 30 PM" src="https://user-images.githubusercontent.com/36087806/233133321-87ebef60-b4a1-48a6-a5f1-d37f03648a10.png">
</td>

<td>
<img width="377" alt="Screenshot 2023-04-19 at 9 27 40 PM" src="https://user-images.githubusercontent.com/36087806/233133391-db7352f3-d20f-4b9a-b434-e31fd47e6720.png">
</td>

</td>

</tr>
</table>

Happy to take this up.

**Comment by aarongillett** [comment]
Thanks @MohitMandalia. Have checked with the other contributor of [3505](https://github.com/coral-xyz/backpack/issues/3505) so if they’re unable to contribute you’re welcome to.

**Comment by RashulChutani** [comment]
Hi @aarongillett, I have resolved this issue in the PR created for issue #2522. Here is the link; https://github.com/coral-xyz/backpack/pull/3659
