### ISSUE TITLE
Cache avatar on lock screen

### ISSUE THREAD

**Issue by aarongillett** [coral-xyz/backpack#3733]
It usually takes around ~1s to load the avatar. Would be great to cache this.

https://user-images.githubusercontent.com/4157473/233162140-c8a7e6e9-54a9-4a83-b98d-5e314a6d9f29.mov

**Comment by aarongillett** [comment]
Go for it. Thanks @atulya2109 !

**Comment by wentokay** [comment]
hey @atulya2109 we've been doing an overhaul in the backend around the way we serve and cache avatars and this issue will get addressed by these changes so I'll pick this up for now, but thanks for offering to help 🙏

**Comment by atulya2109** [comment]
Sure @wentokay, no problem.
