### ISSUE TITLE
It’s not possible to reply to a message that has an image attached.

### ISSUE THREAD

**Issue by aarongillett** [coral-xyz/backpack#3738]
Suggestion
- add the reply button to the right of the image (similar position to other reply buttons next to messages)
- move the trash button to underneath the reply button.

<img width="487" alt="image" src="https://user-images.githubusercontent.com/4157473/233228327-cacf08bd-d08b-4d7a-b3da-ed60bcfe49ac.png">

**Comment by MohitMandalia** [comment]
Happy to take this up

**Comment by aarongillett** [comment]
Thanks @MohitMandalia !

**Comment by MohitMandalia** [comment]
How to you want the preview of the parent message to look while replying to image?

**Comment by MohitMandalia** [comment]
Also how do you want to handle the `delete button` scenario as for message type `media/image/gif` the `delete icon` will be underneath `reply` button and for message type `text` the delete icon displays on the right side of `reply` I know the delete icon will not be displayed to all the users but still something to think for.

**Comment by MohitMandalia** [comment]
Do we want to support gif reply as this will already support image reply

**Comment by MohitMandalia** [comment]
@aarongillett want some inputs here
Thanks

**Comment by aarongillett** [comment]
Apologies for the late reply @MohitMandalia. This is what we could do for images replies.

Yes, we should support gif replies too.

Stickers are a new feature on the latest build, so we should support replies from them as well. They should work in the same way.

As per the mockup, there should be plenty of room to position the reply and delete button next to each other.

Let me know if you have any other queries. Thanks!

![image](https://user-images.githubusercontent.com/4157473/235264332-df3b854d-9d41-496a-82be-9be2f917323a.png)

**Comment by Dhruwang** [comment]
@MohitMandalia are you still working on this issue ?

**Comment by MohitMandalia** [comment]
Yup working on it.
