### ISSUE TITLE
Broken search result view

### ISSUE THREAD

**Issue by MohitMandalia** [coral-xyz/backpack#3739]
## Issue
- The search result view breaks when the search text is too long.

## Suggestions
- Should we only allow 15 char as the username won't be long enough or add `...` if search exceeds certain char limit what do you think?
  
<img width="378" alt="Screenshot 2023-04-20 at 6 29 23 AM" src="https://user-images.githubusercontent.com/36087806/233230937-fd2915bd-8a57-440f-a144-b67a976bc5f3.png">

Happy to work on this.

**Comment by aarongillett** [comment]
Thanks for spotting this. I’d suggest we add an ellipsis `…` to truncate the result (this is what Google does).

**Comment by psugandhraj123** [comment]
Hyy @MohitMandalia. Are you still working on this. If not I can take this up.

**Comment by MohitMandalia** [comment]
Yup I am already on it.
