### ISSUE TITLE
Back button doesn't follow the backstack

### ISSUE THREAD

**Issue by MohitMandalia** [coral-xyz/backpack#3740]
## Issue
- After following the flow in the video, you can see the `back button` directly comes back to `Message` screen instead of `Friends screen` which was the previous screen, this seems a bit weird.

## Suggestion
- If this is not intentional then `Back Button` should follow the navigation backstack.

## Video

https://user-images.githubusercontent.com/36087806/233233589-7520b174-d947-4eea-9e99-f570606e825a.mov

Happy to work on it if this behaviour needs a fix

**Comment by KhushPatibandha** [comment]
I do like to work on this.

**Comment by KhushPatibandha** [comment]
Hey @MohitMandalia, for the past 2 hrs I am trying to find the file to make a change in. Would really appreciate if you can help me out with that.

**Comment by KhushPatibandha** [comment]
do I have to make a change in packages/chat-sdk/src/components/ChatRoom.tsx ?

**Comment by KhushPatibandha** [comment]
No problem 👍
