### ISSUE TITLE
small readme improvement for onboarding 

### ISSUE THREAD

**Issue by Merdi-kim** [coral-xyz/backpack#3741]
I spotted that in the readme, under the _environment variables_ it says **rename .env.example to .env** yet in the codebase we have **.env.sample**. I found this a little bit misleading, especially for newbies. I'd like to change that to the right naming

**Comment by KhushPatibandha** [comment]
would like to take this up!

**Comment by Merdi-kim** [comment]
Oh, thanks @atulya2109. I did not see that PR. Thanks for pointing it out

**Comment by atulya2109** [comment]
No problem @Merdi-kim
