### ISSUE TITLE
Update UI after user has started typing password after typing wrong password

### ISSUE THREAD

**Issue by Merdi-kim** [coral-xyz/backpack#3744]
It would be a nice pattern if the red border disappeared when the user tries to type in a new password after a wrong password. Leaving the red border visible might mean that what they are typing is still wrong, which is slightly misleading. I would be happy to solve that issue 

https://user-images.githubusercontent.com/70149872/233322918-1acd39bf-9037-440f-af20-b92b8e99d2f9.mp4

**Comment by KhushPatibandha** [comment]
I would like to contribute to this one

**Comment by Abhinavcode13** [comment]
Can you assign me this issue please @Merdi-kim ?

**Comment by KhushPatibandha** [comment]
This issue is fixed. @Merdi-kim
