### ISSUE TITLE
put coingecko behind a proxy

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#3752]

**Comment by MohitMandalia** [comment]
what would be the proxy url?

**Comment by Abhishek-90** [comment]
Can you share more details about this @armaniferrante , like proxy URL and other data that needs to be passed?

**Comment by Rakeshrockz** [comment]
@armaniferrante We have to choose a reliable proxy server that we can use to access Coingecko. We have to use either a free or paid proxy server, Also if already choosen one them is it fast and secure, we need more details on these.
