### ISSUE TITLE
collection level holders chat flashes and disappears after refresh

### ISSUE THREAD

**Issue by monk-doesnt** [coral-xyz/backpack#3762]
https://user-images.githubusercontent.com/104650166/233796854-ed57f8e9-da1a-4c1e-8cc8-a4ed632f1941.mov

**Comment by aarongillett** [comment]
Also not seeing chat icons at all.
![image](https://user-images.githubusercontent.com/4157473/234371641-0d16f6ac-1d60-4ff3-b843-25a4374670b3.png)
