### ISSUE TITLE
add more info button to xnfts

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#3763]
Right now it's hard to discover the right click -> menu to get into the details flow.

**Comment by trucy** [comment]
Can we change the chat icon to a "more" icon and use the dropdown to display View, Chat and Send? Right click is not intuitive at this point as we don't use it many places in the app.

<img width="539" alt="Screenshot 2023-04-23 at 10 31 47 AM" src="https://user-images.githubusercontent.com/321395/233849107-78490792-229b-4c4b-9225-e06960c00ea5.png">

**Comment by trucy** [comment]
Since more people are going to be looking to copy the pfp and use it rather than use the xNFT or chat we can also do this:
1. Make main click go to view details
2. Replace chat icon with a ••• that brings up a dropdown/overlay
3. Move view xNFT to the ••• menu
