### ISSUE TITLE
If a user has already joined a chat let him know.

### ISSUE THREAD

**Issue by jim4067** [coral-xyz/backpack#3770]
When looking at an NFT, if I have joined a chat, the `join chat` button should reflect this e.g `already joined` or disabled it.

![image](https://user-images.githubusercontent.com/30603522/234099479-6e618ae7-c447-41b1-a094-d0eac82f313e.png)

**Comment by jim4067** [comment]
The same goes for the chat button when viewing all NFTs.

![image](https://user-images.githubusercontent.com/30603522/234099934-f73ba7f3-9b34-45dd-bedb-928355dea2f5.png)

**Comment by shohan2001** [comment]
Can someone please assign me this issue
