### ISSUE TITLE
Allow user to toggle display off for Prices xNFT

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#3773]
<img width="375" alt="Screenshot 2023-04-24 at 4 43 15 PM" src="https://user-images.githubusercontent.com/321395/234123445-34ae963c-e7d4-4ab3-a3a6-77b1311565d1.png">

**Comment by rushikeshadhav** [comment]
Hey can I take this up?

**Comment by Dhruwang** [comment]
Should the display toggle button work only for Prices xNFT or for all ?
