### ISSUE TITLE
Update Collectibles empty state to include multiple marketplaces

### ISSUE THREAD

**Issue by aarongillett** [coral-xyz/backpack#3776]
### UI
![image](https://user-images.githubusercontent.com/4157473/234124879-4627e271-b515-4694-acca-8e565d085d0c.png)

### Icon
Interests Rounded
https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Ainterests%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048

### Assets
![tensor](https://user-images.githubusercontent.com/4157473/234128675-93bdc1f3-600d-49dd-bd88-a9d835983387.svg)
![magic_eden](https://user-images.githubusercontent.com/4157473/234127390-0e9f3789-987c-4e33-a45a-5c77ea0da398.svg)
![hyperspace](https://user-images.githubusercontent.com/4157473/234127129-dc0433d0-2517-4db3-80cc-7b182d968930.svg)
![blur](https://user-images.githubusercontent.com/4157473/234127231-eef518c2-65de-4ace-ae49-ab5efa810ead.jpg)
![opensea](https://user-images.githubusercontent.com/4157473/234127234-81da6e04-9b6d-4123-a327-bb020577e9b8.svg)

### Links
https://www.tensor.trade
https://magiceden.io
https://hyperspace.xyz
https://blur.io
https://opensea.io

**Comment by Merdi-kim** [comment]
@aarongillett I would like to work on this issue, can I?

**Comment by aarongillett** [comment]
Sure thing, thanks @Merdi-kim !

**Comment by ritvij14** [comment]
@aarongillett can I work on this issue? If yes, just to confirm, on the empty screen I will have to add this so that people can go to those platforms for collectibles, correct?
