### ISSUE TITLE
Join Chat button does not open chat. Many Mad Lads are unable to access holders chat.

### ISSUE THREAD

**Issue by monk-doesnt** [coral-xyz/backpack#3779]
<img width="250" alt="Screenshot 2023-04-25 at 12 41 35 AM" src="https://user-images.githubusercontent.com/104650166/234184357-1eda2e7f-2034-48df-b06a-3f67a3732732.png">

**Comment by monk-doesnt** [comment]
This means that users who did not mint and bought a Mad Lad on secondary are unable to access the holders chat.

**Comment by kevinfaveri** [comment]
+1, also clicking on my Madlad NFT on the king grid minigame does nothing (I'm on Brave)

**Comment by kevinfaveri** [comment]
Hmm. I think this is because of the xNFT specifically, but if you right click it shoudl show you the option to go item details page > chat

Anyway, this PR should improve your UX: https://github.com/coral-xyz/backpack/pull/3790
