### ISSUE TITLE
Add right click option for xNFTs

### ISSUE THREAD

**Issue by jim4067** [coral-xyz/backpack#3782]
Not sure whether this exists but, when viewing xNFTS in the xNFTs tab, there should be a right-click option/menu to enable user's quickly got into the settings page for an xNFT.

The current behaviour is to go to `settings -> xNFTs -> specific xnft to view it's settings`

**Comment by kevinfaveri** [comment]
To go to the details page? You can already right click on individual nfts already
<img width="366" alt="Screenshot 2023-04-25 at 17 35 27" src="https://user-images.githubusercontent.com/18222497/234328838-b6a2c262-6134-4518-94c9-d994eab13b43.png">

**Comment by jim4067** [comment]
thanks 👍🏾 

edited with the correct question. I was talking about opening an xNFT's menu by right-clicking on it, with an option to go to its settings page.
