### ISSUE TITLE
[BUG] Resetting pfp to default pixel avatar doesn't work

### ISSUE THREAD

**Issue by jim4067** [coral-xyz/backpack#3799]
PFP nft not being removed. 

As a feature request, I would love to have the option to remove the PFP and return to the default ones provided by backpack.

**Comment by trucy** [comment]
@jim4067 you should! In the same place where you set your PFP (Settings, click on avatar)

Hover on the PFP to reveal a trash can icon then click "Update" The fact that this doesn't happen is actually a bug, thanks for finding it
