### ISSUE TITLE
Show network status on lock screen if no connection

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#3808]
If you're disconnected, Backpack doesn't let you log in but we should show that it's a network rather than extension error

Proposed:
- Remove the border that shows up around an empty pfp
- Disable the input and button since you can't do anything anyway
- (optional, lmk what you think) Add a tooltip that says "You'll need Internet to use Backpack" when hovering on disabled elements
- Add the same banner we use in messaging for the same state (ref: #1924 )

<img width="822" alt="Screenshot 2023-04-26 at 3 48 36 PM" src="https://user-images.githubusercontent.com/321395/234698969-aff649b8-4f5a-42a6-856d-d2625315d501.png">

**Comment by manishhansal** [comment]
@trucy Could you please assign this issue to me? I want to work on this issue.

**Comment by trucy** [comment]
@manishhansal thank you, assigned

**Comment by trucy** [comment]
@jim4067 thanks! Yeah we should really show it once you're logged in as well, just made a note on the other ticket
