### ISSUE TITLE
After PFP is updated, show toast

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#3809]
Bug: This toast doesn't come up at all
Enhancement: having 2 different types of message

Show new avatar in the toast message, and change the message based on what pfp it is.

1) Default Pixel: "This one’s a classic 🤌"
2) NFT: "Looking good!"

<img width="1097" alt="Screenshot 2023-04-26 at 4 52 21 PM" src="https://user-images.githubusercontent.com/321395/234711093-d6072e89-c4fa-408b-8a67-09e686320bd4.png">

**Comment by rushikeshadhav** [comment]
Hey can I take this up?
