### ISSUE TITLE
pfp squished in backpack chat info drawer

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#3810]
<img width="287" alt="Screenshot 2023-04-26 at 5 39 57 PM" src="https://user-images.githubusercontent.com/321395/234718043-7f3804a3-a2d7-4cb1-9e9c-a82e8f8ae161.png">

**Comment by mrb1nary** [comment]
![image](https://user-images.githubusercontent.com/55779046/234766362-ebc7bac2-7a49-4894-8bd6-b7fd11fdd387.png)

I guess someone already fixed the issue! Can't reproduce it in the latest production build.

**Comment by kevinfaveri** [comment]
Maybe just happens with those set with a madlad which has height > width
prob need fixed width / height and image background style to be something like "cover"
