### ISSUE TITLE
Use higher-quality avatar image on lock screen

### ISSUE THREAD

**Issue by aarongillett** [coral-xyz/backpack#3812]
The lock screen avatar is low quality (120x120px) and pixelated on retina.

Suggestion: use a `@2x` asset for HQ screens.

Related: [Cache avatar on lock screen #3733](https://github.com/coral-xyz/backpack/issues/3733)

<img width="375" alt="image" src="https://user-images.githubusercontent.com/4157473/234831691-d2c50656-6545-4127-8b98-b2d890395b80.png">

**Comment by Abhijit20112003** [comment]
@wentokay I just create a PR

**Comment by wentokay** [comment]
now fixed, longer term changes including [faster loading](https://github.com/coral-xyz/backpack/issues/3733) coming soon
