### ISSUE TITLE
Remove right click from NFTs and Collections

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#3815]
Now that we have the more info icon, we don't really need the right click menu since the options are the same

![OMSthiydcE](https://user-images.githubusercontent.com/321395/234916650-35dfdd47-d00c-4618-ad34-5707f78aed18.gif)

**Comment by atulya2109** [comment]
Hi @trucy, I can look into this.

**Comment by Nitishupkr** [comment]
can i work on this
