### ISSUE TITLE
Add set as PFP and Burn to more info dropdown options in Collectibles tab view

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#3816]
Current "more info" actions on an NFT:
- View
- Send

We should add set as pfp and burn so the list becomes:
- View
- Send
- Set as PFP
--------
- Burn

<img width="191" alt="Screenshot 2023-04-27 at 10 50 32 AM" src="https://user-images.githubusercontent.com/321395/234917170-a91fd2a6-05ae-40ea-b69b-52133feed0a7.png">

**Comment by Merdi-kim** [comment]
I want to try and fix this but unfortunately, I do not have NFTs on my wallet. @trucy is there any place where I can mint some testing NFTs so that I can take on this issue and fix it

**Comment by Rakeshrockz** [comment]
@trucy do we need to design confirmation dialogs that appear when a user clicks on the "Burn" button, to ensure that the user understands the implications of the action they are about to take.

**Comment by Rakeshrockz** [comment]
@trucy We need to ensure that UI is responsive and works well on a variety of screen sizes, since users may be accessing the platform or marketplace on different types of devices. Do need to consider above as well?
