### ISSUE TITLE
Error when clicking on Messages/+ icon/sticker icon

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#3817]
<img width="374" alt="Screenshot 2023-04-27 at 10 42 31 AM" src="https://user-images.githubusercontent.com/321395/234918045-80300f0d-7273-46dc-a612-c50a00027b07.png">

**Comment by aarongillett** [comment]
I’m on Solana and can reproduce this @hkirat .
<img width="1543" alt="image" src="https://user-images.githubusercontent.com/4157473/235226629-f6c39981-d172-4da4-be1b-910a8017c1b7.png">

**Comment by trucy** [comment]
Note: after I said stickers worked, I got the same errors again. So something inconsistent and unrelated to switching networks
