### ISSUE TITLE
Add more options to collectible context menus

### ISSUE THREAD

**Issue by aarongillett** [coral-xyz/backpack#3818]
### Collectible Collectible View
Proposed menu:

- Open xNFT
- View
- Set as PFP
- Chat
- Send

<img width="487" alt="image" src="https://user-images.githubusercontent.com/4157473/234917330-c907b5b4-def6-4e3d-a487-a60d349250d3.png">

### Single Collectible View
Proposed menu:

- Set as PFP
- Download Image
- Copy Image
- View on Explorer
———————————
- Burn Token

<img width="487" alt="image" src="https://user-images.githubusercontent.com/4157473/234918668-ae1c62db-0977-414b-be1e-b7ad4d5b45aa.png">

**Comment by deepam-kapur** [comment]
@aarongillett, I would like to take this up.

**Comment by aarongillett** [comment]
Thanks @deepam-kapur ! Just assigned you.

**Comment by deepam-kapur** [comment]
Opened PR for the same. Let me know if any change is required! Thanks!!

**Comment by deepam-kapur** [comment]
@aarongillett have you got time to look into it?
