### ISSUE TITLE
app-extension: use metaplex collection standard

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#382]
Followup for https://github.com/coral-xyz/backpack/issues/273.

Right now we just do a match on the collection name. Instead, we should use the actual metaplex collection standard.

**Comment by Arrowana** [comment]
> 

It is an horrible mess. So the most canonical is a verified collections standard, but that allows to group NFTs, then you still need to know which collection is "authentic". Like DeGods and DeGods (fake) can be two different verified collection but have the same exact content, except the mint of the collection being "authentic" for the real degod.

For all non verified collections, it is rubbish work using the verified first creators (several sometimes) but sometimes not (hand minted sub collection with same creator for all).

**Comment by armaniferrante** [comment]
Related https://github.com/coral-xyz/backpack/issues/1362

**Comment by armaniferrante** [comment]
We should generally go through all the major collections and make sure they show up correct, e.g., #1362.

**Comment by armaniferrante** [comment]
Related https://github.com/coral-xyz/backpack/pull/1388
