### ISSUE TITLE
Unable to reply to most recent message

### ISSUE THREAD

**Issue by aarongillett** [coral-xyz/backpack#3821]
Hovering over the most recent message and trying to reply is buggy:

https://user-images.githubusercontent.com/4157473/234967896-e223ed67-d7ce-49dc-9610-ad5b83234f5e.mov

**Comment by Merdi-kim** [comment]
Can I fix this @aarongillett?

**Comment by aarongillett** [comment]
Closing this as it’s been fixed by #3848
