### ISSUE TITLE
No dark mode version for spam banner in chat

### ISSUE THREAD

**Issue by aarongillett** [coral-xyz/backpack#3823]
Correct dark mode styling likely exists in other banner components.

<img width="487" alt="image" src="https://user-images.githubusercontent.com/4157473/234979748-a83374cf-1a1a-43b9-add7-21f42d39a803.png">

**Comment by aarongillett** [comment]
The background color could be similar to `balanceChangeNegative: "rgb(233, 80, 80, .1)"` via [colors.tx](https://github.com/coral-xyz/backpack/blob/master/packages/themes/src/colors.ts)

<img width="487" alt="image" src="https://user-images.githubusercontent.com/4157473/234981289-fc608689-49c1-4bfd-ad72-8e333e397bff.png">

**Comment by MohitMandalia** [comment]
Can I pick this up?

**Comment by deepam-kapur** [comment]
@aarongillett, I would like to take this up.

**Comment by bharat2913** [comment]
Hey, @aarongillett 
Can I work on this?

**Comment by aarongillett** [comment]
Looks like there's already a PR out to fix this. Thanks everyone for offering to contribute, will close this if that gets merged.

**Comment by bharat2913** [comment]
okay, Thanks @aarongillett
