### ISSUE TITLE
Increase quality of profile picture on profiles

### ISSUE THREAD

**Issue by aarongillett** [coral-xyz/backpack#3846]
Profile images are pretty pixelated on my retina screen.
Suggestion: render a `@2x` asset for HQ displays.

<img width="487" alt="image" src="https://user-images.githubusercontent.com/4157473/235264999-cdc21eca-caf9-4267-a137-f1fb43ef254a.png">

**Comment by aarongillett** [comment]
Assigning @johnrees as you recently worked on avatars, but feel free to unassign yourself if you’re busy.

**Comment by aarongillett** [comment]
Assigning @wentokay as you recently worked on avatars, but feel free to unassign yourself if you’re busy.

**Comment by tnshgarg** [comment]
Hey @aarongillett @armaniferrante, I would like to pick this issue
