### ISSUE TITLE
Add support for video NFTs

### ISSUE THREAD

**Issue by aarongillett** [coral-xyz/backpack#3847]
It seems like we don’t have support for video NFTs at the moment.

e.g. this scam video NFT ([view on Explorer](https://solscan.io/token/55xCgQVajZ1MKMk6G5EEJYpJY85HJj9zKMCxACJHqSzL)) renders as a jpeg in Backpack

Best to probably test using a Clayno (I think you have one @armaniferrante?)

<img width="644" alt="image" src="https://user-images.githubusercontent.com/4157473/235266469-0574b746-d332-47aa-aed6-d769e619b625.png">

<img width="487" alt="image" src="https://user-images.githubusercontent.com/4157473/235266376-2b74ca99-4e5b-4f66-8615-0dde105ee267.png">

**Comment by jim4067** [comment]
I think this might be related to #1507 and 3d NFTs #1437.
