### ISSUE TITLE
Add `hide` feature for wallet amounts in`Balances` view

### ISSUE THREAD

**Issue by fluturecode** [coral-xyz/backpack#3852]
Allow users to hide wallet amounts when in `Balances` view, that way it is possible to screen share and record videos (i.e. tutorials) that do not expose your financials.

**Comment by manishhansal** [comment]
@armaniferrante  Please assign this issue to me. And it would be beneficial if you could explain the hide feature in detail, like the UI after hiding and the position of the hide button, etc.

**Comment by shohan2001** [comment]
@armaniferrante Can you please assign me this issue

**Comment by Rakeshrockz** [comment]
@armaniferrante Could you also consider Keyboard shortcut, users who prefer keyboard shortcuts, If you could add a shortcut that allows them to quickly toggle the display of wallet amounts on and off.

**Comment by itiwarishubham** [comment]
@armaniferrante could you please assign me this issue?. I would like to work on this and it will be mine first open source contribution
