### ISSUE TITLE
Edit copy on create username screen in onboarding

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#3858]
<img width="398" alt="Screenshot 2023-05-01 at 10 02 53 AM" src="https://user-images.githubusercontent.com/321395/235473160-cced95cb-1817-46c0-8dd5-a2c54372b33f.png">

On the create username screen it's not clear you need to remember your username to recover your account.

Suggestions: 
1. Add this to the top in bold: "Please save your username. You’ll need it to recover your account."
2. Move "Have fun!" to the previous paragraph to leave more whitespace

Designs (ignore the typo with "to to", should only be one "to"):

<img width="787" alt="Screenshot 2023-05-01 at 11 11 15 AM" src="https://user-images.githubusercontent.com/321395/235485202-71c495a3-1650-4a58-9a0e-9c52388d7497.png">

**Comment by karti16** [comment]
Hi, can I work on this issue?

**Comment by Rakeshrockz** [comment]
I would like to take up this, could you assign it to me please

**Comment by manishhansal** [comment]
@trucy Could you please assign this issue to me? I want to work on this issue.

**Comment by Soham-glitch** [comment]
is this issue resolved?

**Comment by ElizabethOgbee** [comment]
I would like to work on this project if it hasn't been assigned to anyone. Thanks
