### ISSUE TITLE
Stickers skeletons are squished

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#3873]
<img width="362" alt="Screen Shot 2023-05-02 at 10 40 29 AM" src="https://user-images.githubusercontent.com/6990215/235568001-77ecf104-d761-4af9-a115-3fdb93691e75.png">

**Comment by SaratAngajalaoffl** [comment]
Can I work on this?

**Comment by armaniferrante** [comment]
Go for it!

**Comment by hkirat** [comment]
Hi @SaratAngajalaoffl feel free to work on it but this might be worked on internally as well since it's a P1!
