### ISSUE TITLE
nft stickers show no nfts when there are indeed nfts

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#3874]
<img width="370" alt="Screen Shot 2023-05-02 at 10 44 48 AM" src="https://user-images.githubusercontent.com/6990215/235568535-eb118494-436a-49b7-9739-ac0f797a4bda.png">

**Comment by punithnayak** [comment]
hey @armaniferrante  can you assign it to me

**Comment by hkirat** [comment]
@armaniferrante can you check if you see your nfts in the NFT tab?
