### ISSUE TITLE
Dark mode only - Change border color on selected NFT in NFT drawer when changing pfp

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#3892]
1. In dark mode, when changing pfp, the selected NFT should have a white border (shown 2nd from left in screenshot), not black which is hard to see currently

<img width="377" alt="Screenshot 2023-05-03 at 1 12 29 PM" src="https://user-images.githubusercontent.com/321395/236007239-f042f0bc-3e87-4a9c-9278-b96b5dbb7d82.png">

**Comment by Dhruwang** [comment]
I would like to work on this !
