### ISSUE TITLE
Update success screens

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#3904]
[Figma](https://www.figma.com/file/HNF2HJZYq6dUzCWxSmH2Oe/Backpack-_-Questlog?node-id=22323%3A189310&t=lpPccC92vGDof3Vw-1)

Mostly just padding and icon swap if you've done the processing ones already

cc @peterpme

**Comment by sumitshinde-84** [comment]
Hi @trucy, I'm really interested in working on frontend-related tasks. Could you please assign me a project issue that aligns with my skills in frontend development? I'm excited to contribute to the team!
