### ISSUE TITLE
When uninstalling an xNFT, type and source are "unknown" in tx metadata

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#3906]
<img width="377" alt="Screenshot 2023-05-04 at 2 13 14 PM" src="https://user-images.githubusercontent.com/321395/236305732-ffe075d7-3e77-4ee5-97ad-e34cd3b9e4fd.png">

**Comment by callensm** [comment]
closing as this is a data sourcing issue within helius. will converse with them offline.
