### ISSUE TITLE
Improved sent screen

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#3907]
For tokens: [Figma](https://www.figma.com/file/HNF2HJZYq6dUzCWxSmH2Oe/Backpack-_-Questlog?node-id=22328%3A190287&t=lpPccC92vGDof3Vw-1)
For NFTs: [Figma](https://www.figma.com/file/HNF2HJZYq6dUzCWxSmH2Oe/Backpack-_-Questlog?node-id=22328%3A190458&t=lpPccC92vGDof3Vw-1)

**Comment by Merdi-kim** [comment]
Hey @trucy is this issue public to work on? I would like to work on it but I do not have access to the Figma file with the design

**Comment by trucy** [comment]
@Merdi-kim Hey! Thanks for your interest, in this case we're going to have someone internal work on these because there is a whole massive set of changes to all of these drawers and screens

**Comment by Merdi-kim** [comment]
Alright thank you
