### ISSUE TITLE
unable to update from NFT PFP to non-NFT/default PFP

### ISSUE THREAD

**Issue by monk-doesnt** [coral-xyz/backpack#3912]
update button becomes unresponsive
https://user-images.githubusercontent.com/104650166/236596825-0b14a71d-ebf4-4b71-91ae-d6c2297ac72d.mov

**Comment by monk-doesnt** [comment]
To reproduce
1. set NFT PFP
2. go to edit PFP menu
3. press trash icon
4. click update

**Comment by jim4067** [comment]
related #3799
