### ISSUE TITLE
number overflow when sending too many of a token

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#3913]
![image](https://user-images.githubusercontent.com/6990215/236597927-0ff6b479-a864-4a3f-8c83-03b984701d17.png)

**Comment by Merdi-kim** [comment]
I would like to work on this. @armaniferrante could you provide the steps to reproduce this?

**Comment by ksgokul2501** [comment]
https://github.com/coral-xyz/backpack/blob/40b3e0ab75fc8021be7148ae806f6101ec076c0d/packages/app-mobile/src/screens/Unlocked/SendTokenScreen.tsx#LL310C19-L310C19

@armaniferrante This might be the reason however I am not able to reproduce it so please confirm.
