### ISSUE TITLE
Swap details not loading

### ISSUE THREAD

**Issue by Dhruwang** [coral-xyz/backpack#3914]
https://user-images.githubusercontent.com/67850763/236613235-e28df706-53bb-4b85-b73f-2078dfe706aa.mp4

## Steps to Reproduce  
1. Open swap
2. Enter amount in sending

## Console shows following error:
![Screenshot from 2023-05-06 14-07-37](https://user-images.githubusercontent.com/67850763/236613318-d3318594-e57f-4b9b-b5c3-4ca520d1f3eb.png)

**Comment by SaratAngajalaoffl** [comment]
Found the source of the issue, it's being caused when gasEstimation returns null without throwing an error in the following line. Opening a PR that falls back to the default value if gas estimation returns null.
