### ISSUE TITLE
Loading icon on update button in update profile picture screen not visible in dark mode

### ISSUE THREAD

**Issue by SaratAngajalaoffl** [coral-xyz/backpack#3917]
<img width="371" alt="Screenshot 2023-05-06 at 5 25 40 PM" src="https://user-images.githubusercontent.com/60383339/236622527-d9d833e5-ffe8-40ab-9805-2ba42678a27f.png">

**Comment by manishhansal** [comment]
@SaratAngajalaoffl Could you please assign this issue to me? I want to work on this issue.
