### ISSUE TITLE
Add /downloads to Backpack.app

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#3933]
Can be done in 2 stages (left column now, right column after mobile) or all at once later

[Figma](https://www.figma.com/file/q0VTiPf42DXifPPeS7Maz9/Backpack.app?type=design&node-id=308%3A2865&t=5BAMhY7oy3VHZhOx-1)

**Comment by Merdi-kim** [comment]
@trucy Can I work on this issue?

**Comment by punithnayak** [comment]
hey @trucy can i get the mobile view Figma?

**Comment by Merdi-kim** [comment]
@punithnayak I think she first has to allocate the task before all that. At least that is how I have seen it happening
