### ISSUE TITLE
Update press section on backpack.app

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#3936]
Updates
- Make the whole card clickable, remove “read” and use the same hover effect similar to the app cards on xnft.gg
- Swap out articles for the following:
- Coindesk: https://www.coindesk.com/web3/2023/04/21/heavy-demand-for-madlads-nft-breaks-internet-delays-mint/
- Fortune: https://fortune.com/crypto/2023/04/28/solana-cryptocurrency-outperforms-bitcoin-and-ethereum-ytd-mad-lads/
- Blockworks: https://blockworks.co/news/you-know-xnfts
- NFTnow: https://nftnow.com/features/what-are-xnfts-the-new-type-of-token-behind-the-mad-lads-craze/
- Decrypt: https://decrypt.co/137634/solana-nfts-come-to-portfolio-app-floor-amid-mad-lads-boom
- https://www.prnewswire.com/news-releases/backpack-launches-first-solana-xnft-collectio[…]han-jpegs-and-reach-a-mass-consumer-audience-301807194.html

Add simple text section with bullet list links for the older (current 4 articles)

**Comment by Merdi-kim** [comment]
I can pretty much do this. Can I work on this issue @trucy ?
