### ISSUE TITLE
lazily decrypt mnemonic when needed for transaction signing

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#3940]
Right now, we decrypt the mnemonic immediately upon unlocking the wallet. Instead, we should make this optional, and instead lazily decrypt mnemonic when needed for transaction signing. This would allow us to remove the password page for all users.

**Comment by armaniferrante** [comment]
Note: this would also be a solution for the auto-locking problem.

**Comment by RakeshBC1** [comment]
@armaniferrante We can go with the approach to store the encrypted mnemonic in a secure storage mechanism like localStorage, sessionStorage, or a secure cookie. Ensure that the encrypted mnemonic is stored using strong encryption and take appropriate security measures. What's your call on this.
