### ISSUE TITLE
no warning if you don't have enough SOL for a transaction in xNFTs

### ISSUE THREAD

**Issue by wentokay** [coral-xyz/backpack#3977]
if you try to sign and send a transaction inside an xNFT with an account that has `0 SOL`, the `window.xnft.solana.sendAndConfirm` promise will be rejected, the transaction drawer closes and there will be an error in the console, but there's no visual warning about not having enough SOL

<img width="628" alt="Screenshot 2023-05-17 at 10 20 21" src="https://github.com/coral-xyz/backpack/assets/101902546/349fd74c-592d-4eb2-adbe-9a49531622ce">

**Comment by Merdi-kim** [comment]
This is similar to an issue I worked on earlier on to disable the button if the user does not have enough tokens in their wallet. I'd be happy to fix this if someone from the team assigns me the task
