### ISSUE TITLE
search icon is missing in desktop mode

### ISSUE THREAD

**Issue by monk-doesnt** [coral-xyz/backpack#3994]

**Comment by Sivayogeith** [comment]
Hey @monk-doesnt, can you please give more details?

**Comment by mrb1nary** [comment]
![image](https://github.com/coral-xyz/backpack/assets/55779046/f1f7618e-9c42-4fb0-9849-f5bc5e2e8a30)

 The search option goes missing once the extension goes to desktop mode(fullscreen)

**Comment by N-NeelPatel** [comment]
Some fullscreen features are yet to be released, so maybe this issue is because of it
https://github.com/coral-xyz/backpack/blob/f158e284837905f940605badce71fd093f26e8dc/packages/app-extension/src/components/Locked/index.tsx#L46
