### ISSUE TITLE
Unexpected errors thrown from injected.js in ProviderSolanaInjection in xNFT

### ISSUE THREAD

**Issue by KultureElectric** [coral-xyz/backpack#4060]
We're working on an xNFT with the next-react stack. The errors appear to be in every xNFT I checked so far.

It appears in the console. The errors are specifically being thrown from injected.js within ProviderSolanaInjection.

Here are the errors:

```
caught Error: unexpected notification name plugin-notification-connect
    at _mapNotificationName (injected.js:2:2926360)
    at ProviderSolanaInjection._ProviderSolanaInjection_handleNotification (injected.js:2:2929373)

Uncaught Error: unexpected notification name plugin-notification-mount
    at _mapNotificationName (injected.js:2:2926360)
    at ProviderSolanaInjection._ProviderSolanaInjection_handleNotification (injected.js:2:2929373)

Uncaught Error: unexpected notification name plugin-notification-update-metadata
    at _mapNotificationName (injected.js:2:2926360)
    at ProviderSolanaInjection._ProviderSolanaInjection_handleNotification (injected.js:2:2929373)
```    
    
The error messages appear to involve unexpected notifications names:

plugin-notification-connect
plugin-notification-mount
plugin-notification-update-metadata

These errors occur in development mode and do not break any functionality in our application, but they do cause the Next.js development error overlay to appear, which is disruptive to our development process.

Looking forward to having this resolved 🙏

Thank you.

**Comment by wentokay** [comment]
I believe [the fix has been merged into master](https://github.com/coral-xyz/backpack/pull/4011), so they should no longer appear in the next chrome store release. Can you confirm @ph101pp?

**Comment by ph101pp** [comment]
Yes this should be fixed

**Comment by 0xNyk** [comment]
WAO
