### ISSUE TITLE
Can't transfer NFTs in devnet

### ISSUE THREAD

**Issue by KultureElectric** [coral-xyz/backpack#4063]
Error: failed to send transaction: Transaction simulation failed: Attempt to load a program that does not exist

**Comment by jim4067** [comment]
I also faced the same issue with this [nft](https://solscan.io/token/Ffipa5caTU9SvFRAMkQ3dJaHjoXBj2p1PUX46pQFeCKS?cluster=devnet#txs)

Some worked while others did not.
