### ISSUE TITLE
read token-2022 accounts

### ISSUE THREAD

**Issue by monk-doesnt** [coral-xyz/backpack#4095]
https://solscan.io/account/CKfatsPMUf8SkiURsDXs7eK6GWb4Jsd6UDbs7twMCWxo

**Comment by monk-doesnt** [comment]
This token in on the new Token 2022 standard.
![image](https://github.com/coral-xyz/backpack/assets/104650166/d51b7215-84e4-48b4-a543-bb1d4871b767)

**Comment by armaniferrante** [comment]
closed by https://github.com/coral-xyz/backpack/commit/ba018d51cee525038d458a434605dcae77434f84
