### ISSUE TITLE
eth: support eth_signTypedData_v4

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#4113]
Apps like matcha require it

**Comment by steveluscher** [comment]
To add some color here:

Eth implements gasless swaps by:

1. Letting you authorize the DEX to transfer your tokens
2. Signing a transaction to agree to a quote

Presumably then they act as a relayer, paying the gas fee on your behalf and covering it by taking some of your tokens for themselves. For example, you ask for a USDC/ETH swap but have no ETH. They pay the gas in ETH from their treasury, take some of the USDC you've granted them an authorization for, then use the rest of the USDC in the swap itself.

Consider such a swap on [1inch](https://app.1inch.io/#/1/simple/swap/USDC/ETH).

1. Configure the swap
2. Use ‘Fusion’ mode

Backpack has no trouble signing the transaction to grant 1inch transfer rights over your USDC balance, but when it comes time to _actually_ sign the quote to authorize the swap, we get a message that Backpack doesn't support `eth_signTypedData_v4`.

I'm now stuck in a situation where I have an authorization, don't have enough ETH to revoke the authorization, and can't sign the quote to finish the swap 😆
