### ISSUE TITLE
No dark mode support for hardware wallet derivation path selector

### ISSUE THREAD

**Issue by aarongillett** [coral-xyz/backpack#4114]
<img width="458" alt="image" src="https://github.com/coral-xyz/backpack/assets/4157473/577c07ea-1c82-4a98-9e0c-b82299093fa0">

**Comment by Merdi-kim** [comment]
@aarongillett can I work on this issue ?

**Comment by tarunsamanta2k20** [comment]
I would like to work on it.

**Comment by tarunsamanta2k20** [comment]
@aarongillett you don't want dark mode for hardware wallet derivation path selector. Right?

**Comment by shadow0500** [comment]
@aarongillett  I would like to work on this issue.
