### ISSUE TITLE
Not able to setup the project locally

### ISSUE THREAD

**Issue by Malav20** [coral-xyz/backpack#4121]
### Discussed in https://github.com/coral-xyz/backpack/discussions/4106

<div type='discussions-op-text'>

<sup>Originally posted by **Malav20** June  1, 2023</sup>
<br/>
I did yarn install and when I run yarn build I am getting errors.
<br/>
![image](https://github.com/coral-xyz/backpack/assets/20325084/d7d4c0ca-7989-4030-a025-9e90ec58dd15)
<br/>
Not able to run `yarn build` in Windows Systems.
Windows users either have to use git bash or WSL.
</div>

**Comment by fancymithun** [comment]
Yeah.. In windows system yarn build is leading into error message.

**Comment by shadow0500** [comment]
I think you should try gitbash for your solution because gitbash is a terminal that allows you to run unix command.
