### ISSUE TITLE
Window.xnft.solana not injected correctly in deployed xnft

### ISSUE THREAD

**Issue by GabrielePicco** [coral-xyz/backpack#4122]
Hi,
I'm experiencing a strange behaviour with an xnft in mainet which I haven't been able to fix yet. 

The window.xnft.solana it's not injected correctly when running the installed xnft (https://www.xnft.gg/app/8fUFbAjZjN5Pij6xnbKu7v7K55q2pTSWP1ci4grsC1TK). Below the screenshot from the developer console, after opening the xnfts, before any interaction.

![photo_2023-06-01_10-05-53](https://github.com/coral-xyz/backpack/assets/12031208/3e1c337a-9916-46b2-ab23-9087a0269e4e)

Strangely it works fine in the simulator. I also tried with other xnfts, and window.xnft.solana is injected correctly. Below a screenshot using a different xnft:

![photo_2023-06-01_10-05-26](https://github.com/coral-xyz/backpack/assets/12031208/b8868eac-a351-4760-a7b8-ed2a51e00f08)

Suggestions on what it could be?

**Comment by wentokay** [comment]
it seems to work ok for me right now

can you share any more details about exactly what you're doing to get this state?

https://github.com/coral-xyz/backpack/assets/101902546/b0efe21e-7d0e-420e-9d8c-523a6a42c053

is it the chrome store release of backpack? Thanks!

**Comment by GabrielePicco** [comment]
Thanks for the fast reply, seems that the issue is now solved. I was trying with different versions/accounts and I was getting the same behaviour, but I can't reproduce anymore the problem, which is great!

Closing as solved. Thanks.

**Comment by wentokay** [comment]
Great! Please do reopen this issue if you notice it happen again, especially if there are steps to reproduce it.
