### ISSUE TITLE
lock screen slide-up menu has no background in dark mode

### ISSUE THREAD

**Issue by wentokay** [coral-xyz/backpack#4151]
https://github.com/coral-xyz/backpack/assets/101902546/ed7bd0bc-3524-427d-ab2a-fe8e48daa011

✅  | ❌ 
--|--
<img width="487" alt="Screenshot 2023-06-12 at 10 15 43" src="https://github.com/coral-xyz/backpack/assets/101902546/e008cb93-59ee-4781-82be-6199856741c4">|<img width="487" alt="Screenshot 2023-06-12 at 10 15 26" src="https://github.com/coral-xyz/backpack/assets/101902546/a9b29f56-f35f-4f04-b0ff-7804ac40a516">

**Comment by Merdi-kim** [comment]
@wentokay can I work on this issue?

**Comment by tarunsamanta2k20** [comment]
I'd like to look into this
