### ISSUE TITLE
no keyring for solana - On chrome for testing

### ISSUE THREAD

**Issue by Virus-Axel** [coral-xyz/backpack#4307]
I am trying to run backback on chrome and sign a transaction. When running on my normal chrome browser this works fine, but when I run a fresh test browser I get the following.

"Error: no keyring for solana
    at gm.keyringForBlockchain (chrome-extension://pfangmoebabcjmjkcmkmompfhpochfbh/background.js:2:3144752)
    at kC.getTransactionSignature (chrome-extension://pfangmoebabcjmjkcmkmompfhpochfbh/background.js:2:3737289)
    at kC.handleSign (chrome-extension://pfangmoebabcjmjkcmkmompfhpochfbh/background.js:2:3736367)"

I am installing backpack on chrome and creating a new wallet without restarting the browser and then signing. I can clearly see that I have a solana wallet that can sign.

I am running:
Chrome for testing - Version 123.0.6312.122 (Official Build) (64-bit)
Backpack - version 10.1 beta build 4

**Comment by Virus-Axel** [comment]
I ran the same thing on a normal chrome instead of test-browser and I still get  "no keyring for solana".
Do I need to restart chrome after a recruitment?

**Comment by armaniferrante** [comment]
`10.1` is a *very* old build. Please use the latest. For support, please see https://support.backpack.exchange/en/articles/1219073. We are not monitoring github issues and only provide this repo as a reference.

**Comment by jeisses** [comment]
Version `10.1` is tagged as `latest` under the GitHub releases, it would be good to remove the GitHub releases if they are not intended to be used, to avoid confusion

@armaniferrante do you still provide a download for the Chrome extension outside of the chrome webstore?

**Comment by keene2** [comment]
> `10.1`是一个_非常_旧的版本。请使用最新版本。如需支持，请参阅https://support.backpack.exchange/en/articles/1219073。我们没有监控 github 问题，仅提供此 repo 作为参考。

The link to the article is no longer valid. Where can I find it？

I had the same problem
