### ISSUE TITLE
Is this repository active?

### ISSUE THREAD

**Issue by Arslan-Muhammad** [coral-xyz/backpack#4351]
Is this repository still openSource or not?

**Comment by kitty4D** [comment]
i would also like to know this, since the website has 

<img width="432" alt="image" src="https://github.com/user-attachments/assets/cc48d764-2c36-427b-a39f-26d179e450a6" />

and then links directly here.  ty

**Comment by armaniferrante** [comment]
No we should remove that. Thanks for proding.
