### ISSUE TITLE
disallow importing the same pubkey twice

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#621]
<img width="363" alt="Screen Shot 2022-08-14 at 4 04 03 PM" src="https://user-images.githubusercontent.com/489202/184522015-7ab7ed7a-7f69-4f1b-ae5a-330973666f7f.png">

Name of the second import will overwrite the existing name of the first so they both end up with the same name.

I can't think of any good reason to allow this so we should error when import is attempted.

**Comment by colinlgray** [comment]
This issue should be resolved now with PR #989 being merged in

**Comment by armaniferrante** [comment]
Done.
