### ISSUE TITLE
ledger signing prompt for send transaction

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#805]
This has a spinner when it is waiting for a signature which is confusing.

<img width="375" alt="Screen Shot 2022-09-19 at 11 36 04 AM" src="https://user-images.githubusercontent.com/489202/190933227-3979cb5a-65d2-4d06-9c90-a8ca8ab9bd84.png">

**Comment by aarongillett** [comment]
Addressed with [issue 3469]( https://github.com/coral-xyz/backpack/issues/3469)
