### ISSUE TITLE
ledger signing prompt for burn nft

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#806]
Clicking confirm brings up the signing request on a Ledger but the UI does not change at all.

<img width="374" alt="Screen Shot 2022-09-19 at 11 51 56 AM" src="https://user-images.githubusercontent.com/489202/190933435-6533030e-2ede-4a51-8005-d355e253f587.png">

**Comment by aarongillett** [comment]
Addressed with [3469](https://github.com/coral-xyz/backpack/issues/3469)
