### ISSUE TITLE
react-xnft: provide ability to disable button

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#811]

**Comment by hkirat** [comment]
I'm assuming this involves passing down the `disabled` prop to the `MuiButton` [here](https://github.com/coral-xyz/backpack/blob/master/packages/react-xnft-renderer/src/Component.tsx#L843) ?

If yes, is there a design specification to follow for the disabled buttons?
Would like to take this up unless someone is already working on this.

**Comment by hkirat** [comment]
Is this a dupe of https://github.com/coral-xyz/backpack/issues/774 ?

**Comment by ThornM9** [comment]
@hkirat happy to take this on

**Comment by armaniferrante** [comment]
Yup dup of #774.
