### ISSUE TITLE
view balances from send screen doesn't work

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#815]
Just closes the send confirmation drawer.

<img width="383" alt="Screen Shot 2022-09-20 at 5 30 12 PM" src="https://user-images.githubusercontent.com/489202/191174936-07a9d538-a19e-4ea5-b12f-ceafc707e59b.png">

**Comment by tomlinton** [comment]
Similarly clicking the below wallet address just closes the drawer rather than taking you back to the wallet screen.

<img width="378" alt="Screen Shot 2022-09-30 at 4 14 24 PM" src="https://user-images.githubusercontent.com/489202/193182408-cf549f8c-7693-4942-8171-e7e1812dce59.png">

**Comment by aarongillett** [comment]
This is still an issue with the new send screen 
<img width="487" alt="Screenshot 2023-03-02 at 21 51 04" src="https://user-images.githubusercontent.com/4157473/222549654-26d2c3fc-192a-476b-ac68-7ba9c21e1b98.png">
