### ISSUE TITLE
xnft-cli: command to initialize an simple xnft

### ISSUE THREAD

**Issue by Gajesh2007** [coral-xyz/backpack#819]
`init` command to initialize a simple xnft instead of cloning `xnft-quickstart` again and again. 

example implemention: 
<img width="507" alt="Screenshot 2022-09-21 at 5 46 50 PM" src="https://user-images.githubusercontent.com/26431906/191616398-bff0d02f-27a8-406a-a7b7-00466152557c.png">

**Comment by 0xMukesh** [comment]
Hey, can I work on this issue?

**Comment by Gajesh2007** [comment]
I've already wrote the code for it in the screenshot.

Just need to open a PR

@armaniferrante should there be any changes into the attached code?

**Comment by armaniferrante** [comment]
@Gajesh2007 open the PR and we can chat there.
