### ISSUE TITLE
provide ability to create a wallet with a ledger

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#830]
right now the keyring assumes the existence of a mnemonic

**Comment by Arrowana** [comment]
This is one of the most horrid UX aspect of most wallets out there.

**Comment by tomlinton** [comment]
Related https://github.com/coral-xyz/backpack/issues/678

**Comment by tomlinton** [comment]
Closing as duplicate of https://github.com/coral-xyz/backpack/issues/994
