### ISSUE TITLE
Username application typeform error

### ISSUE THREAD

**Issue by aarongillett** [coral-xyz/backpack#867]
The _Apply for an Invite Code_ button launches typeform in a small window, rather than a full-screen view.
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/4157473/192227713-35bda62f-e940-422b-825b-4eaa370184d1.png">

**Comment by wentokay** [comment]
fixed in https://github.com/coral-xyz/backpack/pull/866, thanks!
