### ISSUE TITLE
“Try more passwords” button should link to "Change password" screen when navigated to from the "Change password" screen.

### ISSUE THREAD

**Issue by aarongillett** [coral-xyz/backpack#869]
If a user is on the change password screen:
<img width="373" alt="image" src="https://user-images.githubusercontent.com/4157473/192271813-73e4710d-c082-4f7f-93d5-629d4a4db8ca.png">

…and then selects forgot password:
<img width="373" alt="image" src="https://user-images.githubusercontent.com/4157473/192271283-2b0aa74b-d6da-4bc6-b337-c4b7475421bd.png">

The _Try more passwords_ button should link back to the previous _change password_ screen.

If the user navigates to the Forgot password screen from the lock screen, the _Try more passwords_ button should link to the lock screen.

**Comment by NevilleMthw** [comment]
Hi, could I know which file the underlying implementation is in? Is it a ```.ts``` file?
