### ISSUE TITLE
Request: Add Audio tag

### ISSUE THREAD

**Issue by swolswolomon** [coral-xyz/backpack#872]
Please add audio component (from html5). I'm building an xnft that needs to play a sound when an item is clicked. Thanks!

**Comment by hkirat** [comment]
This sounds (no pun intended) very tempting to work on, but I think `react-native` doesn't have `audio` or `video` as part of their core APIs. There are community projects out there that implement media for RN (Eg: https://github.com/react-native-video/react-native-video/)

I'm unsure if this would be in line with the initial set of components that backpack wants to release, but I could be wrong. @armaniferrante can elaborate more on it. 

In case this does lie in the roadmap to be part of a core components API I can work on this. This specific use case might be useful for me as well in the future.

**Comment by armaniferrante** [comment]
Closing this as handled by #1061, which adds support for custom types in the reconciler, e.g., to create an audio tag.

**Comment by swolswolomon** [comment]
Thanks! I see it merged, but I don't see Custom in my version. I'm set to latest.
`import { **Custom** } from "react-xnft";`

**Comment by hkirat** [comment]
You need to set it to `*` if you're using this mono repo

**Comment by swolswolomon** [comment]
thanks, i switched and now i do see new components, such as Table (which is cool)...but not Custom

**Comment by hkirat** [comment]
Can you run `cat ./node_modules/react-xnft/src/elements.tsx`  in the root of your project and paste the contents here?

**Comment by swolswolomon** [comment]
import React from "react";
export declare const Text: (props: any) => React.DOMElement<any, Element>;
export declare const TextField: (props: any) => React.DOMElement<any, Element>;
export declare const Image: (props: any) => React.DOMElement<any, Element>;
export declare const Table: (props: any) => React.DOMElement<any, Element>;
export declare const TableHead: (props: any) => React.DOMElement<any, Element>;
export declare const TableRow: (props: any) => React.DOMElement<any, Element>;
export declare const TableFooter: (props: any) => React.DOMElement<any, Element>;
export declare const View: (props: any) => React.DOMElement<any, Element>;
export declare const Button: (props: any) => React.DOMElement<any, Element>;
export declare const Loading: (props: any) => React.DOMElement<any, Element>;
export declare const ScrollBar: (props: any) => React.DOMElement<any, Element>;
export declare const Svg: (props: any) => React.DOMElement<any, Element>;
export declare const Path: (props: any) => React.DOMElement<any, Element>;
export declare const Circle: (props: any) => React.DOMElement<any, Element>;
export declare const NavAnimation: (props: any) => React.DOMElement<any, Element>;
export declare const Iframe: (props: any) => React.DOMElement<any, Element>;
export declare const BalancesTable: (props: any) => React.DOMElement<any, Element>;
export declare const BalancesTableContent: (props: any) => React.DOMElement<any, Element>;
export declare const BalancesTableHead: (props: any) => React.DOMElement<any, Element>;
export declare const BalancesTableRow: (props: any) => React.DOMElement<any, Element>;
export declare const BalancesTableCell: (props: any) => React.DOMElement<any, Element>;
export declare const BalancesTableFooter: (props: any) => React.DOMElement<any, Element>;
//# sourceMappingURL=elements.d.ts.map

**Comment by hkirat** [comment]
What commit are you on locally?

**Comment by swolswolomon** [comment]
i thought your commit (d1644196be3f62823cf1d069517608c74a39e86c) was merged with master.  I'm just using npm, not pulling a specific commit. I'm happy to use your branch, but i don't want to fall behind

**Comment by hkirat** [comment]
Can you try pulling the latest `master` ?

**Comment by swolswolomon** [comment]
oh, ok... do you know the timing for updating the npm repo from master?

**Comment by swolswolomon** [comment]
maybe that's a manual thing from @armaniferrante

**Comment by hkirat** [comment]
It looks like `latest` represents the latest commit (we should probably change that and gate this on releases) - https://www.npmjs.com/package/react-xnft
