### ISSUE TITLE
react-xnft: add textarea

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#888]

**Comment by hkirat** [comment]
Is this the component to be used to build the textarea component - https://mui.com/material-ui/react-textarea-autosize/ ?
If yes can I assign this to myself unless this is already taken?

**Comment by armaniferrante** [comment]
@hkirat yes though the API should be analgous to react-native's https://reactnative.dev/docs/textinput#multiline. That is, we have a single `react-xnft` API  to handle but the current text field and the multi-line textarea component.
