### ISSUE TITLE
Username and avatar apis for xNFTs

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#929]
Request: https://discord.com/channels/985994296337498182/1023734988690182165/1025184530480500767

**Comment by tpompon** [comment]
I'm the writer of the original message on Discord and what I was talking about is the username that you can claim which you can see when you open your wallet `gm @johndoe`

**Comment by armaniferrante** [comment]
> Could you explain what `username` means here? Is it the Wallet identifier? Or is there a global username in the wallet that I'm missing.

We are working on a global cross chain identity system currently. We'll share more information on the design and implementation soon.

**Comment by hkirat** [comment]
Ah gotcha yeah I see it now with the `BACKPACK_FEATURE_USERNAMES` flag set to true.
