### ISSUE TITLE
Installing backpack extension seems to break metamask on other EVM dapps

### ISSUE THREAD

**Issue by TikiCat7** [coral-xyz/backpack#937]
Not sure why but after installing the backpack extension my metamask stopped being able to connect to other Dapps on non-solana blockchains. Maybe some pollution of global namespaces?

Steps to reproduce:

1. install backpack extension
2. use any metamask supporting DAPP (for example I used https://quickswap.exchange/#/swap) on Polygon
3. metamask not recognized
![image](https://user-images.githubusercontent.com/15680763/193248088-0f94b27c-1cf1-4d5d-9530-21dcd9244ecd.png)
4. attempting to switch networks prompts an error in the console related to backpack
![image](https://user-images.githubusercontent.com/15680763/193247800-0ef82fbc-64c0-4346-ac3a-eb577be75b20.png)
5. removing the backpack extension resolved the issue for me

**Comment by subhojyotisaha** [comment]
Faced the same issue as @TikiCat7  Lots of EVM dApps that I use were not able to detect Metamask and were asking me to install Metamask.
Disabling the backpack extension resolved the issue.

**Comment by tomlinton** [comment]
Thanks for the reports! This was addressed in https://github.com/coral-xyz/backpack/commit/8c160cfb4c45a600232b1dd527c906bb476d76ae and should be fixed in the next release.
