### ISSUE TITLE
Balance percentage evolution showing NaN instead of value

### ISSUE THREAD

**Issue by tpompon** [coral-xyz/backpack#954]
**The problem**
As you can see on the screenshot, the evolution in percentage of SOL balance is showing `NaN`.
I assume that this is because my wallet is recent and there is no previous data.

<img width="364" alt="image" src="https://user-images.githubusercontent.com/34953239/193378005-8bb2249b-8091-4e48-912f-76e7271ca191.png">

**Suggested solution**
Hide it or show something else as default when there is not enough data the evolution percentage

**Comment by tomlinton** [comment]
Duplicate of https://github.com/coral-xyz/backpack/issues/1015, should be resolved now.
