### ISSUE TITLE
 ‘Inaccurate Public Key’ for a real key

### ISSUE THREAD

**Issue by nickFNY** [coral-xyz/backpack#963]
Received ‘Inaccurate Public Key’ for a real key. Key was 2nd derived address on wallet. 

pubkey in question: 4ggs6aHNa6cjea5Bgg7uh9zQ4Zfmx3pmg8wRc2Ju5CWd

**Comment by tomlinton** [comment]
What was he user doing at the time? Sending tokens?

Is that the correct error message? Doesn't seem like an error we display anywhere.

**Comment by nickFNY** [comment]
Yes they were sending tokens. 'Error: Invalid Public Key Input'

**Comment by tomlinton** [comment]
Was this happening during the Solana downtime?

**Comment by nickFNY** [comment]
Nope
