### ISSUE TITLE
Text overflow oust-side of background box on secret recovery phrase page

### ISSUE THREAD

**Issue by nickFNY** [coral-xyz/backpack#966]
secret recovery phrase stage text flows over background box. 

 image: [https://discord.com/channels/971847939456639047/1025538150719819797/1026103272001523802](url)

**Comment by tomlinton** [comment]
![unknown](https://user-images.githubusercontent.com/489202/193479925-3f47f53b-fe8f-4abf-bd67-e28c5b8c8226.png)
