### ISSUE TITLE
multiple transaction simulation 

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#976]
When signing for multiple transactions we don't have any useful simulation/information. Possible design is to simulate all the transactions and have a slider to scroll between each transaction (so each transaction is just displayed as if it were a single transaction).

This needs to be implemented for both the page injected provider and the xnft provider.

<img width="374" alt="Screen Shot 2022-10-03 at 12 20 55 PM" src="https://user-images.githubusercontent.com/489202/193480782-c6499f49-6296-4325-b278-77e5697b69f7.png">

**Comment by armaniferrante** [comment]
Multiple transactions should be rare. P3. Please comment on the thread here if you need this so that we can adjust priority accordingly.

**Comment by armaniferrante** [comment]
P1 as this happens all the time via exchange art.

**Comment by tomlinton** [comment]
Will implement it with a slider type setup.
