### ISSUE TITLE
react-xnft: useTheme should change when the host theme changes

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#985]
This is currently not implemented https://github.com/coral-xyz/backpack/blob/master/packages/react-xnft/src/Context.tsx#L32.

**Comment by Benhawkins18** [comment]
following

**Comment by armaniferrante** [comment]
Blocked by https://github.com/coral-xyz/backpack/pull/1090

**Comment by armaniferrante** [comment]
Unblocked indeed!

**Comment by hkirat** [comment]
Closed via https://github.com/coral-xyz/backpack/pull/1217
