### ISSUE TITLE
Eth transaction errors are not caught

### ISSUE THREAD

**Issue by hkirat** [coral-xyz/backpack#992]
Slightly related to https://github.com/coral-xyz/backpack/pull/904

If I try `Sending an Ethereum Transaction` from an empty wallet, there is an uncaught exception. 
<img width="1720" alt="Screenshot 2022-10-04 at 1 58 23 AM" src="https://user-images.githubusercontent.com/8079861/193676810-8c04382e-cc2e-4b22-bd7b-adab960e2b20.png">
<img width="367" alt="Screenshot 2022-10-04 at 1 58 18 AM" src="https://user-images.githubusercontent.com/8079861/193676849-67b5eb60-8b28-49bb-ac76-01ea0350a222.png">

This is different from https://github.com/coral-xyz/backpack/pull/904 where the exception occurs after the user has clicked on the approve button.

In this particular case the exception occurs even before the user clicks on the `Approve` button.

Not sure what the right UX is here - 
1. Should we immediately close the `Approval Popup` and surface the exception to the developer?
2. Should we maybe show a warning to the user that this transaction might fail even if you click on `approve` ? 
3. Should we just catch and silently ignore this exception?

**Comment by armaniferrante** [comment]
We probably want to immediately show the error on the same Approval Popup drawer. Putting on design.
